/* Vertiefung & Alltagsbeispiele – KOMMU (Kommunikationstraining)
   Alle Dialoge sind erfundene Übungssituationen. KI ist in KOMMU für bewertete Arbeiten verboten:
   Diese Texte sind reines Lernmaterial und niemals als Portfolio- oder Deep-Talk-Abgabe zu verwenden. */
(function () {
window.STUDYOS_DEEP = window.STUDYOS_DEEP || {};
window.STUDYOS_DEEP["kommu"] = {

  /* ================= Welt 1: Grundlagen ================= */
  "k1-1": [
    { t: "text", h: "Vertiefung: Warum Kommunikation an jeder Station scheitern kann", levels: {
      simple: `Eine Nachricht reist von deinem Kopf in den Kopf einer anderen Person. Unterwegs kann viel passieren: Sie hört dich nicht (Lärm), sie versteht ein Wort anders, sie ist nicht einverstanden, sie vergisst es oder sie tut es einfach nicht. Darum heißt „Ich hab's dir doch gesagt!“ noch lange nicht, dass die Botschaft angekommen ist. Wer gut kommuniziert, prüft nach: Hat mich die andere Person gehört? Verstanden? Ist sie einverstanden? Das geht am einfachsten mit einer Rückfrage („Passt das für dich so?“).`,
      normal: `Die Lasswell-Formel (Harold Lasswell, 1948) zerlegt jede Kommunikation in fünf Fragen: <b>Wer</b> (Senderin) sagt <b>was</b> (Botschaft) <b>zu wem</b> (Empfängerin) über <b>welchen Kanal</b> (Medium) mit <b>welcher Wirkung</b> (Effekt)? Technischer gedacht (Sender-Empfänger-Modell nach Shannon/Weaver): Die Senderin <b>codiert</b> einen Gedanken in Zeichen (Wörter, Tonfall, Gesten), schickt sie über einen Kanal, auf dem <b>Störungen</b> („Rauschen“) wirken, und die Empfängerin <b>decodiert</b> die Zeichen wieder – mit <i>ihrem</i> Wortschatz, <i>ihren</i> Erfahrungen und <i>ihrer</i> Stimmung. Gemeint und verstanden sind deshalb nie automatisch dasselbe.<br><br>Die Lorenz-Kette zeigt, dass Kommunikation nicht beim „Gesagt“ endet: Erst wenn die Botschaft gehört, verstanden, akzeptiert, behalten und schließlich angewandt wird, war sie <b>wirksam</b>. Jede Stufe hat ihre eigene Bruchstelle: Lärm (gehört), Fachjargon (verstanden), fehlende Begründung (einverstanden), zu viel Info auf einmal (behalten), kein konkreter nächster Schritt (angewandt).<br><br>Das wichtigste Gegenmittel ist <b>Rückkopplung (Feedback)</b>: Aus einseitiger wird wechselseitige Kommunikation, die Senderin erfährt, was angekommen ist. Das zweite ist <b>Redundanz</b>: Wichtiges wiederholen, auf zwei Kanälen senden (mündlich + schriftlich) oder mit einem Beispiel absichern.`,
      technical: `Lasswells Formel ist ein lineares Modell: Sie beschreibt Kommunikation als Übertragung von A nach B und blendet die Rückkopplung aus. Das Shannon-Weaver-Modell (1949) ergänzt Codierung, Kanal, Rauschquelle und Decodierung; Information geht verloren, wenn Störung den Kanal überlagert. Redundanz (Wiederholung, Mehrkanaligkeit, sprachliche Überbestimmung wie die Übereinstimmung von Artikel und Nomen) erlaubt es, Fehler zu erkennen und zu korrigieren – darum sind natürliche Sprachen stets teilweise redundant. Für zwischenmenschliche Kommunikation reicht das technische Modell nicht: Zeichen sind mehrdeutig, und die Empfängerin konstruiert die Bedeutung aktiv. Daraus folgen die psychologischen Modelle dieser Lehrveranstaltung: Schulz von Thun (eine Nachricht hat vier Seiten), Watzlawick (Beziehungsebene bestimmt den Inhalt) und die GFK (Bedeutung entsteht aus Gefühlen und Bedürfnissen). Kommunikationsformen lassen sich zusätzlich nach Richtung (uni-/bidirektional) und Anzahl der Beteiligten (1:1, 1:n, n:1, n:n) ordnen.` } },
    { t: "example", title: "WG-Abwasch: an welcher Station bricht es ab?", html: `In der WG von Kevin, Sophie und Paul stapelt sich das Geschirr. <b>Vorher:</b><br><i>Sophie (ruft im Vorbeigehen aus dem Flur, Musik läuft):</i> „Wir sollten mal was wegen dem Abwasch machen!“<br><i>Paul:</i> „Mhm.“<br>Drei Tage später ist nichts passiert. Analyse mit der Lorenz-Kette: <b>gesagt</b> ✔ · <b>gehört</b> – nur halb (Musik = physische Störung) · <b>verstanden</b> – „mal was machen“ ist unklar · <b>einverstanden</b> – „Mhm“ ist keine Zustimmung · <b>behalten / angewandt</b> – kein konkreter Schritt, also nichts.<br><br><b>Nachher:</b><br><i>Sophie (Musik leiser, alle am Küchentisch):</i> „Ich möchte kurz über den Abwasch reden. Mein Vorschlag: Jeder spült am Abend sein eigenes Geschirr, und die Töpfe übernimmt reihum einer pro Woche. Passt das für euch?“<br><i>Paul:</i> „Für mich ja – ich fang diese Woche mit den Töpfen an.“<br><i>Sophie:</i> „Super, ich häng den Plan an den Kühlschrank.“<br>Die Rückfrage sichert <b>einverstanden</b>, der Plan am Kühlschrank ist <b>Redundanz</b> (zweiter Kanal) und sichert <b>behalten</b>.` },
    { t: "example", title: "Gruppenarbeit an der FH: Kanal und Kommunikationsform", html: `Lena schreibt in den WhatsApp-Chat ihrer vierköpfigen Projektgruppe: „Abgabe ist Freitag 12:00, bitte eure Teile bis Mittwoch hochladen.“ Nach Lasswell: <b>Wer</b> = Lena (Senderin), <b>was</b> = Termin + Aufgabe (Botschaft), <b>zu wem</b> = drei Gruppenmitglieder, <b>Kanal</b> = Gruppenchat, <b>Wirkung</b> = soll Upload bis Mittwoch auslösen. Form: 1:n und zunächst einseitig. Problem: 47 andere Nachrichten über Pizza überdecken ihre Nachricht – das ist „Rauschen“ auf dem Kanal. Lena verbessert: Sie pinnt die Nachricht an (Redundanz), fragt „Kurzes 👍 von allen, damit ich weiß, dass es angekommen ist?“ (Rückkopplung macht daraus wechselseitige Kommunikation) und trägt den Mittwoch-Termin zusätzlich im gemeinsamen Kalender ein (zweiter Kanal).` },
    { t: "hint", title: "Eselsbrücke für die Lorenz-Kette", html: `Merksatz: <b>„Sagen heißt nicht Tun“</b> – und dazwischen liegen vier Stufen. Merke die Reihenfolge mit <b>G-H-V-E-B-A</b>: <b>G</b>esagt, <b>H</b>ört, <b>V</b>ersteht, <b>E</b>inverstanden, <b>B</b>ehält, <b>A</b>nwendet – „<b>G</b>ute <b>H</b>ühner <b>V</b>ertragen <b>E</b>infach <b>B</b>esser <b>A</b>pfelkerne“.` },
    { t: "hint", title: "Typische Verwechslung: Kanal vs. Botschaft", html: `„E-Mail“, „Telefon“, „Plakat“ sind immer der <b>Kanal (Medium)</b>, nie die Botschaft. Die Botschaft ist der Inhalt („Treffen um 10 Uhr“). Bei Zuordnungsaufgaben zuerst fragen: Wie viele senden, wie viele empfangen, und kann die Empfängerin direkt antworten? Ein Voting im Hörsaal ist z. B. <b>n:1</b> – viele senden ihre Stimme an eine Stelle.` },
    { t: "hint", title: "So nutzt du das im Alltag", html: `Wenn etwas Wichtiges „nicht ankommt“, frag nicht „Wer ist schuld?“, sondern „An welcher Station der Kette ist es hängen geblieben?“ Gegen <b>gehört</b>-Probleme hilft ein ruhiger Moment, gegen <b>verstanden</b>-Probleme einfache Sprache, gegen <b>einverstanden</b>-Probleme eine Begründung und eine echte Frage, gegen <b>behalten/angewandt</b>-Probleme ein konkreter nächster Schritt mit Datum.` }
  ],

  /* ================= Welt 2: Schulz von Thun ================= */
  "k2-1": [
    { t: "text", h: "Vertiefung: Vier Schnäbel, vier Ohren – und warum es knallt", levels: {
      simple: `Jeder Satz sagt vier Dinge auf einmal: eine Sache, etwas über mich, etwas über unsere Beziehung und einen Wunsch an dich. Ich kann nicht steuern, welches dieser vier Dinge du hörst. Wenn ich nur die Sache meine („Der Mülleimer ist voll“) und du einen Vorwurf hörst („Du bist faul“), streiten wir über etwas, das ich gar nicht sagen wollte. Hilfe: Nachfragen, wie es gemeint war, und selbst klarer sagen, was man möchte.`,
      normal: `Friedemann Schulz von Thun („Miteinander reden 1“, 1981) nennt das Modell <b>Kommunikationsquadrat</b>. Jede Nachricht hat vier Seiten:<br>• <b>Sachinhalt</b> – worüber ich informiere (prüfbar: wahr/unwahr, relevant, hinlänglich).<br>• <b>Selbstkundgabe</b> – was ich (gewollt oder ungewollt) über mich zeige: Stimmung, Werte, Kompetenz.<br>• <b>Beziehungshinweis</b> – was ich von dir halte (Du-Botschaft) und wie wir zueinander stehen (Wir-Botschaft). Läuft stark über Tonfall, Mimik, Wortwahl.<br>• <b>Appell</b> – wozu ich dich bringen möchte, offen („Mach bitte …“) oder verdeckt.<br><br>Wichtig: Diese Seiten können <b>explizit</b> (ausdrücklich gesagt) oder <b>implizit</b> (nur mitgemeint) sein. Und sie können <b>kongruent</b> (alles passt zusammen) oder <b>inkongruent</b> sein (Worte freundlich, Ton genervt).<br><br>Auf der Empfangsseite entscheidet die Empfängerin – meist unbewusst –, mit welchem Ohr sie vorrangig hört. Viele Menschen haben <b>Empfangsgewohnheiten</b>: Wer ein großes Beziehungsohr hat, fühlt sich schnell angegriffen; wer ein großes Appellohr hat, springt sofort, um es allen recht zu machen; wer nur das Sachohr hat, übersieht Gefühle. Das Gegenmittel heißt <b>Metakommunikation</b>: über die Kommunikation selbst sprechen („Wie hast du das gemeint?“).`,
      technical: `Das Modell verbindet Bühlers Organonmodell (Darstellung, Ausdruck, Appell) mit Watzlawicks Beziehungsaspekt. Analytisch ist eine Äußerung ein vierdimensionales Bündel; die Gewichtung der Seiten ist kontextabhängig und wird von der Empfängerin konstruiert („Die Nachricht entsteht beim Empfänger“). Störungsquellen: (1) die Senderin codiert eine Seite implizit, die Empfängerin decodiert eine andere; (2) inkongruente Nachrichten, bei denen verbale und nonverbale Anteile widersprechen; (3) einseitige Empfangsgewohnheiten. Bei der Sachseite gelten die Prüfkriterien wahr/unwahr, relevant/irrelevant und hinlänglich/unzureichend. Der Appell kann offen oder verdeckt sein; verdeckte Appelle wirken oft über die Selbstkundgabe („Ich bin so müde …“ → mach du das). Die Beziehungsseite hat zwei Komponenten: Wertschätzung bzw. Geringschätzung des Gegenübers (Du) und Definition der Beziehung (Wir). Praktische Konsequenz: Klare Kommunikation macht die gemeinten Seiten explizit; klärende Kommunikation fragt nach der gemeinten Seite.` } },
    { t: "example", title: "WG-Streit über den Abwasch – ein Satz, vier Seiten", html: `Kevin kommt in die Küche und sagt zu Paul: „Da steht noch dein Topf von gestern.“<br><table class="dt"><tr><th>Seite</th><th>Was Kevin (vielleicht) sendet</th></tr><tr><td>Sachinhalt</td><td>Ein Topf von gestern steht in der Spüle.</td></tr><tr><td>Selbstkundgabe</td><td>Ich will jetzt kochen und bin genervt.</td></tr><tr><td>Beziehung</td><td>Du hältst dich nicht an unsere Abmachung.</td></tr><tr><td>Appell</td><td>Spül ihn bitte ab.</td></tr></table><b>Vorher</b> (Paul hört mit dem Beziehungsohr):<br><i>Paul:</i> „Ach, und deine Pfanne letzte Woche ist drei Tage gestanden, Herr Perfekt!“<br><b>Nachher</b> (Kevin macht die Seiten explizit, Paul fragt nach):<br><i>Kevin:</i> „Da steht noch dein Topf von gestern. Ich will gleich kochen und brauch ihn – magst du ihn schnell abwaschen?“<br><i>Paul:</i> „Ah, okay. Ich dachte kurz, du willst mir wieder eine Predigt halten. Mach ich gleich.“<br>Kevin hat <b>Selbstkundgabe</b> und <b>Appell</b> ausgesprochen, Paul hat seine Beziehungs-Deutung offengelegt – das ist Metakommunikation.` },
    { t: "example", title: "Gespräch mit der Mutter – welches Ohr ist an?", html: `Kevins Mutter am Telefon: „Wir haben uns ja schon lange nicht mehr gesehen.“<br><b>Sachinhalt:</b> Das letzte Treffen ist lange her. <b>Selbstkundgabe:</b> Ich vermisse dich. <b>Beziehung:</b> Du bist mir wichtig (oder: Du kümmerst dich zu wenig). <b>Appell:</b> Komm vorbei.<br><b>Vorher:</b> Kevin hört nur Beziehung + Appell als Vorwurf: „Mama, ich hab halt Prüfungen, ich kann nicht jedes Wochenende heimfahren!“ – Die Mutter ist verletzt, denn sie wollte vor allem die Selbstkundgabe senden.<br><b>Nachher:</b> Kevin hört bewusst mit dem Selbstkundgabe-Ohr: „Klingt, als würdest du mich vermissen?“ – <i>Mutter:</i> „Ja, schon ein bisschen.“ – <i>Kevin:</i> „Ich dich auch. Am 15. hab ich frei, passt dir Mittagessen?“ Gleiche Nachricht, anderes Ohr – völlig anderes Gespräch.` },
    { t: "hint", title: "Farben & Reihenfolge merken", html: `Denk an <b>Himmel und Ampel</b>: <b style="color:#4C9EFF">blauer</b> Himmel = Sache (kühl, sachlich), <b style="color:#8BD126">grün</b> = Selbstkundgabe (ich gebe „grünes Licht“ für mein Inneres), <b style="color:#EAB308">gelb</b> = Beziehung (Achtung, empfindlich!), <b style="color:#F0616D">rot</b> = Appell (Signal zum Handeln – „tu was“).` },
    { t: "hint", title: "So löst du Analyse-Aufgaben", html: `1) Schreibe den Satz wörtlich auf. 2) Formuliere zu jeder Seite <b>einen Satz aus Sicht der Senderin</b>: Sache „Es ist …“, Selbstkundgabe „Ich bin/fühle …“, Beziehung „Du bist …/Wir sind …“, Appell „Tu …!“. 3) Bestimme, mit welchem Ohr die Empfängerin <b>geantwortet</b> hat – die Antwort verrät das Ohr. Wer sich rechtfertigt, hat fast immer das Beziehungsohr benutzt.` },
    { t: "hint", title: "Prüfungsfalle: Selbstkundgabe ≠ Beziehung", html: `„Ich bin müde“ ist Selbstkundgabe (über mich). „Du bist anstrengend“ ist Beziehung (über dich/uns). Merke: Bei der Selbstkundgabe kommt das Gegenüber gar nicht vor. Und: Auch eine reine Sachfrage hat <b>immer</b> alle vier Seiten – die Frage ist nur, welche gerade im Vordergrund steht.` }
  ],

  "k2-2": [
    { t: "text", h: "Vertiefung: Was unter der Wasseroberfläche passiert – und wer in dir mitredet", levels: {
      simple: `Beim Eisberg sieht man nur die Spitze, der große Teil ist unter Wasser. So ist es auch bei Gesprächen: Man hört die Worte, aber darunter liegen Gefühle, Wünsche, alte Erfahrungen. Streit entsteht oft „unter Wasser“. Das Innere Team heißt: In dir gibt es mehrere Stimmen, z. B. „Ich will helfen“ und „Ich hab keine Zeit“. Wenn du sie alle anhörst und dich dann entscheidest, sagst du klarer, was du willst – statt halbherzig Ja zu sagen und später sauer zu sein.`,
      normal: `<b>Eisbergmodell:</b> Über der Wasserlinie liegt die <b>Sachebene</b> – Worte, Zahlen, Argumente, das bewusst Gesagte. Darunter liegt die viel größere <b>Beziehungsebene</b> – Gefühle, Bedürfnisse, Werte, Ängste, Erfahrungen, Erwartungen. Die Metapher geht auf Freuds Bild von Bewusstem und Unbewusstem zurück. Kernaussage: Was unter Wasser liegt, steuert, wie das Sichtbare verstanden wird. Wenn ein Streit über eine Kleinigkeit („Wer kauft Klopapier?“) überraschend heftig wird, kollidieren meist die unsichtbaren Teile (z. B. „Ich fühle mich nicht wertgeschätzt“). Lösungsansatz: nicht noch mehr Sachargumente, sondern das Darunter ansprechen.<br><br><b>Inneres Team</b> („Miteinander reden 3“): Zu einer Frage melden sich in uns mehrere <b>innere Teammitglieder</b> mit eigenen Anliegen – etwa die Hilfsbereite, der Ehrgeizige, die Erschöpfte. Das ist normal (innere Pluralität). Probleme entstehen, wenn (a) eine Stimme alle anderen übertönt, (b) Stimmen sich gegenseitig blockieren (Lähmung) oder (c) ungehörte Stimmen später „von hinten“ durchbrechen (z. B. als Gereiztheit). Die Aufgabe der <b>Teamleitung</b> (das bewusste Ich) ist es, alle Stimmen anzuhören, ihnen Namen zu geben, sie miteinander „verhandeln“ zu lassen und dann eine stimmige Gesamtaussage nach außen zu treffen. Ergebnis: <b>Authentizität</b> (es ist wirklich meins) und <b>Situationsgerechtigkeit</b> (es passt zur Lage).`,
      technical: `Das Eisbergmodell ist eine Heuristik, keine empirisch exakte Größe; die im Skript genannten „mindestens 80 %“ Bauchentscheidungen verdeutlichen die Dominanz affektiver Prozesse. Bezug zu Watzlawick: Der unsichtbare Teil entspricht weitgehend dem Beziehungsaspekt, der den Inhalt „bestimmt“; Bezug zu Schulz von Thun: Selbstkundgabe und Beziehungshinweis sind meist implizit, also unter der Wasserlinie. Das Innere Team (Schulz von Thun 1998) modelliert die Person als Gruppe innerer Akteure mit einer Leitung (Oberhaupt). Typische Schritte: (1) Teammitglieder identifizieren und mit prägnanter Kernbotschaft benennen („Die Pflichtbewusste: ‚Lass die Gruppe nicht hängen!‘“); (2) eine innere Ratsversammlung einberufen; (3) Konflikte zwischen Gegenspielern moderieren; (4) Integration in eine Entscheidung, in der die Anliegen mehrerer Mitglieder vertreten sind. Unterschieden werden Stammspieler (häufig präsent) und Randfiguren bzw. abgelehnte Mitglieder. Ziel ist innere Klarheit als Voraussetzung äußerer Klarheit.` } },
    { t: "example", title: "Konflikt im Fußballteam – der Eisberg", html: `Nach dem Training sagt Stürmer Jonas zum Kapitän Marko: „Warum stehe ich am Samstag schon wieder nicht in der Startelf? Ich hab 3 Tore in 4 Spielen gemacht!“<br><b>Über Wasser (Sache):</b> Aufstellung, 3 Tore, Samstag.<br><b>Unter Wasser:</b> Jonas ist gekränkt, ihm ist Anerkennung wichtig, vielleicht hat er Angst, aus dem Team gedrängt zu werden.<br><b>Vorher:</b> <i>Marko:</i> „Die Aufstellung macht der Trainer, nicht ich. Und Tore sind nicht alles, du läufst zu wenig zurück.“ – reine Sachebene, Jonas wird lauter.<br><b>Nachher:</b> <i>Marko:</i> „Klingt, als würde dich das echt ärgern – du hast ja gut getroffen. Geht's dir drum, dass das gesehen wird?“ – <i>Jonas:</i> „Ja, genau. Egal was ich mach, es zählt irgendwie nicht.“ – <i>Marko:</i> „Willst du den Trainer selbst fragen? Ich komm mit, wenn du magst.“ Erst als das Darunter angesprochen ist, sinkt die Spannung.` },
    { t: "example", title: "Gruppenarbeit an der FH – das Innere Team vor dem Ja", html: `Lena fragt Kevin: „Kannst du die Präsentation für Montag fertig machen? Ich schaff's nicht.“ In Kevin melden sich: <b>der Hilfsbereite</b> („Sie hat's grad schwer, hilf ihr!“), <b>der Erschöpfte</b> („Du hast selbst am Montag Prüfung!“), <b>der Gerechtigkeitssinn</b> („Du hast schon die Recherche gemacht“) und <b>der Harmoniebedürftige</b> („Bloß keinen Streit“).<br><b>Vorher:</b> Der Harmoniebedürftige gewinnt allein: „Ja, passt schon.“ Am Sonntagabend ist Kevin gereizt und schreibt im Chat schnippisch – der übergangene Erschöpfte bricht „von hinten“ durch.<br><b>Nachher:</b> Kevin hört kurz alle Stimmen an und formuliert eine Teamaussage: „Ich will dich nicht hängen lassen (<i>Hilfsbereiter</i>), aber ich hab Montag selbst Prüfung (<i>Erschöpfter</i>). Die Folien übernehm ich, wenn du die Sprechernotizen machst – dann ist es fair verteilt (<i>Gerechtigkeit</i>). Okay für dich?“ Der freundliche Ton wahrt die Harmonie.` },
    { t: "hint", title: "So merkst du dir den Eisberg", html: `Faustregel: <b>„Klein oben, groß unten – und unten wird entschieden.“</b> Wenn ein Gespräch über eine Kleinigkeit unverhältnismäßig heftig wird, ist das ein Signal, dass es unter Wasser um etwas Größeres geht (Wertschätzung, Fairness, Zugehörigkeit). Dann bringen weitere Sachargumente nichts.` },
    { t: "hint", title: "Mini-Übung Inneres Team (2 Minuten)", html: `Vor einer schwierigen Antwort: 1) Notiere jede innere Stimme mit einem Spitznamen und einem Satz („Die Ängstliche: ‚Was, wenn sie sauer wird?‘“). 2) Frage jede: Worum geht's dir eigentlich? 3) Formuliere eine Antwort, in der möglichst viele Anliegen vorkommen. Merke: Ziel ist nicht, Stimmen loszuwerden, sondern sie zu <b>einigen</b>.` },
    { t: "hint", title: "Verbindung zu den anderen Modellen", html: `Unter der Wasserlinie liegen genau die Dinge, die in anderen Modellen eigene Namen haben: bei Schulz von Thun <b>Selbstkundgabe</b> und <b>Beziehung</b>, bei Watzlawick der <b>Beziehungsaspekt</b>, in der GFK <b>Gefühle</b> und <b>Bedürfnisse</b>. Wer das erkennt, kann die Modelle in Analysen sauber verknüpfen.` }
  ],

  /* ================= Welt 3: Watzlawick ================= */
  "k3-1": [
    { t: "text", h: "Vertiefung: Die fünf Axiome verstehen statt auswendig lernen", levels: {
      simple: `Paul Watzlawick hat fünf Grundregeln aufgestellt, die für jedes Gespräch gelten. 1) Du kannst nicht „nicht kommunizieren“ – auch Schweigen sagt etwas. 2) Wie wir zueinander stehen, entscheidet, wie ein Satz ankommt. 3) Jeder sieht den Streit anders: „Ich reagiere ja nur auf dich!“ 4) Wir reden mit Worten und mit dem Körper – und die beiden können sich widersprechen. 5) Beziehungen sind entweder auf Augenhöhe oder ungleich (Chefin–Praktikant). Wer die Regeln kennt, versteht, warum Gespräche entgleisen.`,
      normal: `Watzlawick, Beavin und Jackson („Menschliche Kommunikation“, 1967/dt. 1969) beschreiben Kommunikation als <b>System</b>: Jedes Verhalten wirkt auf das andere zurück.<br><b>Axiom 1 – Man kann nicht nicht kommunizieren.</b> Jedes Verhalten in Anwesenheit anderer hat Mitteilungscharakter; da man sich nicht „nicht verhalten“ kann, sendet man immer. Auch wer ein Gespräch verweigert, teilt mit: „Ich will nicht reden.“<br><b>Axiom 2 – Inhalts- und Beziehungsaspekt.</b> Jede Mitteilung enthält eine Information (Inhalt) und eine Anweisung, wie sie zu verstehen ist (Beziehung). Die Beziehung ist die „Brille“, durch die der Inhalt gelesen wird. Ist die Beziehung gestört, wird sachlich nichts mehr gelöst – dann hilft nur <b>Metakommunikation</b> (über die Beziehung reden).<br><b>Axiom 3 – Interpunktion.</b> Kommunikation ist ein Kreislauf ohne Anfang; jede Seite setzt den „Startpunkt“ dort, wo sie sich als Reagierende sieht. Streit über „Wer hat angefangen?“ ist darum unlösbar.<br><b>Axiom 4 – digital und analog.</b> Digital = Worte mit fester Bedeutung (gut für Inhalte, logisch präzise). Analog = Tonfall, Mimik, Gestik, Nähe (gut für Beziehung, aber mehrdeutig).<br><b>Axiom 5 – symmetrisch oder komplementär.</b> Symmetrisch = Gleichheit, Spiegeln des Verhaltens (Gefahr: Eskalation, „wer ist besser“). Komplementär = Ergänzung, Unterschiedlichkeit (Gefahr: Erstarrung, ein Teil wird klein gehalten). Gesund ist ein flexibler Wechsel.`,
      technical: `Die Axiome entstammen der Palo-Alto-Gruppe (Mental Research Institute) und der systemischen Familientherapie. Axiom 1 gilt für Situationen, in denen sich Personen gegenseitig wahrnehmen; es folgt aus der Prämisse „Verhalten hat kein Gegenteil“. Axiom 2: Der Beziehungsaspekt ist eine Metakommunikation über den Inhalt; Störungen äußern sich, wenn Beziehungskonflikte auf der Inhaltsebene ausgetragen werden (Scheinsachstreit). Axiom 3: Die „Interpunktion von Ereignisfolgen“ beschreibt die subjektive Gliederung zirkulärer Interaktionen in Ursache und Wirkung; Lösungsansatz ist zirkuläres statt lineares Denken. Axiom 4: Digitale Kommunikation verfügt über komplexe logische Syntax, aber eine für Beziehungen unzulängliche Semantik; analoge Kommunikation hat das semantische Potenzial für Beziehungen, aber keine eindeutige Syntax (z. B. keine Verneinung). Widersprechen sich beide Ebenen, entsteht eine Doppelbotschaft; ist die Person zusätzlich abhängig und kann die Situation nicht verlassen, spricht man von <b>Doppelbindung (double bind)</b>. Axiom 5: Symmetrische Interaktion beruht auf Gleichheit, komplementäre auf sich ergänzender Unterschiedlichkeit (superior/inferior bzw. „one-up/one-down“); pathologisch sind symmetrische Eskalation und starre Komplementarität.` } },
    { t: "example", title: "WG-Abwasch – Axiom 3 im Kreis", html: `<b>Vorher:</b><br><i>Sophie:</i> „Ich sag nur deshalb ständig was, weil du nie abwäschst!“<br><i>Paul:</i> „Ich wasch nur deshalb nicht ab, weil du mich ständig kontrollierst – da hab ich null Lust!“<br>Beide „interpunktieren“ anders: Sophie sieht <i>Paul nicht abwaschen → ich nörgle</i>, Paul sieht <i>Sophie nörgelt → ich ziehe mich zurück</i>. Es ist ein Kreis: Nörgeln → Rückzug → mehr Nörgeln → mehr Rückzug.<br><br><b>Nachher</b> (Kreislauf benennen statt Schuld suchen):<br><i>Sophie:</i> „Ich glaub, wir drehen uns im Kreis: Je mehr ich sag, desto weniger Lust hast du, und je weniger du machst, desto mehr sag ich. Wie kommen wir da raus?“<br><i>Paul:</i> „Stimmt. Wenn wir einen festen Plan machen, musst du nix mehr sagen und ich weiß, wann ich dran bin.“<br>Metakommunikation über das Muster unterbricht die Eskalation.` },
    { t: "example", title: "Fußballteam & Mutter – Axiome 4 und 5", html: `<b>Axiom 4 (Fußball):</b> Trainer Huber sagt nach der 0:3-Niederlage „Gut gekämpft, Burschen“ – mit hängenden Schultern und ohne Blickkontakt. Digital: Lob. Analog: Enttäuschung. Die Spieler glauben dem Analogen – Doppelbotschaft. <b>Nachher:</b> „Ich bin enttäuscht vom Ergebnis, und gleichzeitig hab ich gesehen, dass ihr bis zur 90. gelaufen seid.“ – Worte und Körper passen zusammen (kongruent).<br><br><b>Axiom 5 (Mutter):</b> Früher war die Beziehung komplementär (Mutter entscheidet, Kind folgt). Jetzt ist Kevin 21 und will Augenhöhe. <i>Mutter:</i> „Zieh dir eine Jacke an.“ – <i>Kevin:</i> „Ich bin kein Kind mehr!“ – <i>Mutter:</i> „Solange ich …“ → beide ringen um die Definition der Beziehung (symmetrische Eskalation droht). <b>Nachher:</b> <i>Kevin:</i> „Ich merk, du machst dir Sorgen. Ich entscheide das aber gern selbst – ist das okay für dich?“ Er spricht die Beziehungsdefinition offen an, statt über die Jacke zu streiten.` },
    { t: "hint", title: "Eselsbrücke für alle fünf", html: `<b>„Nie Bei Interpunktion Digital Streiten“</b>: 1 <b>N</b>icht nicht kommunizieren · 2 <b>B</b>eziehung bestimmt Inhalt · 3 <b>I</b>nterpunktion (Ursache-Wirkung) · 4 <b>D</b>igital/analog · 5 <b>S</b>ymmetrisch/komplementär.` },
    { t: "hint", title: "Prüfungsfalle: digital ≠ „elektronisch“", html: `„Digital“ hat bei Watzlawick nichts mit Computern oder WhatsApp zu tun. Gemeint sind <b>Zeichen mit vereinbarter Bedeutung</b> – vor allem Wörter. Analog = alles, was der Sache „ähnelt“ und nicht eindeutig codiert ist: Tonfall, Mimik, Gestik, Pausen. Eine Sprachnachricht enthält also beides!` },
    { t: "hint", title: "Symmetrisch oder komplementär? So entscheidest du", html: `Frag: <b>Verhalten sich beide gleich (spiegeln sich) oder ergänzen sie sich?</b> Zwei Spieler, die sich gegenseitig anschreien und jeder will das letzte Wort = symmetrisch. Trainer gibt Anweisung, Spieler setzt um = komplementär. Merke: Keine der beiden Formen ist „schlecht“ – gestört wird es erst durch <b>Eskalation</b> (symmetrisch) oder <b>Erstarrung</b> (komplementär).` }
  ],

  /* ================= Welt 4: GFK ================= */
  "k4-1": [
    { t: "text", h: "Vertiefung: Die vier Ohren der GFK – Wolf und Giraffe nach innen und außen", levels: {
      simple: `Die Gewaltfreie Kommunikation (GFK) von Marshall Rosenberg sagt: Hinter allem, was Menschen tun – auch hinter Gemeinheiten –, steckt ein Bedürfnis, das sie erfüllen wollen. Der Wolf sucht Schuldige („Du bist faul!“ oder „Ich bin so blöd!“). Die Giraffe fragt: Was fühle ich, was brauche ich – und was fühlt und braucht der andere? „Gewaltfrei“ heißt nicht „immer nett“, sondern: ehrlich sagen, was los ist, ohne den anderen anzugreifen.`,
      normal: `Marshall B. Rosenberg (1934–2015), Schüler von Carl Rogers, entwickelte die GFK ab den 1960er-Jahren, u. a. in Schulen und Konfliktgebieten; das Buch „Nonviolent Communication“ erschien 1999. „Gewaltfrei“ bezieht sich auf Gandhis Begriff der Gewaltlosigkeit: Gemeint ist <b>sprachliche</b> Gewalt – Urteile, Schuldzuweisungen, Drohungen –, die Menschen in Verteidigung oder Gegenangriff treibt.<br><br>Zentral sind die <b>vier Ohren der GFK</b> (nicht verwechseln mit Schulz von Thun!). Wenn uns jemand etwas Unangenehmes sagt, können wir so reagieren:<br>• <b>Wolfsohren nach außen</b>: Ich gebe dem anderen die Schuld („Was fällt dir ein?“) → Angriff.<br>• <b>Wolfsohren nach innen</b>: Ich gebe mir die Schuld („Ich bin echt unfähig“) → Scham, Rückzug.<br>• <b>Giraffenohren nach innen</b>: Ich spüre mein Gefühl und Bedürfnis („Ich bin verletzt, weil mir Wertschätzung wichtig ist“) → Selbstempathie.<br>• <b>Giraffenohren nach außen</b>: Ich höre das Gefühl und Bedürfnis des anderen („Bist du frustriert, weil dir Verlässlichkeit wichtig ist?“) → Empathie.<br><br>Die zwei Säulen <b>Aufrichtigkeit</b> (ich zeige mich ehrlich) und <b>Empathie</b> (ich höre den anderen) entsprechen genau den beiden Giraffenrichtungen. Die Grundannahme „Jedes Verhalten ist ein Versuch, ein Bedürfnis zu erfüllen“ heißt nicht, dass jedes Verhalten okay ist – aber dass man über das Bedürfnis einen Zugang findet, statt über die Schuldfrage zu streiten.`,
      technical: `Die GFK basiert auf der humanistischen Psychologie (Rogers: Empathie, Akzeptanz, Kongruenz). Rosenberg unterscheidet „lebensentfremdende“ Kommunikation (statische Urteile über richtig/falsch, Verdienst und Strafe) von „lebensbereichernder“ Kommunikation, die auf erfüllte bzw. unerfüllte Bedürfnisse fokussiert. Das Modell hat zwei Richtungen (sich ehrlich ausdrücken / empathisch empfangen) und vier Komponenten (Beobachtung, Gefühl, Bedürfnis, Bitte), die in beiden Richtungen angewandt werden. Die Wolf-Giraffe-Metapher (in manchen Quellen „Schakal“ statt Wolf) ist ein didaktisches Bild; „Wolf“ ist keine Person, sondern eine Sprechweise, die jeder nutzt. Die Annahme 2 („Gewalt ist ein tragischer Ausdruck unerfüllter Bedürfnisse“) ist erklärend, nicht rechtfertigend: Verantwortung für das Handeln bleibt bestehen. Wichtig: Die GFK ist primär eine <b>Haltung</b> – die vier Schritte sind ein Werkzeug; mechanisch angewandt ohne echtes Interesse wirkt sie manipulativ („Giraffensprache mit Wolfsherz“).` } },
    { t: "example", title: "Gruppenarbeit an der FH – alle vier Ohren", html: `Teamkollegin Mia schreibt um 23 Uhr: „Dein Teil ist echt schwach, so können wir das nicht abgeben.“ Vier mögliche Reaktionen von Kevin:<br>🐺→ <b>Wolf nach außen:</b> „Sagt die, die ihren Teil drei Tage zu spät geschickt hat.“<br>🐺← <b>Wolf nach innen:</b> „Ich krieg echt nix hin, ich bin für Gruppenarbeiten ungeeignet.“<br>🦒← <b>Giraffe nach innen</b> (Selbstempathie, still für sich): „Ich bin gekränkt und auch verunsichert – mir ist wichtig, dass meine Arbeit gesehen wird.“<br>🦒→ <b>Giraffe nach außen:</b> „Du klingst ziemlich besorgt wegen der Abgabe – ist dir wichtig, dass wir etwas abgeben, hinter dem wir alle stehen können? Welche Stellen meinst du konkret?“<br>Nur die beiden Giraffen-Varianten halten das Gespräch offen. Oft braucht es <b>zuerst Selbstempathie</b> (innen), damit man danach empathisch nach außen hören kann.` },
    { t: "example", title: "Gespräch mit der Mutter – Wolf vs. Giraffe", html: `<b>Vorher (Wolf):</b><br><i>Mutter:</i> „Du meldest dich ja nur, wenn du was brauchst.“<br><i>Kevin:</i> „Das stimmt doch gar nicht! Du übertreibst immer.“<br><i>Mutter:</i> „Siehst du, jetzt wirst du wieder frech.“<br><br><b>Nachher (Giraffe nach außen):</b><br><i>Mutter:</i> „Du meldest dich ja nur, wenn du was brauchst.“<br><i>Kevin:</i> „Bist du traurig, weil du dir mehr Kontakt mit mir wünschst?“<br><i>Mutter:</i> „… Ja. Seit du in Graz wohnst, hör ich so wenig von dir.“<br><i>Kevin:</i> „Das versteh ich. Wie wär's, wenn ich dich sonntags kurz anruf, auch wenn's nix Besonderes gibt?“<br>Kevin hört hinter dem Vorwurf (Wolf-Sprache der Mutter) Gefühl <b>traurig</b> und Bedürfnis <b>Verbundenheit</b> – und reagiert darauf statt auf den Vorwurf.` },
    { t: "hint", title: "Prüfungsfalle: zwei Mal „vier Ohren“", html: `Schulz von Thun: vier Ohren = <b>Sache, Selbstkundgabe, Beziehung, Appell</b>. GFK: vier Ohren = <b>Wolf außen, Wolf innen, Giraffe innen, Giraffe außen</b>. Bei einer Frage zuerst klären, welches Modell gemeint ist – der Name des Autors (Schulz von Thun vs. Rosenberg) verrät es.` },
    { t: "hint", title: "Warum Giraffe? So merkst du's dir", html: `<b>Großes Herz</b> (die Giraffe hat das größte Herz aller Landtiere → „Sprache des Herzens“), <b>langer Hals</b> (Überblick, weiter sehen als der momentane Ärger), <b>große Ohren</b> (gut zuhören). Der Wolf dagegen „knurrt“: Er beißt mit Urteilen, Schuld und Forderungen.` },
    { t: "hint", title: "Häufiges Missverständnis", html: `„Gewaltfrei“ heißt <b>nicht</b>: immer zustimmen, keine Grenzen setzen, nie Nein sagen. Ein klares „Nein, das mache ich nicht, weil mir meine Erholung wichtig ist“ ist voll GFK-tauglich. Gewaltvoll wäre: „Nein, weil du immer alles auf andere abschiebst.“` }
  ],

  "k4-2": [
    { t: "text", h: "Vertiefung: Warum Urteile, Vergleiche & Co. Kooperation killen", levels: {
      simple: `Manche Sätze machen ein Gespräch sofort kaputt, auch wenn sie „nur ehrlich“ gemeint sind: „Du bist faul“ (Urteil), „Schau dir Lisa an, die schafft das auch“ (Vergleich), „Ich muss das so machen“ (ich schiebe die Verantwortung ab), „Mach das, sonst …“ (Drohung). Der andere hört dann nur noch den Angriff und verteidigt sich. Auch Lob kann blockieren, wenn es nur dazu dient, jemanden zu steuern.`,
      normal: `Rosenberg nennt diese Muster <b>lebensentfremdende Kommunikation</b>, weil sie den Blick von dem, was Menschen fühlen und brauchen, auf Kategorien wie richtig/falsch lenken. Die Wirkung kann man sich als <b>Kooperationsbarometer</b> vorstellen: Jede Blockade senkt die Bereitschaft des Gegenübers, freiwillig mitzumachen.<br>• <b>Moralische Urteile</b>: „Du bist egoistisch/faul/unfähig.“ Auch Schubladen („typisch Informatiker“) und Diagnosen („Du hast ein Kontrollproblem“). Statt meines Bedürfnisses benenne ich einen Fehler des anderen.<br>• <b>Vergleiche</b>: „Warum kannst du nicht wie dein Bruder …?“ – erzeugen Scham, nicht Motivation.<br>• <b>Verantwortung leugnen</b>: „Ich muss“, „man tut das“, „die Regeln sagen“, „du hast mich wütend gemacht“. Rosenbergs Gegenvorschlag: „Ich <i>entscheide mich</i>, …, weil ich … möchte.“<br>• <b>Forderungen</b>: Befehle, Drohungen, Predigten – lassen kein Nein zu. Wer Druck macht, bekommt bestenfalls Gehorsam oder Widerstand, aber keine freiwillige Kooperation.<br>• <b>Strafe und „Verdienst“-Denken</b>: „Das hast du dir verdient.“ Strafe ändert Verhalten oft nur, solange jemand zuschaut.<br>• <b>Lob als Steuerung</b>: „Super, dass du endlich mal abgewaschen hast!“ – bewertet von oben herab und will Verhalten lenken.<br>Gegenmittel ist immer derselbe Weg: von der Bewertung zurück zur <b>Beobachtung</b>, zum eigenen <b>Gefühl</b> und <b>Bedürfnis</b>.`,
      technical: `Gemeinsamer Nenner aller Blockaden ist, dass statische Bewertungen über Personen (Sein-Aussagen) an die Stelle von Aussagen über Handlungen und deren Wirkung auf Bedürfnisse treten. Rosenberg unterscheidet dabei moralische Urteile (Fehlerzuschreibung an die Person) von <b>Werturteilen</b> (Aussagen über das, was mir wichtig ist) – Letztere sind legitim („Mir ist Ehrlichkeit wichtig“ statt „Lügen ist schlecht“). Das Leugnen von Verantwortung zeigt sich sprachlich in Modalverben (müssen, sollen, dürfen nicht), Passivkonstruktionen und Verweisen auf Autorität, Gruppendruck, Rollen oder Impulse. Forderungen unterscheiden sich von Bitten nicht in der Formulierung, sondern in der Konsequenz bei Ablehnung (Strafe, Schuld). Der Gegenentwurf zum steuernden Lob ist <b>Wertschätzung in drei Teilen</b>: (1) welche Handlung, (2) welches meiner Gefühle, (3) welches Bedürfnis dadurch erfüllt wurde – ohne Absicht, künftiges Verhalten zu kontrollieren.` } },
    { t: "example", title: "Konflikt im Fußballteam – fünf Blockaden in einer Kabinenpredigt", html: `<b>Vorher</b> – Kapitän Marko nach dem Training:<br>„Ihr seid echt faule Säcke (<i>Urteil</i>). Die U18 läuft mehr als ihr (<i>Vergleich</i>). Ich muss das dem Trainer melden, so sind halt die Regeln (<i>Verantwortung leugnen</i>). Wer am Donnerstag wieder zu spät kommt, sitzt am Samstag draußen (<i>Drohung/Strafe</i>). Nur Lukas hat's kapiert, super Lukas, so muss das sein (<i>Lob als Steuerung</i>).“<br>Ergebnis: Augenrollen, Lukas ist es peinlich, zwei Spieler kommen absichtlich später.<br><br><b>Nachher</b>:<br>„Beim Training heute waren nach 20 Minuten nur noch fünf von uns beim Laufen dabei (<i>Beobachtung</i>). Ich bin frustriert und ein bisschen besorgt (<i>Gefühl</i>), weil mir wichtig ist, dass wir am Samstag fit sind und gemeinsam was erreichen (<i>Bedürfnis</i>). Ich hab mich entschieden, das anzusprechen, weil ich Lust auf den Aufstieg hab (<i>Verantwortung übernehmen</i>). Was hält euch gerade ab – und was bräuchtet ihr, damit Donnerstag besser läuft?“ (<i>Bitte</i>).` },
    { t: "example", title: "WG-Abwasch – Lob vs. Wertschätzung", html: `Paul hat zum ersten Mal ohne Erinnerung die ganze Küche geputzt.<br><b>Steuerndes Lob:</b> <i>Sophie:</i> „Na geht doch! Siehst du, wenn du willst, kannst du's ja.“ – klingt wie eine Note von oben und erinnert an die „schlechten“ Male. Paul: „Ja, ja, schon gut.“<br><b>Wertschätzung (Giraffe):</b> <i>Sophie:</i> „Ich hab gesehen, dass du die Küche komplett geputzt hast, sogar den Herd (<i>Handlung</i>). Ich freu mich richtig und bin erleichtert (<i>Gefühl</i>), weil ich nach dem langen Tag einfach entspannt kochen wollte (<i>Bedürfnis</i>). Danke!“ – <i>Paul:</i> „Echt? Cool, das freut mich.“<br>Der Unterschied: Wertschätzung beschreibt, was die Handlung <b>bei mir</b> bewirkt hat, statt den anderen zu benoten.` },
    { t: "hint", title: "Die 6 Blockaden merken: „UVV-FSL“", html: `<b>U</b>rteil · <b>V</b>ergleich · <b>V</b>erantwortung leugnen · <b>F</b>orderung · <b>S</b>trafe · <b>L</b>ob (steuernd). Merksatz: „<b>U</b>nser <b>V</b>erein <b>V</b>erliert, <b>F</b>alls <b>S</b>türmer <b>L</b>ahmen.“` },
    { t: "hint", title: "Der „müssen“-Test", html: `Ersetze in deinem Satz „ich muss“ durch <b>„ich entscheide mich, …, weil ich … will“</b>. „Ich muss heute lernen“ → „Ich entscheide mich, heute zu lernen, weil ich die Prüfung schaffen will.“ Wenn der Satz danach ehrlicher klingt, war „müssen“ eine Verantwortungs-Verschleierung.` },
    { t: "hint", title: "Typische Falle beim Zuordnen", html: `„Das Problem mit dir ist, dass du unfähig bist“ ist <b>Urteil (Diagnose)</b>, nicht Vergleich – es wird niemand anderer genannt. „Für diesen Verstoß muss ich dich verweisen“ ist <b>Verantwortung leugnen</b>, keine Drohung – die Person versteckt ihre eigene Entscheidung hinter Regeln. Achte auf das Schlüsselwort: andere Person genannt → Vergleich; „muss/man/Regeln“ → Verantwortung; „sonst/wenn nicht“ → Drohung.` }
  ],

  /* ================= Welt 5: Die 4 Schritte ================= */
  "k5-1": [
    { t: "text", h: "Vertiefung: Wie du eine Bewertung in eine Beobachtung übersetzt", levels: {
      simple: `Eine Beobachtung beschreibt nur, was passiert ist – wie eine Kamera oder ein Mikrofon. Eine Bewertung sagt, was du darüber denkst. „Du bist chaotisch“ ist eine Bewertung, „Auf dem Sofa liegen drei T-Shirts“ ist eine Beobachtung. Bei einer Beobachtung kann der andere nicht „Stimmt gar nicht!“ sagen – darum fängt ein gutes Gespräch genau damit an. Bewerten ist nicht verboten; man soll es nur nicht mit dem Beobachten vermischen.`,
      normal: `Rosenberg zitiert dazu den Philosophen Krishnamurti: Beobachten, ohne zu bewerten, sei die höchste Form menschlicher Intelligenz. Der Grund ist praktisch: Sobald eine Aussage eine Bewertung enthält, hört das Gegenüber Kritik und beginnt, sich zu verteidigen – das eigentliche Anliegen geht unter.<br><br><b>Übersetzen in 4 Schritten:</b><br>1. <b>Warnwörter suchen</b>: immer, nie, ständig, schon wieder, total, zu (viel/spät/laut), Eigenschaftswörter über Personen (faul, egoistisch, unzuverlässig) und unterstellte Absichten (absichtlich, um mich zu ärgern).<br>2. <b>Fragen: Was genau hat die Kamera aufgenommen?</b> Wer hat was getan oder gesagt?<br>3. <b>Zeit und Häufigkeit konkretisieren</b>: „gestern um 18 Uhr“, „dreimal in dieser Woche“ statt „immer“.<br>4. <b>Wörtlich zitieren</b>, wenn es um Gesagtes geht: „Du hast gesagt: ‚Das bringt eh nix‘“ statt „Du warst negativ“.<br><br>Ein feiner Punkt: Auch Wörter wie „zu spät“ oder „unordentlich“ sind schon Bewertungen, weil sie einen Maßstab enthalten. Die Kamera sieht keine Unordnung, sie sieht Gegenstände an Orten. Eine gute Beobachtung ist außerdem <b>spezifisch für eine Situation</b> – sie spricht über ein Ereignis, nicht über den Charakter.`,
      technical: `Rosenberg unterscheidet <b>statische Sprache</b> (Zuschreibungen von Eigenschaften: „X ist …“) von <b>prozesshafter Sprache</b> (Beschreibung von Handlungen in Raum und Zeit). Vermischungen treten typischerweise auf als: (1) Verwendung des Verbs „sein“ ohne Hinweis auf die eigene Bewertung („Du bist zu großzügig“); (2) Verben mit bewertender Konnotation („Er schiebt alles auf“); (3) Folgerungen über Gedanken, Gefühle oder Absichten anderer („Sie wird ihre Arbeit nicht schaffen“); (4) Verwechslung von Vorhersage und Gewissheit; (5) unspezifische Bezüge („Ausländer“, „die Jungen“); (6) Fähigkeitszuschreibungen ohne Beleg („Er ist ein schlechter Spieler“); (7) Adverbien und Adjektive ohne Kennzeichnung als Bewertung („Sie ist hässlich“) sowie Verallgemeinerungen (immer, nie, ständig). Bewertungen dürfen ausgesprochen werden, sollten aber als eigene Bewertung gekennzeichnet und an Beobachtungen gebunden sein („In den letzten drei Spielen hat er kein Tor geschossen“ statt „Er ist ein schlechter Stürmer“).` } },
    { t: "example", title: "WG-Abwasch – vom Vorwurf zur Kamera", html: `<b>Vorher:</b><br><i>Sophie:</i> „Du lässt <u>immer</u> alles stehen, die Küche ist <u>total</u> eklig, und das machst du <u>absichtlich</u>, damit ich's wegräum.“<br><i>Paul:</i> „Immer? Letzten Dienstag hab ich alles abgewaschen! Und eklig ist es nur für dich.“<br>Paul widerspricht genau den Bewertungswörtern (immer, total eklig, absichtlich) – über das Geschirr wird gar nicht mehr geredet.<br><br><b>Nachher:</b><br><i>Sophie:</i> „In der Spüle stehen seit Sonntag zwei Teller und die Pfanne mit den Nudelresten.“<br><i>Paul:</i> „Ja, das stimmt, die sind von mir.“<br>Paul kann nicht widersprechen – es entsteht eine <b>gemeinsame Wirklichkeit</b>, und das Gespräch kann bei der Lösung weitergehen. Zuordnung: „seit Sonntag“ = konkreter Zeitpunkt, „zwei Teller und die Pfanne“ = konkrete Menge statt „alles“.` },
    { t: "example", title: "Gruppenarbeit an der FH – Bewertungen erkennen", html: `<table class="dt"><tr><th>Bewertung</th><th>Warum?</th><th>Beobachtung</th></tr><tr><td>„Tom macht nie was.“</td><td>Verallgemeinerung „nie“</td><td>„Tom hat bei den letzten zwei Treffen keine Folien mitgebracht.“</td></tr><tr><td>„Lena ist arrogant.“</td><td>Eigenschaft der Person</td><td>„Lena hat zu meinem Vorschlag gesagt: ‚Das ist doch Kindergarten.‘“</td></tr><tr><td>„Das Meeting war viel zu lang.“</td><td>Maßstab „zu“</td><td>„Das Meeting dauerte 95 Minuten, geplant waren 30.“</td></tr><tr><td>„Mia ignoriert den Chat.“</td><td>unterstellte Absicht</td><td>„Mia hat auf die letzten drei Nachrichten im Gruppenchat nicht geantwortet.“</td></tr></table>Bei Mia kann es viele Gründe geben (Handy kaputt, krank, Benachrichtigung aus) – „ignoriert“ legt schon eine Absicht fest.` },
    { t: "hint", title: "Der Kamera-Test in einem Satz", html: `Frag dich: <b>Könnte eine Kamera mit Mikrofon genau das aufzeichnen – ohne dass jemand sie interpretiert?</b> „Er war wütend“ kann keine Kamera filmen (das ist eine Deutung); „Er hat mit der Faust auf den Tisch geschlagen und ‚Mir reicht's‘ gerufen“ schon.` },
    { t: "hint", title: "Warnwörter-Liste zum Merken", html: `<b>Zeit-Verallgemeinerungen:</b> immer, nie, ständig, schon wieder, jedes Mal · <b>Maßstäbe:</b> zu (viel, spät, laut), total, völlig · <b>Charakter:</b> faul, egoistisch, unzuverlässig, arrogant · <b>Absichten:</b> absichtlich, ignoriert, provoziert, will mich ärgern. Ein einziges Warnwort macht aus einer Beobachtung eine Bewertung.` },
    { t: "hint", title: "Prüfungsfalle: Gefühl in der Beobachtung", html: `„Gestern warst du traurig“ ist <b>keine</b> Beobachtung – Traurigkeit sieht man nicht, man deutet sie. Beobachtung wäre: „Gestern hast du beim Abendessen nichts gesagt und bist nach zehn Minuten aufgestanden.“` }
  ],

  "k5-2": [
    { t: "text", h: "Vertiefung: Auslöser vs. Ursache – woher Gefühle wirklich kommen", levels: {
      simple: `Echte Gefühle beschreiben, was in dir passiert: traurig, wütend, froh, erleichtert, ängstlich. Pseudogefühle beschreiben eigentlich, was ein anderer (angeblich) mit dir macht: „ich fühle mich ausgenutzt, ignoriert, angegriffen“. Das klingt nach Gefühl, ist aber ein Vorwurf. Wichtig: Was andere tun, löst dein Gefühl aus – aber ob du dich ärgerst oder nicht, hängt davon ab, was dir gerade wichtig ist.`,
      normal: `Rosenbergs Kernsatz: <b>Was andere tun, kann der Auslöser (Stimulus) unserer Gefühle sein, aber nie die Ursache.</b> Die Ursache ist unser eigenes erfülltes oder unerfülltes Bedürfnis. Beweis aus dem Alltag: Wenn der Freund 30 Minuten zu spät kommt, ist man einmal ärgerlich (Bedürfnis: Verlässlichkeit), ein anderes Mal erleichtert (Bedürfnis: Zeit, noch fertig zu lernen). Gleicher Auslöser – verschiedene Gefühle, weil verschiedene Bedürfnisse aktiv sind.<br><br>Daraus folgt der Unterschied:<br>• <b>Echtes Gefühl</b>: beschreibt meinen inneren Zustand, hängt am eigenen Bedürfnis → „Ich bin enttäuscht.“<br>• <b>Pseudogefühl</b>: enthält eine Interpretation dessen, was der andere tut → „Ich fühle mich hintergangen“ (= du hast mich hintergangen).<br><br>Pseudogefühle sind nicht „falsch“, sie sind nur <b>verpackte Urteile</b> – und lösen deshalb Verteidigung aus. Übersetzungsweg: Pseudogefühl → „Wie geht es mir, wenn ich glaube, dass ich übergangen werde?“ → z. B. enttäuscht, traurig, ärgerlich.<br><br>Zum Gefühlswortschatz: Es hilft, zwei Listen zu kennen. <b>Bei erfüllten Bedürfnissen</b>: froh, erleichtert, dankbar, entspannt, zuversichtlich, neugierig, berührt. <b>Bei unerfüllten Bedürfnissen</b>: traurig, ärgerlich, frustriert, ängstlich, besorgt, erschöpft, verwirrt, einsam, ungeduldig. Je genauer das Wort, desto besser versteht dich das Gegenüber („genervt“ ist etwas anderes als „erschöpft“).`,
      technical: `In der GFK fungieren Gefühle als Indikatoren des Bedürfniszustands („Armaturenbrett“). Pseudogefühle lassen sich linguistisch identifizieren: (1) „fühlen“ + Konjunktion <i>dass, wie, als ob</i> → Gedanke; (2) „fühlen“ + Pronomen/Name („Ich habe das Gefühl, er …“) → Urteil über Dritte; (3) „fühlen“ + Partizip, das eine Handlung anderer impliziert (ausgenutzt, betrogen, missverstanden, manipuliert, abgelehnt, bedrängt, provoziert, übergangen, unterschätzt) → Interpretation; (4) „fühlen“ + Selbstbewertung („unfähig“, „unwichtig“) → Urteil über sich selbst. Die Formel „Ich fühle …, weil ich … brauche“ verankert die Verantwortung für das Gefühl beim Sprecher; „Ich fühle …, weil du …“ verlagert sie auf den anderen und ist zu vermeiden. Rosenberg grenzt das von Gleichgültigkeit ab: Übernahme von Verantwortung für eigene Gefühle bedeutet nicht, dass die Handlung des anderen unwichtig wäre – sie ist der Stimulus und darf benannt werden.` } },
    { t: "example", title: "Konflikt im Fußballteam – ein Auslöser, zwei Gefühle", html: `Der Trainer wechselt Stürmer Jonas in der 60. Minute aus.<br><b>Variante A:</b> Jonas will sich beweisen (Bedürfnis: Anerkennung) → er ist <b>enttäuscht und ärgerlich</b>.<br><b>Variante B:</b> Jonas hat seit der 50. Minute Wadenkrämpfe (Bedürfnis: Gesundheit/Schonung) → er ist <b>erleichtert</b>.<br>Gleicher Auslöser, andere Gefühle – die <b>Ursache</b> ist das Bedürfnis, nicht der Trainer.<br><br><b>Vorher</b> (Variante A, Pseudogefühl):<br><i>Jonas:</i> „Ich fühl mich von Ihnen total verarscht und abgestempelt.“<br><i>Trainer:</i> „Ich stempel niemanden ab. Ich treff die Entscheidungen, Punkt.“<br><b>Nachher</b> (echtes Gefühl + Bedürfnis):<br><i>Jonas:</i> „Ich war echt enttäuscht über die Auswechslung, weil ich gern zeigen wollte, dass ich 90 Minuten durchhalte.“<br><i>Trainer:</i> „Verstehe. Es ging mir um deine gelbe Karte, nicht um deine Kondition. Nächste Woche bekommst du die Chance.“` },
    { t: "example", title: "Gespräch mit der Mutter – Pseudogefühle übersetzen", html: `Kevin will seiner Mutter sagen, was ihn stört, wenn sie ihm ungefragt Ratschläge zum Studium gibt.<br><b>Vorher:</b> „Ich fühl mich von dir total bevormundet und nicht ernst genommen.“ (zwei Pseudogefühle: <i>bevormundet</i> und <i>nicht ernst genommen</i> beschreiben, was sie angeblich tut) – <i>Mutter:</i> „Ich bevormund dich doch nicht, ich mein's nur gut!“<br><b>Nachher:</b> „Wenn du mir sagst, welche Fächer ich wählen soll, bin ich <b>angespannt</b> und auch ein bisschen <b>unsicher</b>, weil mir wichtig ist, das selbst zu entscheiden.“ – <i>Mutter:</i> „Oh, so hab ich das nicht gesehen. Ich wollte dir nur helfen.“<br>Zuordnung: <i>angespannt, unsicher</i> = echte Gefühle; <i>selbst entscheiden</i> = Bedürfnis Autonomie.` },
    { t: "hint", title: "Der Ersetz-Test", html: `Ersetze „Ich fühle mich“ durch <b>„Ich bin“</b>. Klingt es noch richtig? „Ich bin traurig“ ✔ – echtes Gefühl. „Ich bin übergangen“ ✘ – da steckt eine Handlung eines anderen drin, also Pseudogefühl. Zweiter Test: Braucht das Wort einen Täter? (<i>ausgenutzt</i> – von wem?) → Pseudogefühl.` },
    { t: "hint", title: "Typische Prüfungsfalle", html: `„Ich fühle mich <b>wie</b> …“, „Ich habe das Gefühl, <b>dass</b> …“, „Ich fühle mich <b>als ob</b> …“ sind immer Gedanken, auch wenn danach ein harmloses Wort kommt. Und Vorsicht bei Selbstbewertungen: „Ich fühle mich unfähig/dumm/unwichtig“ ist ein Urteil über sich selbst, kein Gefühl.` },
    { t: "hint", title: "Kurze Übersetzungstabelle", html: `ignoriert → einsam, traurig · ausgenutzt → ärgerlich, erschöpft · unter Druck gesetzt → angespannt, gestresst · kritisiert → verletzt, unsicher · missverstanden → frustriert, verwirrt · bevormundet → gereizt, eingeengt. Danach fragen: <b>Welches Bedürfnis ist unerfüllt?</b>` }
  ],

  "k5-3": [
    { t: "text", h: "Vertiefung: Bedürfnis oder Strategie – der wichtigste Unterschied der GFK", levels: {
      simple: `Ein Bedürfnis ist etwas, das jeder Mensch auf der Welt hat: Ruhe, Sicherheit, Anerkennung, Gemeinschaft, Selbstbestimmung. Eine Strategie ist der konkrete Weg dorthin: „Ich will, dass DU um 22 Uhr leise bist.“ Streit entsteht fast immer über Strategien („Musik aus!“ vs. „Ich will Musik!“). Über Bedürfnisse kann man sich viel leichter einigen, weil jeder sie kennt. Und: Für ein Bedürfnis gibt es viele Strategien – man muss nur eine finden, die für beide passt.`,
      normal: `<b>Bedürfnisse</b> sind universell, abstrakt und frei von Person, Ort, Zeit und Handlung. <b>Strategien</b> sind konkret: Sie nennen, <i>wer was wann wo</i> tun soll. Merke: Sobald eine Person, ein Ort, eine Uhrzeit oder eine Handlung vorkommt, ist es eine Strategie.<br><br>Beispiel: „Ich brauche, dass du mich jeden Abend anrufst“ ist eine Strategie (Person, Zeit, Handlung). Das Bedürfnis dahinter: Verbundenheit, Sicherheit, Nähe. Für Verbundenheit gibt es viele Wege – Anruf, Sprachnachricht, gemeinsames Frühstück am Wochenende.<br><br><b>Warum das so wichtig ist:</b> Auf der Strategie-Ebene sind Konflikte oft Nullsummenspiele (entweder Musik oder Ruhe). Auf der Bedürfnis-Ebene erkennen beide, dass ihre Anliegen legitim sind, und es öffnet sich ein Raum für neue Strategien (Kopfhörer, Musik bis 22 Uhr, Ohrstöpsel). Das ist dieselbe Logik wie beim Harvard-Konzept („Interessen statt Positionen“).<br><br><b>Rosenbergs Bedürfnisgruppen</b> (zur Orientierung): Autonomie (Wahlfreiheit, Selbstbestimmung) · Feiern (Erfolge und Verluste würdigen) · Integrität (Authentizität, Sinn, Selbstwert) · Interdependenz/Verbundenheit (Akzeptanz, Nähe, Unterstützung, Respekt, Verständnis) · physische Existenz (Nahrung, Ruhe, Schutz, Bewegung) · Spiel (Spaß, Lachen) · spirituelle Verbundenheit (Schönheit, Harmonie, Frieden).`,
      technical: `Das GFK-Bedürfnisverständnis unterscheidet sich von Maslows Pyramide: Bedürfnisse stehen nicht in fixer Hierarchie, sondern sind gleichwertig und situativ unterschiedlich aktiv. Die Trennung Bedürfnis/Strategie ermöglicht die „Bedürfnisebene“ als gemeinsamen Nenner (alle Bedürfnisse aller Beteiligten gelten als gleich berechtigt), während Strategien verhandelbar bleiben. Zwei Erschließungswege laut Skript: (1) <b>vom unerwünschten Verhalten</b> über das gewünschte Verhalten zum Bedürfnis (Verhalten → Gegenverhalten → „Wofür?“); (2) <b>von der Bewertung</b> zum positiven Gegenteil („unfair“ → Fairness, „chaotisch“ → Ordnung/Klarheit). Prüfkriterien für ein Bedürfnis: Es kann von jeder Person geteilt werden, es braucht keine bestimmte andere Person zur Erfüllung, und es lässt sich auf mehrere Arten erfüllen. Begriffe wie „Ich brauche Respekt von dir“ verunreinigen das Bedürfnis mit einer Person – sauber ist „Mir ist Respekt wichtig“.` } },
    { t: "example", title: "WG-Abwasch – zwei Strategien, zwei Bedürfnisse, eine Lösung", html: `<b>Vorher (Strategie-Kampf):</b><br><i>Sophie:</i> „Geschirr wird sofort nach dem Essen abgewaschen!“<br><i>Paul:</i> „Nein, ich wasch einmal am Abend alles zusammen ab, das ist effizienter.“<br>→ Zwei Strategien, kein Spielraum.<br><br><b>Nachher (Bedürfnisse aufdecken):</b><br><i>Paul:</i> „Was ist dir am sofortigen Abwasch eigentlich wichtig?“<br><i>Sophie:</i> „Ich will, wenn ich heimkomm, einfach kochen können. Ich brauch <b>Erholung</b> und eine <b>freie Arbeitsfläche</b>.“<br><i>Sophie:</i> „Und dir?“<br><i>Paul:</i> „Ich will nicht nach jedem Kaffee an die Spüle müssen – mir ist <b>Selbstbestimmung</b> und <b>Effizienz</b> wichtig.“<br><i>Sophie:</i> „Was wäre, wenn du dein Geschirr sammelst, aber in der Box neben der Spüle, und die Arbeitsfläche bleibt frei?“<br><i>Paul:</i> „Deal.“<br>Neue Strategie, die <b>beide</b> Bedürfnisse erfüllt.` },
    { t: "example", title: "Gruppenarbeit an der FH – Bedürfnisse aus Vorwürfen ableiten", html: `Drei Sätze aus einem Gruppen-Chat und wie man das Bedürfnis findet:<br>1) „Ihr entscheidet eh alles ohne mich!“ → <b>Weg 2</b> (Gegenteil der Bewertung): ausgeschlossen → <b>Beteiligung, Zugehörigkeit</b>.<br>2) „Kannst du bitte aufhören, meine Folien ohne Rückfrage umzubauen?“ → <b>Weg 1</b> (unerwünschtes Verhalten → erwünschtes Verhalten → Bedürfnis): umbauen ohne Rückfrage → vorher fragen → <b>Respekt, Mitsprache</b>.<br>3) „Ich brauch, dass Tom bis Mittwoch liefert.“ → das ist eine <b>Strategie</b> (Person, Zeit). Bedürfnis dahinter: <b>Planbarkeit, Sicherheit</b>. Andere Strategien für dasselbe Bedürfnis: Zwischenstand am Montag, Puffer im Zeitplan, Aufgabentausch.` },
    { t: "hint", title: "Der Strategie-Detektor: P-O-Z-H", html: `Kommt eine <b>P</b>erson, ein <b>O</b>rt, ein <b>Z</b>eitpunkt oder eine <b>H</b>andlung vor? Dann ist es eine Strategie. „Mir ist Ruhe wichtig“ – kein P-O-Z-H → Bedürfnis. „Ich will, dass du ab 22 Uhr leise bist“ – P (du), Z (22 Uhr), H (leise sein) → Strategie.` },
    { t: "hint", title: "Die „Wofür?“-Treppe", html: `Wenn du nur eine Strategie hast, frag so lange <b>„Wofür ist mir das wichtig?“</b>, bis kein Konkretes mehr übrig ist: „Ich will ein neues Handy“ → wofür? „Damit die Fotos besser sind“ → wofür? „Damit ich Erinnerungen festhalten kann“ → Bedürfnis: Verbundenheit mit Erlebtem / Schönheit.` },
    { t: "hint", title: "Typische Falle: „Ich brauche Respekt von dir“", html: `Klingt nach Bedürfnis, enthält aber eine Person („von dir“) – das macht es zu einer halben Strategie und klingt fordernd. Sauber: „<b>Mir ist Respekt wichtig.</b>“ Ebenso: „Ich brauche einen zuverlässigen Freund“ → Bedürfnis „Verlässlichkeit“.` }
  ],

  "k5-4": [
    { t: "text", h: "Vertiefung: Was eine Bitte von einer Forderung unterscheidet", levels: {
      simple: `Eine gute Bitte sagt genau, was jemand jetzt tun kann – nicht was er lassen soll. „Sei nicht so laut“ ist ungenau; „Kannst du die Musik auf Stufe 3 drehen?“ ist klar. Und das Wichtigste: Bei einer echten Bitte ist ein Nein erlaubt. Wenn du nach einem Nein beleidigt bist oder Druck machst, war es eigentlich eine Forderung. Nach einem Nein sucht man gemeinsam weiter.`,
      normal: `Die Bitte ist der vierte GFK-Schritt und macht aus einer Mitteilung eine Einladung zum Handeln. Kriterien einer erfolgversprechenden Bitte:<br>• <b>Positiv</b>: sagen, was ich will, nicht was ich nicht will („Kannst du die Schuhe ins Regal stellen?“ statt „Lass die Schuhe nicht im Gang liegen“). Negative Bitten lassen offen, was stattdessen passieren soll, und klingen vorwurfsvoll.<br>• <b>Konkret und in Handlungssprache</b>: eine beobachtbare Handlung, die jetzt oder zu einem klaren Zeitpunkt möglich ist. „Sei rücksichtsvoller“ ist ein frommer Wunsch – niemand weiß, wann er erfüllt ist.<br>• <b>Erfüllbar</b>: realistisch für die andere Person.<br>• <b>Frei ablehnbar</b>: Der Test liegt in <i>meiner</i> Reaktion auf ein Nein.<br><br>Zwei Arten laut Skript:<br>• <b>Lösungsbitte (Handlungsbitte)</b>: konkrete Handlung → „Wärst du bereit, bis Freitag die Folien 5–8 zu machen?“<br>• <b>Beziehungsbitte</b>: Rückmeldung zur Verbindung → „Was ist bei dir angekommen?“ (sichert Verständnis) oder „Wie geht es dir damit?“ (lädt zu Empathie ein). Gerade nach einer heiklen Mitteilung ist die Beziehungsbitte oft der bessere erste Schritt, weil sie prüft, ob die Botschaft richtig angekommen ist, bevor man über Lösungen spricht.<br><br><b>Nach einem Nein</b>: Ein Nein ist kein Ende, sondern ein Hinweis, dass ein anderes Bedürfnis im Weg steht. Giraffen-Reaktion: Das Bedürfnis hinter dem Nein erfragen („Ist dir gerade Ruhe wichtig?“) und eine Strategie suchen, die beiden dient.`,
      technical: `Rosenberg definiert die Unterscheidung Bitte/Forderung funktional, nicht sprachlich: Ein „bitte“ oder eine Frageform machen eine Aussage nicht zur Bitte. Entscheidend ist, ob der Sprecher bei Ablehnung Strafe, Schuldinduktion oder Liebesentzug einsetzt. Hat das Gegenüber in der Vergangenheit Forderungen erlebt, hört es auch echte Bitten als Forderung; dann helfen Transparenz („Es ist mir wichtig, dass du nur Ja sagst, wenn du es wirklich willst“) und empathisches Eingehen auf ein Nein. Die Bitte bezieht sich auf die Gegenwart („Wärst du bereit …?“), auch wenn die Handlung in der Zukunft liegt – sie fragt nach der jetzigen Bereitschaft. Vage Formulierungen (mehr Mühe, aufmerksamer, verantwortlich) sind problematisch, weil sie keine Erfüllungsbedingung enthalten und Interpretationsspielraum für erneute Vorwürfe lassen. Eine Bitte ohne vorangehende Beobachtung, Gefühl und Bedürfnis wirkt leicht wie ein Befehl; Beobachtung, Gefühl und Bedürfnis ohne Bitte wirken wie Klage oder Vorwurf.` } },
    { t: "example", title: "Gehaltsverhandlung im Ferialjob – Bitte vs. Forderung", html: `Kevin arbeitet im Sommer im Lager eines Getränkehändlers und soll zusätzlich die Inventur-Excel betreuen.<br><b>Vorher (Forderung im Bitten-Kleid):</b><br><i>Kevin:</i> „Könnten Sie mir bitte mehr zahlen? Sonst muss ich mir halt überlegen, ob ich nächstes Jahr wiederkomme.“<br>Vage („mehr“) + Drohung → Forderung. <i>Chefin:</i> „Dann überlegen Sie mal.“<br><br><b>Nachher (konkrete Bitte mit Wahlfreiheit):</b><br><i>Kevin:</i> „Seit drei Wochen betreue ich neben dem Lager auch die Inventurliste, etwa 6 Stunden pro Woche. Mir ist wichtig, dass das fair abgebildet ist. Wären Sie bereit, für diese Stunden den Stundensatz der Bürokräfte anzusetzen, oder mit mir am Freitag 15 Minuten darüber zu reden?“<br><i>Chefin:</i> „Den Bürosatz kann ich nicht einfach so geben. Aber reden wir am Freitag.“<br><i>Kevin:</i> „Passt, danke.“ – Kein beleidigter Rückzug: Das zeigt, dass es eine echte Bitte war.` },
    { t: "example", title: "Gespräch mit der Mutter – frommer Wunsch → Bitte", html: `<b>Frommer Wunsch:</b> „Mama, kannst du mich einfach mal mein Leben leben lassen?“ – unklar, was sie konkret tun soll.<br><b>Lösungsbitte:</b> „Mama, magst du mich beim Telefonieren zuerst fragen, wie's mir geht, bevor wir über die Prüfungen reden?“ – konkret, positiv, sofort umsetzbar.<br><b>Beziehungsbitte:</b> „Ich hab jetzt einiges gesagt – was ist bei dir angekommen?“ – <i>Mutter:</i> „Dass dich meine Fragen nerven.“ – <i>Kevin:</i> „Nicht ganz – mich freut, dass du dich interessierst. Mir ist nur wichtig, dass es nicht nur um die Uni geht.“ Die Beziehungsbitte hat ein Missverständnis aufgedeckt, bevor es sich festsetzt.` },
    { t: "hint", title: "Der Nein-Test", html: `Stell dir vor, die Person sagt <b>Nein</b>. Was wäre deine spontane Reaktion? Vorwurf, Schmollen, „Na toll“, Druck → es war eine <b>Forderung</b>. Neugier („Was spricht für dich dagegen?“) → es war eine <b>Bitte</b>. Das Wort „bitte“ allein macht noch keine Bitte.` },
    { t: "hint", title: "Eselsbrücke: PoKoHa", html: `Eine gute Bitte ist <b>Po</b>sitiv („was ich will“), <b>Ko</b>nkret (wer, was, wann) und in <b>Ha</b>ndlungssprache (etwas, das man tun kann). Plus: frei ablehnbar. Prüfe jede Bitte: Wüsste die Person genau, wann sie erfüllt ist?` },
    { t: "hint", title: "Typische Falle: „Ich möchte, dass du dir mehr Mühe gibst“", html: `Wirkt konkret, ist aber ein frommer Wunsch: „mehr Mühe“ ist nicht messbar. Umbau: „Wärst du bereit, deine Folien vor dem Hochladen einmal mit der Checkliste abzugleichen?“ Daraus wird eine beobachtbare Handlung.` }
  ],

  "k5-5": [
    { t: "text", h: "Vertiefung: Die vier Schritte als Ganzes – senden UND empfangen", levels: {
      simple: `Die vier Schritte sind: 1) Was habe ich gesehen/gehört? 2) Wie geht es mir damit? 3) Was ist mir wichtig? 4) Worum bitte ich? Man kann sie in zwei Richtungen nutzen: Um selbst ehrlich zu sagen, was los ist – und um zuzuhören, was beim anderen los ist („Bist du sauer, weil dir … wichtig ist?“). Es muss nicht nach Lehrbuch klingen; Hauptsache, alle vier Teile sind drin.`,
      normal: `Die vier Komponenten bilden eine Kette, bei der jeder Schritt den nächsten vorbereitet: Die <b>Beobachtung</b> schafft eine gemeinsame Basis, das <b>Gefühl</b> zeigt, dass mich etwas berührt, das <b>Bedürfnis</b> erklärt, warum (und nimmt dem anderen die Schuld), die <b>Bitte</b> zeigt einen Weg nach vorn.<br><br><b>Zwei Richtungen:</b><br>• <b>Aufrichtig ausdrücken</b>: „Wenn ich sehe …, bin ich …, weil mir … wichtig ist. Wärst du bereit …?“<br>• <b>Empathisch empfangen</b>: Ich übersetze, was der andere sagt, in seine vier Schritte und frage nach: „Bist du ärgerlich, weil dir … wichtig ist?“ Gerade bei Vorwürfen ist das oft wirkungsvoller als die eigene Botschaft – erst wenn sich jemand verstanden fühlt, kann er zuhören.<br><br><b>Typische Stolpersteine</b>:<br>1. Beobachtung enthält Warnwort („Du hast schon wieder …“).<br>2. Pseudogefühl („Ich fühle mich ignoriert“).<br>3. „Weil du …“ statt „weil mir … wichtig ist“ – dann wird das Bedürfnis wieder zum Vorwurf.<br>4. Bitte fehlt oder ist vage.<br>5. Zu lange Monologe – lieber kurze Sätze und Pausen für die Reaktion.<br><br>Die Reihenfolge ist eine Lernhilfe: Im echten Gespräch darf man natürlich formulieren und auch einzelne Schritte vorziehen – solange Beobachtung, Gefühl, Bedürfnis und Bitte erkennbar sind. <i>Hinweis: Die folgenden Beispiele sind erfundene Übungssituationen – eigene Portfolio-Texte müssen selbst und ohne KI entstehen.</i>`,
      technical: `Formal: Ausdruck = B (Stimulus, beobachtbar) + G (affektiver Zustand) + Bd (universelles Bedürfnis, Ursache des G) + Bi (konkrete, gegenwärtige, ablehnbare Handlungsanfrage). Empathie = Vermutung über G' und Bd' des Gegenübers, als Frage formuliert, mit anschließender Bestätigung oder Korrektur. Rosenberg empfiehlt bei starken Emotionen die Reihenfolge Selbstempathie → Empathie für das Gegenüber → Ausdruck; man kann nur zuhören, wenn die eigenen Gefühle nicht überlaufen („Notfall-Empathie“ für sich selbst). Der Schritt vom Bedürfnis zur Bitte trennt Bedürfnis (nicht verhandelbar, aber gleichrangig mit den Bedürfnissen anderer) von Strategie (verhandelbar). Kritik am Modell: Mechanische Anwendung („Giraffen-Formelsprache“) wird als künstlich oder manipulativ erlebt; die Haltung (echtes Interesse an beiden Bedürfnissen) ist Voraussetzung der Wirkung.` } },
    { t: "example", title: "Konflikt im Fußballteam – Vorwurf in vier Schritten", html: `Torhüter Daniel ärgert sich über Verteidiger Lukas.<br><b>Vorher:</b><br><i>Daniel:</i> „Du stehst nie, wo du stehen sollst! Wegen dir kassieren wir jedes Tor!“<br><i>Lukas:</i> „Jetzt bin ich wieder schuld? Halt du lieber mal einen Ball!“<br><br><b>Nachher:</b><br><i>Daniel:</i> „Bei den letzten zwei Gegentoren warst du bei der Flanke am langen Pfosten und der Stürmer stand allein am kurzen (<b>Beobachtung</b>). Ich war da ziemlich frustriert (<b>Gefühl</b>), weil mir wichtig ist, dass wir uns hinten aufeinander verlassen können (<b>Bedürfnis</b>). Magst du nach dem Training 10 Minuten mit mir die Zuteilung bei Flanken durchgehen? (<b>Bitte</b>)“<br><i>Lukas:</i> „Ehrlich gesagt war mir nicht klar, dass ich den kurzen nehmen soll. Ja, machen wir.“` },
    { t: "example", title: "Gruppenarbeit an der FH – empathisch empfangen", html: `Mia schreibt im Gruppenchat: „Ich hab echt keinen Bock mehr, ich mach hier alles allein!“<br><b>Vorher:</b> <i>Kevin:</i> „Stimmt doch gar nicht, ich hab die ganze Recherche gemacht.“ → Rechtfertigung, Streit.<br><b>Nachher</b> (Kevin hört die vier Schritte in Mias Satz und fragt nach):<br><i>Kevin:</i> „Klingt, als wärst du ziemlich erschöpft und frustriert (<b>Gefühl</b>) – geht's dir drum, dass die Arbeit fair verteilt ist und du dich auf uns verlassen kannst (<b>Bedürfnis</b>)?“<br><i>Mia:</i> „Ja. Ich hab die letzten zwei Abende die Folien formatiert und keiner hat was gesagt.“ (<b>Beobachtung</b> – liefert sie jetzt selbst)<br><i>Kevin:</i> „Danke, dass du das sagst. Wärst du einverstanden, wenn wir morgen um 10 kurz telefonieren und die restlichen Aufgaben neu verteilen? (<b>Bitte</b>)“` },
    { t: "hint", title: "Satzschablone zum Üben (nicht für Abgaben)", html: `„Als ich <b>[Kamera-Beobachtung]</b> gesehen/gehört habe, war ich <b>[echtes Gefühl]</b>, weil mir <b>[Bedürfnis]</b> wichtig ist. Wärst du bereit, <b>[konkrete Handlung, Zeitpunkt]</b>?“ – Zum Empfangen: „Bist du <b>[Gefühl]</b>, weil dir <b>[Bedürfnis]</b> wichtig ist?“` },
    { t: "hint", title: "Checkliste: Die 4 häufigsten Fehler", html: `☐ Warnwort in der Beobachtung? (immer, nie, schon wieder) ☐ Pseudogefühl? (ignoriert, ausgenutzt) ☐ „weil du …“ statt „weil mir … wichtig ist“? ☐ Bitte vage oder negativ? Wenn alle Kästchen leer bleiben, ist die Botschaft stimmig.` },
    { t: "hint", title: "Wenn's emotional wird: Reihenfolge ändern", html: `Bist du selbst gerade sehr wütend, starte mit <b>Selbstempathie</b> (kurz für dich: Was fühle ich, was brauche ich?). Ist das Gegenüber aufgebracht, starte mit <b>Empathie</b> (Gefühl + Bedürfnis des anderen erfragen). Deine eigene 4-Schritte-Botschaft kommt erst, wenn sich der andere verstanden fühlt.` }
  ],

  /* ================= Welt 6: Aktives Zuhören ================= */
  "k6-1": [
    { t: "text", h: "Vertiefung: Paraphrasieren, Verbalisieren – und die 12 Gesprächsblocker", levels: {
      simple: `Aktiv zuhören heißt: Ich zeige dir, dass ich dich verstehen will – mit Blick, Nicken, kurzen Zusammenfassungen und Fragen. Ich gebe keine Ratschläge, urteile nicht und erzähle nicht gleich meine eigene Geschichte. Zwei Werkzeuge sind besonders wichtig: Inhalt in eigenen Worten wiederholen („Du meinst, …?“) und das Gefühl dahinter ansprechen („Das hat dich echt geärgert, oder?“). Dann fühlt sich der andere verstanden und erzählt weiter.`,
      normal: `Das Konzept geht auf den Psychologen <b>Carl Rogers</b> (klientenzentrierte Gesprächsführung) zurück und wurde von <b>Thomas Gordon</b> für Alltag, Familie und Führung bekannt gemacht. Grundhaltung nach Rogers: <b>Empathie</b> (die Welt mit den Augen des anderen sehen), <b>Akzeptanz</b> (den Menschen wertschätzen, auch wenn man seine Meinung nicht teilt) und <b>Echtheit/Kongruenz</b> (nur so viel Interesse zeigen, wie man wirklich hat).<br><br><b>Die Techniken in Stufen:</b><br>1. <b>Aufmerksam sein</b> (nonverbal): Blickkontakt, Nicken, zugewandte Haltung, „mhm“, Handy weg.<br>2. <b>Paraphrasieren</b> = den <i>Inhalt</i> mit eigenen Worten zurückgeben: „Du hast also bis Mittwoch keine Rückmeldung bekommen?“<br>3. <b>Verbalisieren</b> = das <i>Gefühl/Bedürfnis</i> ansprechen: „Das klingt, als hätte dich das verunsichert.“<br>4. <b>Nachfragen und ermutigen</b>: offene Fragen („Wie ging's dann weiter?“), Pausen aushalten.<br>5. <b>Zusammenfassen</b> am Ende längerer Abschnitte.<br>Wichtig: Paraphrase und Verbalisierung sind <b>Angebote mit Fragezeichen</b> – der andere darf korrigieren, und genau die Korrektur bringt das Gespräch weiter.<br><br><b>Barrieren</b> (laut Skript): <b>physisch</b> (Lärm, Müdigkeit, monotone Stimme), <b>emotional</b> (Vorurteile, Reizwörter, schlechte Erfahrungen) und <b>semantisch</b> (unterschiedlicher Wortschatz, Fachjargon). Dazu kommen Gordons <b>12 Kommunikationssperren</b> – gut gemeinte Reaktionen, die das Gespräch beenden (siehe Tipp unten).`,
      technical: `Gordons „Kommunikationssperren“ (roadblocks) haben gemeinsam, dass der Zuhörer eine <b>eigene Botschaft</b> sendet, statt die des Sprechers aufzunehmen; dadurch geht das Anliegen des Sprechers unter. Gordon unterscheidet passives Zuhören (Schweigen, Aufmerksamkeitsreaktionen, „Türöffner“ wie „Erzähl mal“) und aktives Zuhören (Rückmeldung der verstandenen Bedeutung). In der Gesprächspsychotherapie nach Rogers wird zwischen Paraphrasieren (kognitiver Inhalt) und Verbalisieren emotionaler Erlebnisinhalte (VEE) unterschieden; Letzteres gilt als wirksamer, weil es die Bedeutungsebene „unter der Wasserlinie“ adressiert. Bezug zur GFK: Empathisches Empfangen in vier Schritten entspricht verbalisierendem Zuhören mit Fokus auf Gefühl und Bedürfnis. Bezug zu Schulz von Thun: Aktives Zuhören schult das Selbstkundgabe-Ohr und verhindert vorschnelles Hören mit dem Beziehungsohr. Grenzen: Aktives Zuhören ist unpassend, wenn eine Sachinformation verlangt wird („Wo ist der Schlüssel?“) oder wenn es als Technik ohne echtes Interesse eingesetzt wird (Papageien-Effekt).` } },
    { t: "example", title: "Gespräch mit der Mutter – Blocker vs. aktives Zuhören", html: `Kevins Mutter erzählt: „In der Arbeit haben sie jetzt ein neues Programm eingeführt, und ich komm überhaupt nicht mit. Die Jungen klicken da herum, und ich sitz daneben.“<br><b>Vorher (drei Blocker hintereinander):</b><br><i>Kevin:</i> „Mach halt einen Kurs auf YouTube (<i>Ratschlag</i>). Ist eh total einfach (<i>Bagatellisieren/Belehren</i>). Bei uns an der FH haben wir sowas im ersten Semester gemacht …“ (<i>Ablenken auf sich</i>)<br><i>Mutter:</i> „Ja, eh. Lassen wir das.“<br><br><b>Nachher:</b><br><i>Kevin:</i> „Ihr arbeitet jetzt mit einem neuen Programm, und die Jüngeren sind schneller drin? (<i>Paraphrase</i>)“<br><i>Mutter:</i> „Genau. Und keiner erklärt was.“<br><i>Kevin:</i> „Das klingt frustrierend – und vielleicht auch ein bisschen so, als würdest du abgehängt? (<i>Verbalisieren</i>)“<br><i>Mutter:</i> „Ja … ich hab Angst, dass sie mich irgendwann nicht mehr brauchen.“<br><i>Kevin:</i> „Magst du mir mehr erzählen? (<i>Ermutigen</i>)“<br>Erst durch das Zuhören kommt das eigentliche Thema – die Sorge um den Job – zum Vorschein.` },
    { t: "example", title: "Gruppenarbeit an der FH – Barrieren erkennen", html: `Im Teams-Call erklärt Tom seine Datenbank-Idee. Die anderen verstehen nichts. Analyse:<br>• <b>Physisch:</b> Toms Mikro rauscht, und es ist 21 Uhr – alle sind müde.<br>• <b>Semantisch:</b> Tom spricht von „3NF“ und „Fremdschlüssel-Constraints“; Lena kennt die Begriffe nicht.<br>• <b>Emotional:</b> Paul denkt bei Toms Vorschlägen schon vorher „Der will sich eh nur wichtig machen“ – ein Vorurteil, das das Zuhören filtert.<br><b>Nachher:</b> Mikro getauscht, Call auf den nächsten Vormittag verlegt, Lena fragt nach („Was heißt 3NF in einem Satz?“), Paul paraphrasiert bewusst, bevor er bewertet: „Du willst also die Kundendaten in eine eigene Tabelle auslagern, damit nichts doppelt gespeichert wird?“ – <i>Tom:</i> „Genau!“` },
    { t: "hint", title: "Gordons 12 Gesprächsblocker auf einen Blick", html: `1 Befehlen · 2 Warnen/Drohen · 3 Moralisieren · 4 Ratschläge/Lösungen geben · 5 Belehren/logisch argumentieren · 6 Kritisieren/Urteilen · 7 Loben/Zustimmen (wenn's das Gespräch abwürgt) · 8 Beschimpfen/Lächerlich machen · 9 Interpretieren/Diagnostizieren · 10 Beruhigen/Trösten („Wird schon!“) · 11 Ausfragen/Verhören · 12 Ablenken/Themawechsel. Merke: Alle senden <b>meine</b> Botschaft, statt die des anderen aufzunehmen.` },
    { t: "hint", title: "Paraphrasieren vs. Verbalisieren", html: `<b>Paraphrasieren</b> = Was hat sie <i>gesagt</i>? (Inhalt, Kopf) – „Du hast also die Mail erst am Freitag bekommen?“<br><b>Verbalisieren</b> = Was <i>fühlt/braucht</i> sie? (Gefühl, Bauch) – „Das hat dich unter Zeitdruck gebracht?“<br>Eselsbrücke: <b>Para</b>phrase = <b>para</b>llele Worte für den Inhalt; <b>Verbal</b>isieren = das Unausgesprochene in Worte fassen.` },
    { t: "hint", title: "Typische Prüfungsfalle: Müdigkeit & monotone Stimme", html: `Beide zählen laut Skript zu den <b>physischen</b> Barrieren, nicht zu den emotionalen – auch wenn Müdigkeit sich „innerlich“ anfühlt. Emotional = Einstellungen und Gefühle zum Thema oder zur Person (Vorurteile, Reizwörter, schlechte Erfahrungen). Semantisch = alles, was mit Wortbedeutungen zu tun hat.` }
  ],

  "k6-2": [
    { t: "text", h: "Vertiefung: Warum Du-Botschaften Verteidigung auslösen – und wie man sie umbaut", levels: {
      simple: `Eine Du-Botschaft zeigt mit dem Finger auf den anderen: „Du bist rücksichtslos!“ Der andere fühlt sich angegriffen und verteidigt sich. Eine Ich-Botschaft erzählt, was bei mir passiert: „Ich bin gestresst, wenn um Mitternacht laut Musik läuft, weil ich Schlaf brauche.“ Der andere erfährt so, was sein Verhalten bewirkt – ohne beschimpft zu werden. Achtung: „Ich finde, du bist …“ beginnt zwar mit „Ich“, ist aber trotzdem eine Du-Botschaft.`,
      normal: `Den Begriff „Ich-Botschaft“ prägte <b>Thomas Gordon</b> („Familienkonferenz“, Original 1970). Gordons Version hat drei Teile: (1) das <b>Verhalten</b> ohne Bewertung beschreiben, (2) die <b>konkrete Auswirkung</b> auf mich nennen, (3) mein <b>Gefühl</b> ausdrücken. Die Kursformel kombiniert das mit der GFK: <b>Gefühl – Verhalten (ohne Schuld) – Bedürfnis/Wunsch</b>.<br><br><b>Warum es wirkt:</b> Eine Du-Botschaft ist meist eine <b>Bewertung der Person</b> („Du bist unzuverlässig“) und landet direkt auf dem Beziehungsohr – der andere muss sein Selbstbild verteidigen. Eine Ich-Botschaft ist eine <b>Selbstkundgabe</b>: Über mein Gefühl kann man nicht streiten, und das beschriebene Verhalten ist konkret und änderbar. Der andere behält die Freiheit, selbst zu entscheiden, wie er reagiert.<br><br><b>Verkleidete Du-Botschaften</b> – beginnen mit „Ich“, enthalten aber ein Urteil:<br>• „Ich finde, du bist egoistisch.“ (Urteil)<br>• „Ich fühle mich von dir verarscht.“ (Pseudogefühl)<br>• „Ich bin sauer, weil du nie zuhörst.“ (Ursache = du, plus Warnwort „nie“)<br><br><b>Grenzen:</b> Ich-Botschaften sind kein Zaubertrick. In sehr hitzigen Situationen braucht es zuerst Zuhören (Empathie). Und zu häufige, routinierte Ich-Botschaften wirken künstlich – Echtheit ist wichtiger als die perfekte Formel.`,
      technical: `In Gordons Modell dient die Ich-Botschaft der Situation, in der der Sender das „Problem besitzt“ (das Verhalten des anderen beeinträchtigt ihn), während aktives Zuhören für Situationen gedacht ist, in denen der andere das Problem besitzt. Gordon unterscheidet u. a. konfrontierende, präventive und positive (wertschätzende) Ich-Botschaften sowie das „Umschalten“ auf aktives Zuhören, wenn der andere defensiv reagiert. Kommunikationspsychologisch verschiebt die Ich-Botschaft den Fokus von der Beziehungsseite (Urteil über das Du) auf die Selbstkundgabe und einen offen formulierten Appell. Prüfkriterien: Subjekt des Gefühlssatzes ist „ich“; das Gefühlswort ist ein echtes Gefühl (vgl. k5-2); der Verhaltensteil ist eine Beobachtung (vgl. k5-1); der Begründungsteil nennt das eigene Bedürfnis, nicht das Fehlverhalten des anderen als Ursache. Eine Ich-Botschaft garantiert keine Verhaltensänderung, erhöht aber die Wahrscheinlichkeit freiwilliger Rücksichtnahme, weil sie die Autonomie des Gegenübers respektiert.` } },
    { t: "example", title: "WG-Streit über den Abwasch – Du → Ich", html: `<b>Vorher (Du-Botschaft):</b><br><i>Sophie:</i> „Du bist echt das Letzte, du lässt deinen Dreck einfach stehen.“<br><i>Paul:</i> „Und du bist ein Kontrollfreak. Zieh doch aus, wenn's dir nicht passt.“<br>Beide antworten auf der Beziehungsebene mit einem Gegenurteil – Eskalation.<br><br><b>Nachher (Ich-Botschaft nach Kursformel):</b><br><i>Sophie:</i> „Ich bin genervt und ziemlich müde (<b>Gefühl</b>), wenn ich nach der Arbeit heimkomm und die Spüle mit Töpfen voll ist (<b>Verhalten ohne Schuld</b>), weil ich dann einfach in Ruhe kochen möchte (<b>Bedürfnis</b>). Ich würd mich freuen, wenn die Spüle bis 18 Uhr frei ist (<b>Wunsch</b>).“<br><i>Paul:</i> „Okay, ich wusste nicht, dass dich das so trifft. 18 Uhr krieg ich hin.“<br>Paul muss sich nicht verteidigen, weil niemand über seinen Charakter urteilt.` },
    { t: "example", title: "Konflikt im Fußballteam – verkleidete Du-Botschaften entlarven", html: `Kapitän Marko will dem Trainer sagen, dass ihn die kurzfristigen Trainingsänderungen stören. Drei Versuche:<br>1) „Ich finde, Sie planen echt chaotisch.“ → <b>verkleidete Du-Botschaft</b> (Urteil „chaotisch“).<br>2) „Ich fühl mich von Ihnen nicht ernst genommen.“ → <b>Pseudogefühl</b> („nicht ernst genommen“ beschreibt, was der Trainer angeblich tut).<br>3) „Ich bin unter Druck (<i>Gefühl</i>), wenn die Trainingszeit am selben Tag per WhatsApp verschoben wird (<i>Verhalten</i>), weil ich neben dem Studium planen können möchte (<i>Bedürfnis Planbarkeit</i>). Ginge es, Änderungen bis zum Vortag anzukündigen? (<i>Wunsch</i>)“ → <b>echte Ich-Botschaft</b>.<br><i>Trainer:</i> „Das war mir nicht bewusst. Bis zum Vortag versuch ich's.“` },
    { t: "hint", title: "Der Ich-Anfang ist kein Beweis", html: `Lösch gedanklich das „Ich finde/glaube/habe das Gefühl“ am Satzanfang. Bleibt ein Urteil über das Du übrig („… du bist arrogant“), ist es eine <b>verkleidete Du-Botschaft</b>. Echte Ich-Botschaft: Das Gefühl gehört mir, das Verhalten ist kamera-tauglich, das Bedürfnis gehört mir.` },
    { t: "hint", title: "Formel-Spickzettel", html: `<b>Kursformel:</b> Ich bin <b>[Gefühl]</b>, wenn <b>[Verhalten ohne Schuld]</b>, weil ich <b>[Bedürfnis]</b> brauche / Ich würde mich freuen, wenn <b>[Wunsch]</b>.<br><b>Gordon (Original):</b> Verhalten → konkrete Auswirkung auf mich → Gefühl.<br>Beide sind richtig – bei Übungen im Kurs die Kursformel verwenden.` },
    { t: "hint", title: "Typischer Fehler im „weil“-Teil", html: `„Ich bin sauer, <b>weil du</b> immer zu spät kommst“ macht den anderen zur Ursache – das ist wieder ein Vorwurf. Richtig: „Ich bin sauer, <b>weil mir</b> Verlässlichkeit wichtig ist.“ Faustregel: Nach dem „weil“ kommt <b>ich/mir</b>, nicht <b>du</b>.` }
  ],

  /* ================= Welt 7: Harvard-Konzept ================= */
  "k7-1": [
    { t: "text", h: "Vertiefung: Vom Positionsfeilschen zur sachbezogenen Verhandlung", levels: {
      simple: `Beim normalen Feilschen sagt jeder, was er will („Ich will 15 Euro pro Stunde!“ – „Ich zahl 12!“), und man trifft sich irgendwo in der Mitte oder streitet. Das Harvard-Konzept macht es anders: Man fragt, <b>warum</b> jeder etwas will, sucht Lösungen, bei denen beide gewinnen, und entscheidet nach fairen Regeln statt nach Lautstärke. Dabei bleibt man freundlich zu den Menschen, aber klar in der Sache. Vorher sollte man seinen Plan B kennen (BATNA).`,
      normal: `Das Harvard-Konzept stammt von <b>Roger Fisher und William Ury</b> (Harvard Negotiation Project, Buch „Getting to Yes“, 1981; dt. „Das Harvard-Konzept“). Es grenzt sich vom <b>Positionsfeilschen</b> ab, bei dem beide Seiten extreme Startpositionen nennen und sich in kleinen Schritten annähern. Probleme dabei: ineffizient, beziehungsschädigend und oft ein fauler Kompromiss, der niemandem wirklich hilft. Weder „weich“ (nachgeben um des Friedens willen) noch „hart“ (gewinnen um jeden Preis) ist gut – das Motto lautet: <b>hart in der Sache, weich zu den Menschen</b>.<br><br><b>Die vier Prinzipien:</b><br>1. <b>Menschen und Probleme trennen</b>: Wahrnehmungen klären, Emotionen anerkennen, zuhören. Gemeinsam gegen das Problem, nicht gegeneinander.<br>2. <b>Interessen statt Positionen</b>: Eine Position ist <i>was</i> jemand fordert; ein Interesse ist <i>warum</i>. Fragen: „Wofür brauchen Sie das?“ „Was wäre daran schlecht?“ Hinter gegensätzlichen Positionen liegen oft vereinbare Interessen (Orangen-Beispiel: Saft vs. Schale).<br>3. <b>Optionen zum beiderseitigen Vorteil</b>: erst Ideen sammeln, dann bewerten. „Den Kuchen vergrößern“, statt ihn nur zu teilen.<br>4. <b>Objektive Kriterien</b>: Marktpreise, Kollektivvertrag, Gutachten, Gleichbehandlung, Losentscheid – Maßstäbe, die unabhängig vom Willen beider Seiten sind.<br><br><b>BATNA</b> ist das Sicherheitsnetz: Wer seine beste Alternative kennt, nimmt keinen schlechteren Deal an und kann gelassen verhandeln. Eine starke BATNA verschafft Verhandlungsmacht – darum lohnt es sich, sie <b>vor</b> der Verhandlung zu verbessern.`,
      technical: `Fisher/Ury definieren „principled negotiation“ über vier Elemente (People, Interests, Options, Criteria) und bewerten Verhandlungsmethoden nach drei Kriterien: Sie sollen ein kluges Ergebnis liefern (sofern Einigung möglich), effizient sein und die Beziehung verbessern oder zumindest nicht schädigen. Die BATNA dient als Maßstab, gegen den jedes Angebot geprüft wird; sie ersetzt das starre „Bottom Line“-Limit, das Kreativität verhindert. In der Verhandlungslehre wird ergänzend die <b>ZOPA</b> (Zone of Possible Agreement) betrachtet: der Bereich, in dem beide Seiten besser gestellt sind als mit ihrer jeweiligen BATNA; existiert keine ZOPA, ist Nicht-Einigung rational. Die WATNA (schlechteste Alternative) verdeutlicht das Risiko des Scheiterns. Bezug zur GFK: Interessen entsprechen weitgehend Bedürfnissen, Positionen den Strategien; Prinzip 1 deckt sich mit Empathie und der Trennung von Beobachtung und Bewertung. Kritikpunkte: Die Methode setzt Kooperationsbereitschaft voraus und stößt bei starken Machtasymmetrien oder Wertekonflikten an Grenzen; Fisher/Ury empfehlen für unkooperative Gegenüber u. a. „Verhandlungs-Judo“ (Angriffe nicht kontern, sondern auf das Problem umlenken).` } },
    { t: "example", title: "Gehaltsverhandlung im Ferialjob – alle vier Prinzipien", html: `Kevin soll im Sommer wieder 8 Wochen beim Getränkehändler arbeiten. Erfundene Zahlen: Letztes Jahr 12 €/h brutto. Er möchte 14 €, die Chefin bietet 12,50 €.<br><b>Vorher (Positionsfeilschen):</b><br><i>Kevin:</i> „Ich will 14 Euro.“ – <i>Chefin:</i> „12,50, mehr geht nicht.“ – <i>Kevin:</i> „Dann 13,50?“ – <i>Chefin:</i> „13 und fertig.“ Keiner ist zufrieden, keiner weiß, warum.<br><br><b>Nachher:</b><br>1) <i>Menschen/Problem trennen:</i> „Mir ist wichtig, dass wir eine Lösung finden, mit der wir beide gut leben können – ich arbeite gern bei Ihnen.“<br>2) <i>Interessen:</i> „Was ist Ihnen beim Lohn wichtig?“ – <i>Chefin:</i> „Die Personalkosten im Sommer sind hoch, und ich brauch jemanden, der auch die Excel-Inventur kann.“ Kevins Interessen: Geld fürs Semester, Anerkennung seiner IT-Kenntnisse.<br>3) <i>Optionen:</i> Grundlohn 13 € + 15 € für die Inventur-Stunden · Fixbetrag für die Inventur · 14 €, dafür flexibler Einsatz an Hitzetagen.<br>4) <i>Objektive Kriterien:</i> „Was sieht der Kollektivvertrag für Bürotätigkeiten vor? Daran könnten wir uns für die Inventur-Stunden orientieren.“<br><b>BATNA</b> Kevin: Angebot eines Supermarkts für 13 €/h. <b>WATNA</b>: kein Ferialjob, Sommer ohne Einkommen. Ergebnis: 13 € + 15 € für die Inventur-Stunden – besser als Kevins BATNA, also sinnvoll anzunehmen.` },
    { t: "example", title: "Konflikt im Fußballteam – Interessen hinter Positionen", html: `Der Verein hat nur einen Trainingsplatz am Dienstag 18–20 Uhr. Die Kampfmannschaft (Position: „Wir brauchen den ganzen Platz“) und die U16 (Position: „Wir wollen auch dienstags“) streiten.<br><b>W-Fragen:</b> Warum dienstags? → U16: „Mittwochs haben die Jugendlichen Nachmittagsunterricht“ (<i>Interesse: Vereinbarkeit mit Schule</i>). Warum der ganze Platz? → Kampfmannschaft: „Wir üben Standards und brauchen ein Tor plus Strafraum“ (<i>Interesse: Standardsituationen trainieren</i>).<br><b>Optionen:</b> Platz halbieren (die Kampfmannschaft braucht nur eine Hälfte mit Tor) · U16 18–19, Kampfmannschaft 19–20 · Tausch mit dem Donnerstag.<br><b>Objektives Kriterium:</b> Platzvergabe nach Anzahl der Spieler pro Hälfte oder Vereinsregel „Jugend vor 19 Uhr“.<br>Ergebnis: Hälfte-Hälfte – beide Interessen erfüllt, ohne dass jemand „verliert“.` },
    { t: "hint", title: "Eselsbrücke: MIOK", html: `<b>M</b>enschen und Probleme trennen · <b>I</b>nteressen statt Positionen · <b>O</b>ptionen entwickeln · <b>K</b>riterien (objektiv). Merksatz: „<b>M</b>it <b>I</b>deen <b>O</b>hne <b>K</b>ampf.“ Plus BATNA als Sicherheitsnetz.` },
    { t: "hint", title: "Position oder Interesse? Der Warum-Test", html: `Kann man sinnvoll „<b>Warum?</b>“ oder „<b>Wofür?</b>“ fragen und bekommt einen tieferen Grund, war es eine <b>Position</b>. „Ich will 10 % mehr“ → warum? → „Ich brauche finanzielle Sicherheit“ (Interesse). Gleiche Logik wie in der GFK: Position ≈ Strategie, Interesse ≈ Bedürfnis.` },
    { t: "hint", title: "Typische Prüfungsfalle: BATNA ≠ Mindestforderung", html: `Die BATNA ist <b>keine Zahl, die du in der Verhandlung forderst</b>, sondern das, was du tust, <b>wenn es keine Einigung gibt</b> (z. B. das andere Jobangebot). Nimm nur an, was besser ist als deine BATNA. Und: Die WATNA ist das schlechteste <i>realistische</i> Szenario ohne Einigung – nicht das schlechteste Angebot der Gegenseite.` }
  ]
};
})();
