/* Vertiefung & Alltagsbeispiele – ENG3 */
(function () {
window.STUDYOS_DEEP = window.STUDYOS_DEEP || {};
window.STUDYOS_DEEP["eng3"] = window.STUDYOS_DEEP["eng3"] || {};
})();

/* ===== World 1: Figures & Trends ===== */
(function () {
var D = window.STUDYOS_DEEP["eng3"];
D["e1-1"] = [
  { t: "text", h: "Vertiefung: verbs, nouns and prepositions of change", levels: {
    simple: "To talk about numbers you need three things: a <b>verb</b> (rise, fall, stay), a word for <b>how much</b> (slightly, sharply) and the right <b>preposition</b>. <i>by</i> = the size of the change, <i>to</i> = the new number, <i>from</i> = the old number, <i>at</i> = where it is now. Example: <i>Prices rose <b>from</b> €1.50 <b>to</b> €1.80, <b>by</b> 30 cents.</i> Then they <i>stood <b>at</b> €1.80</i>.",
    normal: "A good trend sentence has four parts: <b>subject</b> (what is measured) + <b>verb</b> (direction) + <b>adverb</b> (strength/speed) + <b>figures with prepositions</b> + <b>time</b>.<br><i>Spotify's subscriber numbers rose sharply from 205 million to 263 million between 2022 and 2024.</i><br><b>Prepositions</b> (Präpositionen) are where most marks are lost:<ul><li><b>from … to …</b> – start and end level: <i>Sales went up from 30 to 45.</i></li><li><b>by</b> – the size of the change: <i>Sales went up by 15 (= by 50 %).</i></li><li><b>at</b> – a level at a point in time: <i>Unemployment stands at 5.2 %.</i> / <i>Prices peaked at €2.10.</i></li><li><b>of</b> – after a NOUN: <i>a rise <b>of</b> 15 %</i> (not “a rise by”).</li><li><b>in</b> – what rises: <i>a rise <b>in</b> sales</i> (Anstieg <b>der</b> Verkäufe).</li><li><b>on</b> – compared with: <i>up 50 % <b>on</b> last year</i> (gegenüber dem Vorjahr).</li></ul>Two families of verbs: <b>intransitive</b> (no object: <i>rise, fall, grow, drop, soar, slump</i>) and <b>transitive</b> (with an object: <i>raise, increase, cut, slash, ramp up, boost</i>). Many verbs can be both: <i>Sales increased</i> / <i>We increased sales</i>.",
    technical: "Tense follows the time frame of the data: a closed period → <b>past simple</b> (<i>sales fell in 2023</i>); a period continuing up to now → <b>present perfect</b> (<i>sales have fallen since January</i>); a current level → <b>present simple</b> (<i>it stands at 13 %</i>); forecasts → <b>will / be expected to / be likely to / be set to</b> (<i>prices are expected to level out</i>). Irregular forms are frequent errors: <i>rise – rose – risen</i>, <i>fall – fell – fallen</i>, <i>grow – grew – grown</i>, <i>shoot up – shot up</i>, <i>rise</i> (intransitive) vs. <i>raise – raised – raised</i> (transitive). Multiplication words: <i>double, triple/treble, quadruple, a tenfold increase, rose tenfold</i>; halve (<i>to halve, halved</i>). Approximation: <i>just over / just under / roughly / approximately / nearly / almost</i> 40 %. Fractions: <i>a quarter, a third, half, two thirds, the vast majority, a small minority</i> – e.g. <i>Mobile users account for <b>more than a third</b> of all visits.</i>" } },
  { t: "example", title: "Spotify subscribers, sentence by sentence", html: "Data (premium subscribers, millions, end of year, rounded): 2021: 180 · 2022: 205 · 2023: 236 · 2024: 263.<ul><li><b>Overall trend</b>: <i>Spotify's premium subscriber base <b>grew steadily</b> between 2021 and 2024.</i> → verb + adverb.</li><li><b>Start/end levels</b>: <i>It <b>rose from</b> 180 million <b>to</b> 263 million.</i> → from/to = levels.</li><li><b>Size of change</b>: <i>That is an increase <b>of</b> 83 million, or roughly 46 per cent.</i> → noun + <b>of</b>. With a verb: <i>It went up <b>by</b> 83 million.</i></li><li><b>Comparison</b>: <i>Subscribers were up 11 per cent <b>on</b> the previous year in 2024.</i></li><li><b>Forecast</b>: <i>Numbers are <b>expected to</b> keep climbing, but growth may <b>level off</b> as markets become saturated.</i></li></ul>Notice: “steadily” describes the regular yearly growth (about 25–30 million each year) – no year was a jump or a dip." },
  { t: "example", title: "Petrol prices: a bumpy line", html: "Imagine the price of a litre of petrol at Anna's local station over one year: Jan €1.62 · Mar €1.71 · Jun €1.95 · Aug €1.88 · Oct €1.60 · Dec €1.61.<ul><li>Jan–Mar: <i>Prices <b>climbed gradually</b>.</i> (small, steady rise)</li><li>Mar–Jun: <i>They then <b>soared</b> to €1.95, <b>peaking at</b> almost two euros in June.</i> (strong rise + top point, preposition <b>at</b>)</li><li>Jun–Aug: <i>There was a <b>slight dip</b> to €1.88.</i> (small, temporary fall)</li><li>Aug–Oct: <i>Prices <b>slumped</b> by 28 cents.</i> (sudden large fall, size with <b>by</b>)</li><li>Oct–Dec: <i>They <b>levelled out</b> at around €1.60.</i> (stable)</li></ul>Summary sentence: <i>Overall, petrol prices <b>fluctuated</b> considerably, but ended the year almost exactly where they had started.</i>" },
  { t: "hint", title: "Typical German mistake: rise or raise?", html: "German has <i>steigen</i> and <i>erhöhen</i>; English has <b>rise</b> (by itself, no object: <i>Prices rose</i>) and <b>raise</b> (someone raises something: <i>The petrol station raised prices</i>). Wrong: <i>Prices raised by 5 %.</i> ✗ – Right: <i>Prices rose by 5 %.</i> Memory trick: r<b>ai</b>se needs an <b>a</b>ctor (somebody does it)." },
  { t: "hint", title: "“increased of” – the preposition trap", html: "German says <i>um 5 % gestiegen</i> and <i>ein Anstieg von 5 %</i>. In English: verb + <b>by</b> (<i>increased by 5 %</i>), noun + <b>of</b> (<i>an increase of 5 %</i>), and what grows takes <b>in</b> (<i>an increase in sales</i>). ✗ <i>increased of 5 %</i>, ✗ <i>an increase of sales</i>." },
  { t: "hint", title: "Don't double up", html: "Strong verbs already contain the strength: <i>soar, plummet, slump, skyrocket</i>. So ✗ <i>soared dramatically</i> sounds clumsy. Use either a neutral verb + strong adverb (<i>rose dramatically</i>) or a strong verb alone (<i>soared</i>). Also: <i>slightly</i> + <i>slump</i> is a contradiction – a slump is always big." }
];
D["e1-2"] = [
  { t: "text", h: "Vertiefung: describing a chart step by step", levels: {
    simple: "A chart description has four steps: 1) Say what the chart shows (topic, unit, years, source). 2) Give the big picture in one sentence. 3) Describe the most important changes with numbers. 4) Finish with a short summary. Don't read out every number – choose the interesting ones: start, end, highest, lowest and any sudden change.",
    normal: "<b>1. Introduction</b> – chart type + topic + unit + period + source: <i>The line graph, taken from Statista, shows Netflix's worldwide subscribers in millions from 2016 to 2025.</i><br><b>2. Overview</b> – the main trend: <i>Overall, the number of subscribers more than tripled.</i><br><b>3. Details</b> – 3–5 key points with exact figures and strong verbs: <i>Between 2019 and 2020 subscribers jumped from 167 to 204 million – one of the biggest annual increases, probably due to the lockdowns. In 2021 and 2022, however, growth slowed considerably, with only about 9 million new subscribers in 2022.</i><br><b>4. Conclusion</b> – sum up or interpret: <i>In short, after a brief slowdown, Netflix has returned to strong growth.</i><br><b>Chart vocabulary</b>: <i>line graph, bar chart, pie chart, table, the x-axis / y-axis (horizontal / vertical axis), the legend</i> (Legende), <i>a segment</i> (of a pie), <i>a column / bar</i>. Comparison phrases: <i>higher than, twice as high as, whereas, while, in contrast to, by comparison, the biggest increase was in …</i>.",
    technical: "<b>Choosing the chart type</b>: line graph → development over time; bar chart → comparison of categories (or a few time points); pie chart → shares of one whole (must add up to 100 %). <b>Percentage vs. percentage points</b>: if a market share falls from 20 % to 18 %, it falls by <b>2 percentage points</b>, which is a relative fall of <b>10 per cent</b> (2/20). <b>Calculating change</b>: relative change = (new − old) / old × 100. 30 → 45 = +15/30 = +50 %. Going back down from 45 to 30 is −15/45 = −33 % (not −50 %!). <b>Hedging interpretations</b>: data shows what happened, not why. Use <i>probably, this may be due to, one possible reason is</i>. <b>Number style</b>: <i>203.66 million</i> (decimal point, not comma), <i>1,500</i> (comma for thousands) – the opposite of German usage." } },
  { t: "example", title: "Model answer: IT support tickets (bar chart)", html: "Data: Hardware 420 → 390 · Software 510 → 560 · Network 380 → 400 · Other 90 → 100 (2025 → 2026).<br><i><b>[Intro]</b> The bar chart compares the number of IT support tickets by category in 2025 and 2026. <b>[Overview]</b> Software was the largest category in both years and also saw the biggest increase. <b>[Details]</b> Software tickets rose by 50, from 510 to 560, an increase of almost 10 per cent. Network tickets went up slightly to 400, and “Other” remained the smallest category at around 100. In contrast, hardware tickets fell by 30 to 390, the only decrease. <b>[Conclusion]</b> Overall, the total rose moderately from 1,400 to 1,450, mainly because of software problems.</i><br>Check the mapping: intro = chart type + topic + period; overview = biggest category and biggest change; details = numbers with <b>by/from/to</b>; conclusion = total." },
  { t: "example", title: "Percentage points in daily life", html: "Your phone battery shows <b>40 %</b>. After an hour of video it shows <b>30 %</b>. It dropped by <b>10 percentage points</b> – but relative to what you had, you lost <b>25 per cent</b> of your remaining charge (10/40).<br>Same in business: <i>“iPlus's market share dropped from 20 % to 18 %”</i> = <i>a fall of 2 percentage points</i> = <i>iPlus lost a tenth (10 %) of its share</i>. Journalists often mix these up; in the exam you should not." },
  { t: "hint", title: "German number format", html: "German: <i>1.500,75 €</i>. English: <b>€1,500.75</b> – comma for thousands, point for decimals. Say “two point five per cent”, not “two comma five”. Also: <i>per cent</i> (BrE) / <i>percent</i> (AmE) – both fine, but be consistent." },
  { t: "hint", title: "Exam trick: select, don't list", html: "Examiners want the <b>significant</b> points: start, end, highest, lowest, sudden changes and crossing points (when one line overtakes another). A list like “2016: 89, 2017: 110, 2018: 139 …” shows no language skills. Group years together: <i>Between 2016 and 2019 subscribers almost doubled.</i>" },
  { t: "hint", title: "Which tense?", html: "<b>Past simple</b> for finished years (<i>rose in 2018</i>), <b>present perfect</b> for “up to now” (<i>has risen since 2021</i>), <b>present simple</b> for the chart itself (<i>The graph shows …</i>). German speakers often use the present perfect for finished years (<i>has risen in 2018</i> ✗) because German <i>ist gestiegen</i> works for both." }
];
})();

/* ===== World 2: Presenting ===== */
(function () {
var D = window.STUDYOS_DEEP["eng3"];
D["e2-1"] = [
  { t: "text", h: "Vertiefung: the structure behind presentation phrases", levels: {
    simple: "A presentation is like a guided tour. First you say <b>where we are going</b> (purpose and outline). On the way you say <b>where we are now</b> (signposting: “Let's move on to …”). You point at pictures (“As you can see …”). At the end you say <b>what we have seen</b> (summary). Linking words like <i>however</i> and <i>therefore</i> connect your ideas so the audience can follow.",
    normal: "Listeners cannot scroll back like readers. That is why spoken English uses much more <b>signposting</b> (Wegweiser-Sätze) than written English. A clear talk has five stages, each with typical phrases:<ol><li><b>Opening & purpose</b>: <i>Good morning, everyone. Today I'd like to talk about … · The aim of my talk is to …</i></li><li><b>Outline</b>: <i>I've divided my talk into three parts. First, … Then, … Finally, …</i></li><li><b>Signposting</b> between parts: <i>Let's move on to … · This brings me to my next point. · So much for X – let's now turn to Y.</i></li><li><b>Referring to visuals</b>: <i>As you can see in this drawing … · Take a look at … · On the left you can see …</i></li><li><b>Summary & close</b>: <i>To sum up … · Let's recap … · I'd like to conclude by emphasizing … · Thank you for your attention. Are there any questions?</i></li></ol><b>Linking words</b> show the logic: <b>result</b> (<i>therefore, consequently, as a result</i>), <b>contrast</b> (<i>however, although, in spite of, whereas</i>), <b>addition</b> (<i>moreover, in addition, not only … but also</i>). Grammar matters: <i>although</i> + clause (<i>although it was expensive</i>), but <i>in spite of / despite</i> + noun or -ing (<i>in spite of the cost / despite being expensive</i>).",
    technical: "<b>Rhetorical devices</b> make a talk memorable: <b>rhetorical questions</b> (<i>So how will this affect us?</i>), the <b>rule of three</b> (<i>faster, cheaper, better</i>), <b>direct address</b> (<i>For IT experts like yourselves …</i>), and <b>contrast</b> (<i>Not more data – better data.</i>). <b>Handling questions</b>: <i>That's a good question. · If I understand you correctly, you're asking … · I'm afraid I don't have the figures with me, but I can send them to you.</i> <b>Cue cards</b> with keywords only force you to speak freely – this sounds more natural and keeps eye contact. Write one card per drawing, 3–5 keywords, and the transition phrase to the next part. <b>Register</b>: avoid German fillers like “So, …” at the start of sentences (English <i>so</i> = result: <i>It was raining, so we stayed in</i>). Use <i>Right, … / OK, … / Now, …</i> instead. Also avoid “At the end” (= am Schluss einer Sache, örtlich) when you mean <i>In the end</i> (letztendlich) or <i>Finally</i>." } },
  { t: "example", title: "A 6-minute student podcast talk, phrase by phrase", html: "Lena presents the HBR IdeaCast episode about remote work.<ul><li><b>Purpose</b>: <i>“Good morning. Today I'd like to talk about why some remote teams work better than others.”</i></li><li><b>Outline</b>: <i>“I'll start with the main idea of the podcast, then show you three drawings, and finally we'll do a short activity.”</i></li><li><b>Visual</b>: <i>“As you can see in this first drawing, the team members are on islands …”</i></li><li><b>Signposting</b>: <i>“So much for the problem. Let's now move on to the solutions.”</i></li><li><b>Rhetorical question</b>: <i>“How many of you have been in a video call where nobody spoke?”</i></li><li><b>Linking</b>: <i>“Many teams use chat tools; <b>however</b>, they rarely talk about feelings. <b>As a result</b>, conflicts stay hidden.”</i></li><li><b>Summary</b>: <i>“To sum up, good remote teams communicate more, not less. I'd like to conclude by emphasizing one thing: …”</i></li></ul>" },
  { t: "example", title: "Linking words in a team meeting", html: "Tom reports on the new app release in the Monday team meeting:<br><i>“The beta test went well. <b>Moreover</b>, we got 300 sign-ups in the first week. <b>However</b>, the login crashed on older Android phones. <b>Although</b> we fixed the bug on Wednesday, some users left bad reviews. <b>In spite of</b> these reviews, our rating is still 4.2. <b>Therefore</b>, I suggest we launch next Monday.”</i><br>Mapping: <i>moreover</i> = addition · <i>however / although / in spite of</i> = contrast · <i>therefore</i> = result. Notice: <i>although</i> + full sentence; <i>in spite of</i> + noun." },
  { t: "hint", title: "German trap: “So, …”", html: "German <i>„So, jetzt kommen wir zu …“</i> becomes <b>“Right, now let's come to …”</b> or <b>“OK, let's move on to …”</b>. English <i>so</i> at the start of a sentence means <i>therefore</i> or introduces a conclusion. ✗ <i>So, I am Kevin.</i> → ✓ <i>Hi everyone, I'm Kevin.</i>" },
  { t: "hint", title: "although vs. in spite of", html: "<b>although</b> + subject + verb: <i>Although the app is free, few people use it.</i><br><b>in spite of / despite</b> + noun or -ing: <i>In spite of the free price … / Despite being free …</i><br>✗ <i>In spite of the app is free</i> – typical error. Also: <i>despite</i> without <i>of</i> (✗ <i>despite of</i>)." },
  { t: "hint", title: "Cue card recipe", html: "One card per drawing: <b>(1)</b> a big keyword for the main idea, <b>(2)</b> 2–3 supporting keywords or numbers, <b>(3)</b> the transition phrase in small letters at the bottom (<i>→ This brings me to …</i>). Never write full sentences – you will start reading and lose eye contact." }
];
D["e2-2"] = [
  { t: "text", h: "Vertiefung: why stories work and how to build one", levels: {
    simple: "People remember stories much better than facts. A good story has a <b>person</b> we care about, a <b>problem</b> (conflict) that creates tension, and an <b>ending</b> that changes something. Tell it with details, show feelings with your face and voice, make pauses, and let people talk in your story (“She said: ‘…’”).",
    normal: "A story is a <b>sequence of connected events</b> with <b>characters</b>, <b>tension</b> and a <b>conflict</b>. A simple and reliable structure has three acts:<ol><li><b>Setting</b> – who, where, when: <i>Last summer, I was working as a waiter in a busy café in Graz.</i></li><li><b>Conflict / turning point</b> – something goes wrong: <i>One Saturday the card terminal stopped working and forty guests wanted to pay.</i></li><li><b>Resolution + message</b> – what happened and what we learn: <i>We wrote bills by hand – and I learned that a backup plan is part of every IT system.</i></li></ol>The four classic <b>types of conflict</b>: person vs. <b>nature</b> (a storm cancels the trip), vs. <b>self</b> (fear of speaking in public), vs. <b>society</b> (rules, bureaucracy), vs. <b>person</b> (a difficult boss). <b>Techniques from the course</b>: dive straight into the story (no long introduction), paint a mental picture with specific details (<i>a cold Monday at 7 a.m.</i> instead of <i>once</i>), use <b>dialogue</b> instead of narration (<i>“Can you fix it?” my boss shouted.</i> instead of <i>My boss asked me to fix it</i>), include pauses before important moments, and show emotions with face, gestures and body language.",
    technical: "<b>Tenses in storytelling</b>: past simple for the main events (<i>the terminal crashed</i>), past continuous for the background (<i>I was carrying three plates when …</i>), past perfect for events before the story time (<i>I had never seen the boss so nervous</i>). Some speakers switch to the <b>historic present</b> for drama: <i>So I walk in, and there's my boss …</i> – fine in speech, but be consistent. <b>Reporting verbs</b> make dialogue lively: <i>shout, whisper, admit, complain, insist, mutter</i>. <b>Sensory language</b> (sight, sound, smell) builds the mental picture. In a business presentation, a story typically serves as a <b>hook</b> at the start or an <b>illustration</b> of a data point (<i>Behind this number is a real person – let me tell you about Maria</i>)." } },
  { t: "example", title: "Turning a boring report into a story", html: "<b>Report version</b>: <i>“Our customer support response time was too long, so we introduced a chatbot. Satisfaction improved by 20 %.”</i><br><b>Story version</b>: <i>“It's 11 p.m. on a Sunday. Maria, a nurse, has just finished her shift. Her online order is missing, and she types: ‘Where is my package?’ [<b>setting, character, specific details</b>] … Nothing. No answer until Tuesday. [<b>pause, tension</b>] On Tuesday she writes: ‘I'm never ordering from you again.’ [<b>dialogue, conflict: person vs. company</b>] That message changed our strategy. Today, Maria would get an answer in 30 seconds – and our satisfaction score is 20 per cent higher.” [<b>resolution + data</b>]</i><br>Same facts – but now the audience feels the problem." },
  { t: "example", title: "Your summer job story for an interview", html: "Interview question: <i>“Tell me about a time you solved a problem.”</i><br>Kevin answers with a mini story: <i>“Last August I <b>was working</b> [background, past continuous] at a supermarket checkout. One evening the scanner <b>stopped</b> [event, past simple] working and the queue <b>grew</b> to fifteen people. A customer <b>said</b>: ‘I've been waiting for twenty minutes!’ [dialogue] I <b>had seen</b> [past perfect] my manager enter codes manually before, so I <b>typed</b> in the product numbers and <b>called</b> a colleague to open a second till. Ten minutes later the queue <b>was</b> gone.”</i><br>Conflict: person vs. technology/time pressure. Message: stays calm, finds a practical solution." },
  { t: "hint", title: "Show, don't tell", html: "Instead of naming the emotion, show it: ✗ <i>I was very nervous.</i> → ✓ <i>My hands were shaking so much that I dropped my notes.</i> The audience then feels the emotion themselves. This is what “paint a mental picture” means." },
  { t: "hint", title: "German speakers: “since” vs. “for” in stories", html: "German <i>seit</i> = English <b>for</b> (duration: <i>for twenty minutes</i>) or <b>since</b> (starting point: <i>since 8 o'clock</i>). And use the present perfect continuous: ✗ <i>I wait since twenty minutes</i> → ✓ <i>I've been waiting for twenty minutes.</i>" },
  { t: "hint", title: "Exam trap", html: "The material says <b>dialogue, not narration</b>, and <b>communicate</b> emotions (not avoid them). Distractors often reverse the tips: “use narration”, “avoid pauses”, “keep details vague”. Remember the opposite of each is correct." }
];
})();

/* ===== World 3: Products & Markets ===== */
(function () {
var D = window.STUDYOS_DEEP["eng3"];
D["e3-1"] = [
  { t: "text", h: "Vertiefung: from target group to SWOT to research", levels: {
    simple: "Before you build an app, ask: <b>Who</b> will use it, and what do they love, value and know? Then check your idea with <b>SWOT</b>: what is good about it (Strengths), what is weak (Weaknesses) – both inside your team or product – and what chances (Opportunities) and dangers (Threats) come from the outside world. Finally, find facts: ask people yourself (<b>primary research</b>) or use data that already exists (<b>secondary research</b>).",
    normal: "<b>1. Target group</b> (Zielgruppe): describe users by <b>passions</b> (what they enjoy – gardening), <b>values</b> (what is important to them – family) and <b>experience</b> (their life situation – retirement). A gardening app for seniors might connect these: share photos of your vegetables with grandchildren.<br><b>2. SWOT analysis</b> – a 2×2 grid:<ul><li><b>Internal</b> (you can control it): <b>Strengths</b> (+) and <b>Weaknesses</b> (−) – features, team skills, budget, technology.</li><li><b>External</b> (you cannot control it): <b>Opportunities</b> (+) and <b>Threats</b> (−) – market trends, competitors, laws, technology changes.</li></ul>Test question: <i>“If our company disappeared tomorrow, would this factor still exist?”</i> Yes → external (O/T). No → internal (S/W).<br><b>3. Market research</b>: <b>primary</b> = new data you collect for this purpose (surveys, interviews, focus groups, observation, test marketing); <b>secondary</b> = data that already exists (government statistics, industry reports, competitor websites, your own sales figures). Secondary is cheaper and faster; primary is more specific and up to date.",
    technical: "A SWOT becomes useful only when you <b>combine</b> the quadrants (TOWS matrix): <b>SO</b> strategies use strengths to seize opportunities (offline mode + partnership with garden centres → in-store promotion); <b>WO</b> strategies fix weaknesses to use opportunities (no marketing know-how → partner with a seniors' association); <b>ST</b> strategies use strengths against threats (simple UI as differentiation against big-tech apps); <b>WT</b> strategies minimise both (small budget + new data rules → keep data collection minimal). <b>Vocabulary</b>: <i>a gap in the market</i> (Marktlücke), <i>a USP / unique selling point</i>, <i>a niche</i>, <i>to launch a product</i>, <i>a prototype</i>, <i>user-friendly</i>, <i>to roll out</i>, <i>a competitor</i> (Mitbewerber), <i>benchmarking</i> (comparing yourself with the best competitors), <i>a focus group</i> (6–10 people discussing a product with a moderator), <i>a questionnaire / survey</i>. Grammar: <i>research</i> is uncountable – ✗ <i>a research, researches</i> → ✓ <i>some research, a research project, a study</i>." } },
  { t: "example", title: "SWOT for a WG cleaning-plan app", html: "Kevin and two flatmates want to build <b>“FlatChores”</b>, an app that splits cleaning tasks in shared flats.<ul><li><b>Strength</b> (internal +): <i>Two of us study Business Informatics and can code the app ourselves.</i></li><li><b>Weakness</b> (internal −): <i>We have no money for advertising and only weekends to work on it.</i></li><li><b>Opportunity</b> (external +): <i>Rents are soaring, so more and more students live in shared flats.</i></li><li><b>Threat</b> (external −): <i>Free to-do apps like shared Google lists already exist.</i></li></ul><b>Research</b>: an online survey in three student WhatsApp groups = <b>primary</b>; Statistik Austria figures on students in shared flats = <b>secondary</b>.<br><b>SO strategy</b>: use our coding skills to build a free version quickly while demand grows." },
  { t: "example", title: "Gardening app for seniors – reading the categories", html: "<i>“Large, easy-to-read buttons”</i> → a feature of OUR product → internal → <b>Strength</b>.<br><i>“Growing number of senior smartphone users”</i> → happens in the market whether we exist or not → external → <b>Opportunity</b>.<br><i>“New data protection rules raise costs”</i> → a law from outside, negative → <b>Threat</b>.<br>A frequent confusion: <i>“Our app is cheaper than competitors”</i> is a <b>strength</b> (our price), but <i>“A competitor launches a cheaper app”</i> is a <b>threat</b> (their action)." },
  { t: "hint", title: "S/W inside, O/T outside", html: "Memory trick: the first two letters are about <b>us</b>, the last two about the <b>world</b>. If you cannot change it with a team decision, it is O or T. Trend words (growing, rising, new law, competitor) usually signal O/T." },
  { t: "hint", title: "German false friend: “the research”", html: "<i>Forschung / Recherche</i> is uncountable in English: ✗ <i>I did a research</i> → ✓ <i>I did some research</i> / <i>I carried out a survey</i>. Also: <i>to make a survey</i> ✗ → <b>to carry out / conduct a survey</b> ✓." },
  { t: "hint", title: "Primary or secondary? Ask one question", html: "<b>Did the data exist before my project started?</b> Yes → secondary (even your own company's old sales figures). No, I created it now → primary. Benchmarking is usually secondary because you compare existing information about competitors." }
];
})();

/* ===== World 4: Communication Style ===== */
(function () {
var D = window.STUDYOS_DEEP["eng3"];
D["e4-1"] = [
  { t: "text", h: "Vertiefung: the two axes behind DiSC", levels: {
    simple: "DiSC sorts behaviour with two questions. 1) Is the person <b>fast</b> (outgoing, quick decisions) or <b>slower</b> (careful, calm)? 2) Do they focus on <b>tasks</b> (results, facts) or <b>people</b> (relationships, feelings)? Fast + task = <b>D</b> (Dominance). Fast + people = <b>i</b> (influence). Slower + people = <b>S</b> (Steadiness). Slower + task = <b>C</b> (Conscientiousness). Everybody has all four, but usually one or two are strongest.",
    normal: "The model goes back to psychologist <b>William Moulton Marston</b> (book <i>Emotions of Normal People</i>, 1928). It describes observable <b>behaviour at work</b>, not intelligence, values or skills – and no style is better than another.<table><tr><th></th><th>Task-oriented</th><th>People-oriented</th></tr><tr><td><b>Faster-paced</b></td><td><b>D</b> – direct, decisive, results-driven, impatient. Fear: losing control.</td><td><b>i</b> – enthusiastic, talkative, optimistic, persuasive. Fear: rejection.</td></tr><tr><td><b>Slower-paced</b></td><td><b>C</b> – analytical, accurate, reserved, cautious. Fear: being wrong / criticism.</td><td><b>S</b> – patient, loyal, supportive, calm. Fear: sudden change, conflict.</td></tr></table><b>How to adapt</b> (“flexing”):<ul><li><b>D</b>: be brief, get to the point, offer options, talk about results.</li><li><b>i</b>: be friendly, allow small talk, show enthusiasm, give recognition.</li><li><b>S</b>: be patient, explain step by step, give time, show sincere interest, don't force quick decisions.</li><li><b>C</b>: give facts and data in writing, be precise, minimise socialising, set clear deadlines.</li></ul>",
    technical: "The lower-case <b>i</b> is a trademark convention of the DiSC brand (Wiley), not a typo. DiSC is a <b>self-report</b> instrument: you rate statements about yourself, so the result reflects your self-perception in a given context (many people score differently at work and at home). It is a communication tool, not a diagnostic or a hiring test – using it to select candidates is criticised because it was not designed for that. Typical adjectives for exams: D – <i>assertive, demanding, competitive, blunt</i>; i – <i>outgoing, charming, lively, spontaneous</i>; S – <i>reliable, cooperative, even-tempered, predictable</i>; C – <i>precise, systematic, perfectionist, sceptical</i>. Each style has a typical <b>question</b> it asks: D – <i>What?</i> (results), i – <i>Who?</i> (people involved), S – <i>How?</i> (process, stability), C – <i>Why?</i> (logic, evidence)." } },
  { t: "example", title: "One team meeting, four styles", html: "The student project team has to choose a database for their app.<ul><li><b>Marco (D)</b>: <i>“We've talked enough. PostgreSQL – decision made, let's start tomorrow.”</i> → fast, task, wants results.</li><li><b>Julia (i)</b>: <i>“Ooh, Firebase sounds cool, and my friend at Bitpanda loves it! Let's all go for pizza and discuss it.”</i> → fast, people, enthusiasm.</li><li><b>Stefan (S)</b>: <i>“Hmm, we used MySQL last semester and it worked fine. Do we really need to change?”</i> → slow, people, stability.</li><li><b>Lea (C)</b>: <i>“I made a spreadsheet comparing performance, cost and documentation. I need two more days to check the licence terms.”</i> → slow, task, accuracy.</li></ul><b>Adapting</b>: to convince Lea, send her the data in writing; for Stefan, explain how the migration will work step by step; for Marco, give two clear options; for Julia, show how the team will enjoy it." },
  { t: "example", title: "Student job interview: reading the interviewer", html: "Sophie applies for a part-time IT support job. The interviewer checks his watch, skips the small talk and asks: <i>“What can you do for us from day one?”</i> → probably a <b>D</b>. Sophie answers briefly: <i>“I can set up laptops, reset accounts and handle first-level tickets – I did 200 tickets in my last job.”</i><br>If the interviewer had asked many detailed questions about her procedures and read her CV line by line (<b>C</b>), a precise, structured answer with numbers and documentation would work better. A warm, chatty interviewer (<b>i</b>) would enjoy a short anecdote about a happy customer." },
  { t: "hint", title: "Two questions to classify any person", html: "<b>1. Fast or slow?</b> (speaks quickly, decides quickly, interrupts → fast). <b>2. Task or people?</b> (talks about results, data, deadlines → task; talks about feelings, team, others → people). Fast/task = D, fast/people = i, slow/people = S, slow/task = C. Clockwise from top left: <b>D – i – S – C</b>." },
  { t: "hint", title: "Exam trap: what DiSC measures", html: "DiSC measures <b>behaviour in the work environment</b> – not intelligence, technical skills, values or salary expectations. And no style is “best”: each has strengths and blind spots." },
  { t: "hint", title: "Vocabulary trap: “conscientious”", html: "Pronounced /ˌkɒnʃiˈenʃəs/ (“kon-shee-EN-shus”). It means <i>gewissenhaft</i> (careful and thorough), not <i>bewusst</i> (= <b>conscious</b>). ✗ <i>She is very conscious about details</i> → ✓ <i>She is very conscientious.</i>" }
];
})();

/* ===== World 5: Listening ===== */
(function () {
var D = window.STUDYOS_DEEP["eng3"];
D["e5-1"] = [
  { t: "text", h: "Vertiefung: the tools and barriers of active listening", levels: {
    simple: "Active listening means: you really try to understand the other person, and you <b>show</b> it. You repeat in your own words what you heard (“So you mean …”), you ask open questions (“What happened then?”), and you don't interrupt or give advice too early. You don't have to agree – you only show that you understood.",
    normal: "Active listening has three main tools:<ol><li><b>Restatement / paraphrasing</b> – say back the message in your own words: <i>So what you're saying is … · If I hear you correctly, your concern is … · In other words, …</i> Test: the speaker says <i>“Yes, exactly!”</i></li><li><b>Open-ended questions</b> – start with <i>what, how, why, tell me, could you describe</i>: <i>What kinds of changes have been hardest for you?</i> They invite explanation. <b>Closed questions</b> (<i>Is it hard? Did you finish?</i>) get yes/no and are useful only to check facts.</li><li><b>Non-verbal signals</b> – eye contact, nodding, an open posture, short sounds like <i>mm-hm, I see, right</i>.</li></ol><b>Barriers</b> that stop us listening:<ul><li><b>Physical</b>: noise, bad connection, fatigue, hunger, an uncomfortable room.</li><li><b>Emotional</b>: <b>red-flag words</b> that trigger anger (<i>“That's typical for IT people”</i>), prejudice against the speaker, stress, defensiveness.</li><li><b>Semantic</b>: words mean different things to different people – jargon, technical terms, false friends, abbreviations.</li></ul>Important: restatement shows <b>understanding, not agreement</b>. You can say <i>“So you feel the deadline is unrealistic”</i> and still keep the deadline.",
    technical: "Useful phrase bank. <b>Clarifying</b>: <i>What do you mean by …? · Could you give me an example? · Could you be more specific?</i> <b>Encouraging</b>: <i>Tell me more about that. · And then? · How did that make you feel?</i> <b>Reflecting feelings</b>: <i>It sounds like you're frustrated about … · You seem worried about …</i> <b>Summarising</b> (at the end of a longer exchange): <i>Let me see if I've got this right: there are three issues – …</i> Avoid the <b>“listening blockers”</b>: interrupting, finishing the other person's sentences, immediately giving advice (<i>“You should just …”</i>), comparing (<i>“That's nothing, when I …”</i>), and “Why” questions that sound accusing (<i>“Why did you do that?”</i> → better: <i>“What led to that decision?”</i>). Grammar note: <i>listen <b>to</b> somebody</i> (✗ <i>listen somebody</i>); <i>hear</i> = perceive sound, <i>listen</i> = pay attention." } },
  { t: "example", title: "Team meeting: a frustrated developer", html: "Nina, a developer, says in the stand-up: <i>“I'm fed up. Every time I start coding, someone pings me on Teams.”</i><br><b>Poor response</b>: <i>“Just turn off notifications.”</i> (advice too early) or <i>“We all get messages.”</i> (comparison).<br><b>Active listening</b>:<ul><li><b>Restatement</b>: <i>“So you're saying the constant messages make it hard to concentrate?”</i> → Nina: <i>“Exactly.”</i></li><li><b>Open question</b>: <i>“What kinds of messages interrupt you most?”</i> → <i>“Mostly small questions from sales that could wait.”</i></li><li><b>Clarifying</b>: <i>“Could you give me an example from today?”</i></li><li><b>Summary</b>: <i>“Let me see if I've got this right: the problem is non-urgent questions from sales during your focus time.”</i></li></ul>Only now does the team look for a solution (e.g. two “no-meeting” focus hours)." },
  { t: "example", title: "Barriers in a train call", html: "Kevin calls his project partner from the train to Graz. The connection keeps breaking up (<b>physical barrier</b>). His partner says <i>“the sprint review got moved”</i> – Kevin doesn't know what a “sprint review” is (<b>semantic barrier</b>). Then the partner adds <i>“Typical, you students never read the emails”</i> and Kevin gets annoyed and stops listening (<b>emotional barrier</b>, red-flag word “typical”).<br>Fix: call back later from a quiet place, ask <i>“What do you mean by sprint review?”</i>, and notice your own reaction before answering." },
  { t: "hint", title: "Open vs. closed: look at the first word", html: "Questions starting with <b>is, are, do, did, have, can, will</b> are usually closed (yes/no). Questions starting with <b>what, how, why, which</b> or <i>Tell me …</i> are open. Exception from the course: <i>“Could you give me an example?”</i> is technically yes/no, but it works as an open prompt." },
  { t: "hint", title: "German speakers: hear vs. listen", html: "<i>hören</i> = <b>hear</b> (sound reaches you, no effort); <i>zuhören</i> = <b>listen to</b> (you pay attention). ✗ <i>I listened a strange noise</i> → ✓ <i>I heard a strange noise.</i> ✗ <i>Listen me!</i> → ✓ <i>Listen to me!</i>" },
  { t: "hint", title: "Exam trap: understanding ≠ agreement", html: "If an answer option says restatement means “you agree with the speaker”, it is wrong. Restatement = confirming your understanding in your own words – to the speaker's satisfaction." }
];
D["e5-2"] = [
  { t: "text", h: "Vertiefung: gambits by function and politeness level", levels: {
    simple: "Gambits are small ready-made phrases that help a conversation run smoothly. You use them to agree (“Exactly!”), disagree politely (“I see your point, but …”), get thinking time (“Good question, let me think …”), change the topic (“By the way, …”) and end a conversation (“Anyway, I should get going.”). Learn them as fixed chunks – they make you sound fluent.",
    normal: "Native speakers rarely say a bare <i>“No”</i> or <i>“You're wrong”</i>. Gambits soften the message and keep the relationship friendly. Grouped by function:<ul><li><b>Agreeing</b> – strong: <i>I couldn't agree more. · Exactly! · Absolutely.</i> Partial: <i>I agree up to a point. · That's true, but …</i></li><li><b>Disagreeing politely</b>: <i>I see your point, but … · I'm not sure I agree. · That's an interesting point, although … · I'm afraid I see it differently.</i></li><li><b>Buying time</b>: <i>That's a good question. · Let me think … · Well, how can I put it … · That's a tough one …</i></li><li><b>Interrupting</b>: <i>Sorry to interrupt, but … · Can I just come in here?</i></li><li><b>Changing the topic</b>: <i>By the way, … · Speaking of …, · Oh, that reminds me …</i></li><li><b>Returning to the topic</b>: <i>Anyway, getting back to … · As I was saying …</i></li><li><b>Ending</b>: <i>Anyway, I should be going. · It was nice talking to you. · Let's catch up again soon.</i></li></ul>",
    technical: "Many gambits work through <b>“yes, but”</b> structure: first acknowledge (<i>I see your point / That's true</i>), then add the contrast (<i>but / although / however</i>). This protects the other person's “face” (their public self-image). Note the <b>ironic negative</b>: <i>I couldn't agree more</i> = I agree completely (German speakers sometimes misread it as disagreement). Conversely, <i>“With all due respect, …”</i> and <i>“I hear what you're saying”</i> often announce strong disagreement in British English. Intonation matters: <i>“Right.”</i> with a falling tone = agreement; with a long, rising-falling tone it can sound sceptical. Fillers like <i>well, actually, you know</i> are also gambits – use them sparingly in presentations." } },
  { t: "example", title: "A team meeting with gambits", html: "Topic: should the team move the release date?<br><b>Anna</b>: <i>“I think we should release on Friday.”</i><br><b>Ben</b>: <i>“<b>I see your point, but</b> the payment module isn't tested yet.”</i> → polite disagreement<br><b>Anna</b>: <i>“<b>That's true.</b> How long would testing take?”</i> → partial agreement<br><b>Ben</b>: <i>“<b>That's a tough one … let me think.</b> Probably three days.”</i> → buying time<br><b>Carla</b>: <i>“<b>I couldn't agree more</b> with Ben – quality first.”</i> → strong agreement<br><b>Ben</b>: <i>“<b>Oh, that reminds me</b> – did anyone update the privacy policy?”</i> → changing topic<br><b>Anna</b>: <i>“<b>Anyway, getting back to</b> the date: Tuesday then?”</i> → returning<br><b>Carla</b>: <i>“Perfect. <b>I should be going</b> – I have a lecture. <b>Let's catch up</b> tomorrow.”</i> → ending" },
  { t: "example", title: "Small talk at a career fair", html: "Kevin meets a recruiter at a stand. Recruiter: <i>“So why do you want to work in IT consulting?”</i> Kevin: <i>“<b>Well, that's a good question.</b> I think …”</i> (time to think). Later: <i>“<b>Speaking of</b> projects, do you also work with SAP?”</i> (topic change). At the end: <i>“<b>It was really nice talking to you.</b> Could I have your card?”</i> (polite exit). Without gambits, the answers would sound abrupt or the conversation would stop awkwardly." },
  { t: "hint", title: "German trap: “I am agree”", html: "<i>Ich bin einverstanden</i> → ✗ <i>I am agree</i> → ✓ <b>I agree</b> (agree is a verb!). Negative: ✓ <i>I don't agree / I disagree</i>. And ✗ <i>I'm with you agree</i> → ✓ <i>I agree with you.</i>" },
  { t: "hint", title: "“I couldn't agree more” = 100 % yes", html: "It means “it is impossible to agree more than I do”. Don't confuse it with <i>I couldn't agree</i> (= I didn't agree). In exams it is always <b>agreeing</b>." },
  { t: "hint", title: "Recognise by the key word", html: "<b>but / although / not sure</b> → disagreeing · <b>think / question / put it / tough</b> → buying time · <b>by the way / speaking of / reminds me</b> → changing topic · <b>anyway / going / catch up</b> → ending · <b>exactly / absolutely / more</b> → agreeing." }
];
D["e5-3"] = [
  { t: "text", h: "Vertiefung: why I-messages work – and how to build them", levels: {
    simple: "A <b>you-message</b> attacks: “You always come late!” The other person defends themselves and stops listening. An <b>I-message</b> talks about your own feeling and need: “I feel stressed when meetings start late, because I have a lecture afterwards. Could we start on time?” Nobody is blamed, so it's easier to find a solution.",
    normal: "The formula has three (plus one) parts:<ol><li><b>Feeling</b>: <i>I feel / I'm …</i> + a real emotion (<i>frustrated, worried, stressed, disappointed, confused, nervous, relieved, happy</i>).</li><li><b>Behaviour</b> – a neutral, observable description, no blame: <i>when the meeting starts 20 minutes late</i> (not <i>when you're so unreliable</i>).</li><li><b>Reason / need</b>: <i>because I need … / because I have …</i></li><li><b>Request</b> (optional but helpful): <i>Could we … ? / I'd appreciate it if … / Would it be possible to … ?</i></li></ol><b>Disguised judgments</b> are the most common error. Words like <i>ignored, attacked, manipulated, betrayed, misunderstood, criticised, left out</i> look like feelings but really describe what the other person did. <i>I feel that you …</i> or <i>I feel like you …</i> is always a judgment, not a feeling. Compare: <i>I feel ignored</i> (accusation) → <i>I feel lonely / hurt</i> (feeling). Also avoid absolutes: <i>always, never, every time</i> – they are rarely true and invite a counter-attack.",
    technical: "The concept comes from psychologist <b>Thomas Gordon</b> (<i>Parent Effectiveness Training</i>, 1970s) and is related to Marshall Rosenberg's <b>Nonviolent Communication</b> (observation – feeling – need – request). The grammar of politeness supports it: conditional and modal forms (<i>I'd appreciate it if you could …, Would you mind …-ing …?</i>) are softer than imperatives. Note the patterns: <i>I'd appreciate <b>it</b> if you <b>could</b> …</i> (the “it” is needed), <i>Would you mind <b>sending</b> …?</i> (+ -ing), <i>I'd like you <b>to</b> send …</i> (+ to-infinitive, ✗ <i>I'd like that you send</i>). In professional e-mails, “I” can also become <b>“we”</b> to share responsibility: <i>We may need to look at the timeline together.</i>" } },
  { t: "example", title: "WG kitchen: from attack to request", html: "Lisa's flatmate leaves dirty dishes in the sink for days.<br><b>You-message</b>: <i>“You're so lazy, you never clean up!”</i> → judgment (lazy) + absolute (never) → flatmate defends himself.<br><b>I-message</b>: <i>“<b>I feel annoyed</b> [feeling] <b>when the dishes stay in the sink for three days</b> [neutral behaviour, specific], <b>because I need the space to cook</b> [need]. <b>Could we agree</b> to wash up the same evening?” [request]</i><br>Check: no “you are …”, a real emotion, an observable fact (three days), a clear wish." },
  { t: "example", title: "Team project: a missing report", html: "Max promised the market analysis for Monday; on Wednesday it's still missing.<br>✗ <i>“You did a horrible job with the deadline.”</i><br>✗ <i>“I feel you don't care about this project.”</i> (disguised judgment – “I feel you …”)<br>✓ <i>“<b>I'm worried</b> because the market analysis isn't in the folder yet, and <b>I need it</b> to finish the SWOT by Friday. <b>Would it be possible</b> to send me a first draft tomorrow? <b>I'd appreciate it</b> if you could tell me if something is blocking you.”</i><br>The last sentence opens the door for Max to explain – maybe he was ill." },
  { t: "hint", title: "The “that/like” test", html: "If the word <b>that</b> or <b>like</b> follows <i>I feel</i>, it is a thought, not a feeling: <i>I feel <b>that</b> you're unfair</i> = <i>I think you're unfair</i>. A real feeling follows directly: <i>I feel <b>frustrated</b></i>." },
  { t: "hint", title: "German trap: “I'd like that you …”", html: "German: <i>Ich möchte, dass du …</i> → ✗ <i>I'd like that you call me</i> → ✓ <b>I'd like you to call me</b> or <b>I'd appreciate it if you could call me</b>. Same with <i>want</i>: ✓ <i>I want you to …</i>" },
  { t: "hint", title: "Exam recipe in 3 steps", html: "1) Replace “you are/did …” with a feeling word (worried, frustrated, stressed). 2) Describe the behaviour with facts (time, number, situation). 3) Add “because I need …” + a polite request (“Could we …?”). Remove <i>always/never</i>." }
];
})();

/* ===== World 6: Ethics at Work ===== */
(function () {
var D = window.STUDYOS_DEEP["eng3"];
D["e6-1"] = [
  { t: "text", h: "Vertiefung: the case, the ethics and the language of sales", levels: {
    simple: "The story: during a recession, Bluebird Publications sells advertising space by phone. Team leader Rob is usually the best, but now he sells almost nothing. The new guy, Duncan, sells a huge advert to Paxham's – a company that normally never buys adverts. Later Paxham's calls again; Rob takes the call on Duncan's phone and says the commission is his. Is that fair? You have to discuss what Duncan should do.",
    normal: "<b>Key facts</b>: Bluebird sells advertising space in magazines by telephone (<b>telesales</b>). Salespeople earn a <b>commission</b> (Provision) on each sale. Because of the <b>recession</b>, companies cut advertising budgets. Duncan Black, a new recruit, closes a big deal with <b>Paxham's Menswear</b>, an <b>up-market</b> clothing chain whose <b>corporate policy</b> was never to buy advertising space. Rob Grewal, team leader, argues that everybody had been <b>softening up</b> Paxham's for years, so the commission should be shared. Then Paxham's places a <b>repeat order</b>; Rob takes it on Duncan's phone and claims the commission himself.<br><b>The ethical question</b>: who deserves the reward – the person who closed the deal, or the team that prepared it? And is it acceptable for a leader to use his position to take a junior's income?<br><b>Five courses of action</b> for Duncan:<ol><li><b>Confrontation</b> – talk to Rob directly.</li><li><b>Go straight to the top</b> – report it to a senior manager.</li><li><b>Ignore the problem</b> – say nothing to keep the peace.</li><li><b>Get something for yourself</b> – ask for something in return (e.g. future leads).</li><li><b>Compromise</b> – Rob and Duncan share the commission.</li></ol>",
    technical: "<b>Language for discussing options</b>: <i>If Duncan confronts Rob, he <b>might</b> damage the relationship.</i> (first conditional for realistic options) · <i>If I <b>were</b> Duncan, I <b>would</b> go straight to the top.</i> (second conditional for advice) · <i>Rob <b>shouldn't have</b> taken the call.</i> (criticising the past) · <i>The main advantage / drawback of this option is …</i> · <i>On the one hand … on the other hand …</i>. <b>Ethics vocabulary</b>: <i>fair / unfair, to take credit for something</i> (sich mit fremden Federn schmücken), <i>to abuse one's position</i>, <i>a conflict of interest</i>, <i>to blow the whistle</i> (Missstände melden), <i>a grey area</i>, <i>integrity</i>, <i>accountability</i>. <b>Sales vocabulary</b>: <i>a lead</i> (potential customer), <i>a cold call</i>, <i>to close / clinch / land a deal</i>, <i>a repeat order</i>, <i>a sales target / quota</i>, <i>to meet / miss a target</i>, <i>commission-based pay</i>." } },
  { t: "example", title: "Same dilemma, your student job", html: "Kevin works at an electronics store and earns 2 % commission on sales. A customer spends an hour with Kevin asking about laptops, then says he'll come back. The next day Kevin's colleague Mario serves the same customer, who buys a €1,500 laptop – Mario gets the €30 commission.<br>Mapping to the case: Kevin = the people who <b>softened up</b> the customer (like Rob's team claims); Mario = the one who <b>closed the deal</b> (like Duncan).<br>Possible courses of action: <b>confrontation</b> (<i>“Mario, I think we should talk about yesterday's customer”</i>), <b>go to the top</b> (ask the store manager about the rules), <b>compromise</b> (split: €15 each). A clear <b>corporate policy</b> (e.g. “commission goes to whoever is named on the receipt”) would prevent the conflict." },
  { t: "example", title: "Arguing for one option (model paragraph)", html: "<i>“<b>If I were</b> Duncan, I <b>would</b> first talk to Rob privately. <b>On the one hand</b>, a confrontation is uncomfortable, and Rob is his team leader. <b>On the other hand</b>, if Duncan ignores the problem, Rob <b>might</b> do it again. <b>The main advantage</b> of a private talk is that Rob can save face. If that doesn't work, Duncan <b>should</b> go straight to the top, because Rob <b>abused his position</b> and <b>took credit for</b> Duncan's client.”</i><br>Structure: recommendation (2nd conditional) → pros/cons → consequence (might) → fallback option." },
  { t: "hint", title: "False friend: “provision”", html: "German <i>Provision</i> = English <b>commission</b>. English <i>provision</i> means <i>Bereitstellung / Vorkehrung</i> (the provision of services). Also: <i>Kommission</i> (a committee) = <b>commission</b> too – context decides." },
  { t: "hint", title: "German trap: “If I would be …”", html: "✗ <i>If I would be Duncan, I would …</i> → ✓ <b>If I were Duncan, I would …</b> Never put <i>would</i> in the if-clause. <i>were</i> is used for all persons in advice (<i>If I were you</i>)." },
  { t: "hint", title: "Get the facts straight", html: "Exam questions check who did what. <b>Duncan</b>: made the Paxham's sale, should get that commission, his client placed the new order. <b>Rob</b>: took the new order on the phone and claims the commission. Rob's argument for splitting: the team had been softening up Paxham's for years." }
];
})();

/* ===== World 7: Companies ===== */
(function () {
var D = window.STUDYOS_DEEP["eng3"];
D["e7-1"] = [
  { t: "text", h: "Vertiefung: liability, ownership and the Tesco story", levels: {
    simple: "Companies differ in <b>who owns them</b> and <b>who pays if things go wrong</b>. A <b>sole trader</b> is one person – if the business has debts, she pays with her private money (unlimited liability). In a <b>limited company</b> (Ltd or plc), owners lose only the money they invested (limited liability). A <b>plc</b> can sell shares to anyone on the stock exchange; an <b>Ltd</b> cannot. A <b>non-profit</b> uses its money for a mission, and a <b>public corporation</b> belongs to the state.",
    normal: "<b>Key concepts</b>:<ul><li><b>Liability</b> (Haftung): <b>unlimited</b> = the owner's private property (car, flat, savings) can be used to pay business debts; <b>limited</b> = shareholders risk only their investment.</li><li><b>Legal entity / legal person</b> (juristische Person): the company itself can sign contracts, sue and be sued, separate from its owners.</li><li><b>Shares</b> (Aktien/Anteile) and <b>shareholders</b>: owners of part of the company.</li></ul><table><tr><th>Type</th><th>Owner(s)</th><th>Liability</th><th>Shares</th><th>Austrian equivalent</th></tr><tr><td>Sole trader</td><td>1 person</td><td>unlimited</td><td>none</td><td>Einzelunternehmen</td></tr><tr><td>Private limited (Ltd)</td><td>private shareholders</td><td>limited</td><td>not sold publicly</td><td>GmbH</td></tr><tr><td>Public limited (plc)</td><td>public shareholders</td><td>limited</td><td>traded on stock exchange</td><td>AG (listed)</td></tr><tr><td>Non-profit</td><td>members / trustees</td><td>usually limited</td><td>none</td><td>Verein, gemeinnützige GmbH</td></tr><tr><td>Public corporation</td><td>the state</td><td>state</td><td>none</td><td>e.g. state-owned railway</td></tr></table>The course material gives minimum share capital of €35,000 (Ltd) and €50,000 (plc). In reality this depends on the country: a UK Ltd needs no minimum, a UK plc £50,000; an Austrian GmbH €10,000 (since 2024), an AG €70,000.",
    technical: "<b>Confusion alert</b>: a <b>public limited company</b> (plc) is PRIVATELY owned by the public (investors), while a <b>public corporation</b> is owned by the STATE. “Public” means different things. <b>Going public</b> = an IPO (initial public offering), when an Ltd becomes a plc and lists its shares. <b>Tesco case vocabulary</b>: Tesco began in 1919 as Jack Cohen's market stall in London's East End and grew into one of the world's largest <b>retailers</b> by selling at <b>rock-bottom prices</b> and opening many <b>outlets</b>. Useful verbs: <i>to flourish</i> (grow successfully), <i>to expand into</i> new markets, <i>to set up a subsidiary</i> (a company owned by a <b>parent company</b>), <i>to be a takeover target</i> (another firm wants to buy it), <i>to merge with</i>. Adjective <i>volatile</i> = changing suddenly (volatile markets, volatile share price). <i>Premises</i> is always plural: <i>on the premises</i> (auf dem Firmengelände)." } },
  { t: "example", title: "Five ways to run a coffee business", html: "<ul><li><b>Sole trader</b>: Sarah sells coffee from a van at the FH campus under her own name. When the van breaks down and she owes €8,000, the bank can take her private savings → <b>unlimited liability</b>.</li><li><b>Ltd</b>: Sarah and her brother found “CampusCoffee GmbH/Ltd”, each investing money. If it goes bankrupt, they lose their investment but not their flat → <b>limited liability</b>, shares held privately.</li><li><b>plc</b>: years later, CampusCoffee <b>goes public</b>; anyone can buy its shares on the Vienna Stock Exchange.</li><li><b>Non-profit</b>: a student association runs a café; all surplus goes to scholarships; volunteers serve, a paid manager organises.</li><li><b>Public corporation</b>: the coffee bar on a state-owned train, run by a company the government owns.</li></ul>" },
  { t: "example", title: "Tesco in sentences", html: "<i>Tesco is a British <b>retailer</b> that started as a market stall in 1919. Its business <b>flourished</b> because it offered <b>rock-bottom prices</b>. Today it has thousands of <b>outlets</b>, and it has <b>set up subsidiaries</b> in other countries. In a <b>volatile</b> market, even a large retailer can become a <b>takeover target</b>.</i><br>Each bold term = one vocabulary pair from the lesson. Retelling a case in 5–6 sentences like this is a good way to learn the words in context." },
  { t: "hint", title: "“public” has two meanings", html: "<b>Public limited company</b> = shares sold to the public (owned by investors). <b>Public corporation / public sector</b> = owned by the state. Exam distractors love this. Memory trick: <b>plc</b> → stock <b>market</b>; <b>public corporation</b> → <b>government</b>." },
  { t: "hint", title: "German false friends", html: "<i>Firma</i> → <b>company/firm</b> (not “firma”). <i>Aktie</i> → <b>share</b> (BrE) / <b>stock</b> (AmE) – ✗ <i>action</i>. <i>Gesellschafter</i> → <b>shareholder/partner</b>. <i>Haftung</i> → <b>liability</b>. <i>Konkurs/Insolvenz</i> → <b>bankruptcy / insolvency</b>; <i>to go bankrupt</i>." },
  { t: "hint", title: "Decision path for exam items", html: "1) State owns it? → public corporation. 2) Mission instead of profit, volunteers? → non-profit. 3) One person, unlimited liability? → sole trader. 4) Shares on the stock exchange? → plc. 5) Otherwise, limited liability with private shareholders → Ltd." }
];
})();

/* ===== Prep chapter: exam preparation ===== */
(function () {
var D = window.STUDYOS_DEEP["eng3"];
D["exx-1"] = [
  { t: "text", h: "Vertiefung: writing a full chart description under exam conditions", levels: {
    simple: "In the exam you write a longer description of a chart. Plan for two minutes first: circle the start, the end, the highest and lowest points and where lines cross. Then write four short paragraphs: what the chart is (with source), the big trend, the details with numbers, and a final sentence. Use past tense for past years and vary your verbs.",
    normal: "<b>Planning (2–3 min)</b>: mark start values, end values, the maximum, the minimum, the biggest jump/fall, and any <b>crossing point</b> (where one line overtakes the other). That is your content – nothing else.<br><b>Writing</b> – useful sentence frames:<ul><li><b>Source</b>: <i>The line graph, taken from an article titled “…”, published on [date] on [website], illustrates …</i></li><li><b>Overview</b>: <i>Overall, X remained ahead of Y throughout the period, although the gap narrowed / widened.</i></li><li><b>Crossing point</b>: <i>In 2018, X overtook Y for the first time.</i> / <i>Y fell behind X.</i></li><li><b>Gap</b>: <i>The gap between X and Y narrowed from 8.1 to 4.7 percentage points.</i></li><li><b>Parallel development</b>: <i>Both services grew steadily, with X slightly ahead.</i></li><li><b>Contrast</b>: <i>While X rose sharply, Y fell considerably.</i> / <i>X jumped by 25 points, whereas Y dropped by 10.</i></li></ul><b>Variety checklist</b>: at least five different verbs, three adverbs, one noun phrase (<i>a sharp rise in …</i>), one comparison, one approximation (<i>just under / roughly</i>).",
    technical: "<b>Narrow/widen</b> (the gap): <i>The gap narrowed</i> = the difference got smaller (Abstand verringerte sich), <i>widened</i> = got bigger; <i>to close the gap on someone</i> = catch up. <b>Overtake / surpass / outstrip</b> = go above a competitor. <b>Time phrases</b>: <i>over the period, throughout, in the following year, by 2023</i> (= no later than; <i>by 2023 it had reached …</i> – past perfect!), <i>between 2019 and 2021</i>, <i>from then on</i>. <b>Headline grammar</b> (also tested): present simple = past event (<i>Shares fall</i>), <i>to</i> + infinitive = future (<i>Firm to cut jobs</i>), past participle = passive (<i>100 jobs cut</i>), articles and the verb <i>be</i> are dropped. When explaining a headline, rebuild a full sentence with articles and the correct tense, and paraphrase the key idiom." } },
  { t: "example", title: "Model description (fictional data: music streaming in a WG survey)", html: "Data (% of 200 students using each service, fictional): Spotify 2021: 70 · 2022: 66 · 2023: 64 – YouTube Music 2021: 20 · 2022: 38 · 2023: 52.<br><i><b>[Intro]</b> The line graph, based on a fictional survey of 200 students, shows the percentage using Spotify and YouTube Music between 2021 and 2023. <b>[Overview]</b> Spotify remained the market leader throughout the period, but YouTube Music closed the gap dramatically. <b>[Details]</b> In 2021, Spotify was used by 70 % of students, compared with only 20 % for YouTube Music – a gap of 50 percentage points. Over the next two years Spotify declined gradually to 64 %, whereas YouTube Music more than doubled, soaring to 52 %. As a result, the gap narrowed to just 12 points. <b>[Conclusion]</b> If this trend continues, YouTube Music may overtake Spotify in the near future.</i><br>Mapping: <b>gap / narrowed / closed the gap</b> = comparison language; <b>percentage points</b> = difference between two percentages; <b>may</b> = careful forecast." },
  { t: "example", title: "Explaining two headlines in your own words", html: "<b>“Petrol prices to soar as oil supply slumps”</b> → <i>Petrol prices are expected to rise very quickly <b>(to soar = future)</b> because the supply of oil is falling sharply <b>(slumps = is falling suddenly and strongly)</b>.</i><br><b>“Spotify shares take a hit after subscriber growth slows”</b> → <i>The value of Spotify's shares has fallen <b>(take a hit = be negatively affected)</b> because the number of new subscribers is growing more slowly than before.</i><br>Recipe: full sentence + articles + correct tense + explanation of the idiom in brackets or in simpler words." },
  { t: "hint", title: "German trap: “the last years”", html: "<i>in den letzten Jahren</i> → ✓ <b>in recent years / over the last few years</b> + present perfect (<i>has grown</i>). ✗ <i>in the last years it grew</i>. And <i>im Vergleich zu</i> → <b>compared with/to</b>, ✗ <i>in comparison of</i>." },
  { t: "hint", title: "Always name the source", html: "Losing points for a missing source is the easiest mistake to avoid. Write it into your first sentence: <i>“The graph, taken from [title], published on [date] on [website], shows …”</i> Then you cannot forget it." },
  { t: "hint", title: "Gap language", html: "<b>gap</b> (Abstand) + <b>narrow</b> (kleiner werden) / <b>widen</b> (größer werden). <b>close the gap on</b> = aufholen. <b>overtake</b> = überholen. One correct gap sentence shows the examiner that you compare, not just list." }
];
D["exx-2"] = [
  { t: "text", h: "Vertiefung: politeness strategies and more confusables", levels: {
    simple: "English business language is often indirect. Instead of giving orders, people ask questions (“Could you …?”), add soft words (“a bit”, “slightly”, “I'm afraid”) and say “not very good” instead of “bad”. Also learn word pairs that look similar but mean different things, like <i>delay</i> (happens by accident) and <i>postpone</i> (decided on purpose).",
    normal: "<b>Five softening tools</b>, each with an example from a team meeting:<ol><li><b>Question instead of order</b>: <i>Fix the bug!</i> → <i>Could you have a look at the bug?</i></li><li><b>Softening intro</b>: <i>We can't meet the deadline.</i> → <i>I'm afraid we won't be able to meet the deadline.</i></li><li><b>Not + positive word</b>: <i>The design is ugly.</i> → <i>The design isn't very attractive yet.</i></li><li><b>Qualifiers</b>: <i>It's expensive.</i> → <i>It's a bit / slightly / rather expensive.</i></li><li><b>Past or continuous forms (distance)</b>: <i>I want to ask …</i> → <i>I was wondering if I could ask …</i>; <i>Do you have time?</i> → <i>Would you have a moment?</i></li></ol><b>More confusables</b> often tested: <i>say vs. tell</i> (say something / tell somebody something), <i>make vs. do</i> (make a decision, a mistake, a profit / do business, research, a job), <i>economic vs. economical</i>, <i>affect (verb) vs. effect (noun)</i>, <i>lend vs. borrow</i>, <i>sensible</i> (vernünftig) vs. <i>sensitive</i> (empfindlich), <i>become</i> (werden) vs. German <i>bekommen</i> (= <b>get</b>), <i>eventually</i> (schließlich) vs. German <i>eventuell</i> (= <b>possibly</b>).",
    technical: "Politeness theory (Brown & Levinson) explains this: requests threaten the listener's <b>negative face</b> (their freedom to act), so speakers reduce the imposition with indirectness, modals and hedges. British English is famous for <b>understatement</b>: <i>“That's not ideal”</i> can mean “That's a disaster”; <i>“With respect …”</i> introduces disagreement; <i>“I'll bear it in mind”</i> may mean “I won't do it”. German directness (<i>Das ist falsch.</i>) can therefore sound rude in English. Grammar of the modal requests: <i>Could you + infinitive?</i>, <i>Would you mind + -ing?</i> (answer “No, not at all” = yes, I'll do it!), <i>I'd be grateful if you could …</i>, <i>Would it be possible to …?</i>. <b>delay vs. postpone</b> in detail: <i>delay</i> can also be a noun (<i>a two-hour delay</i>) and is usually involuntary; <i>postpone</i> is a deliberate decision with a new date (<i>postponed until/to Monday</i>); <i>cancel</i> = it will not take place at all." } },
  { t: "example", title: "A blunt e-mail made diplomatic", html: "<b>Blunt</b> (student job, to the shift manager): <i>“The new schedule is wrong. I can't work on Saturday. Change it.”</i><br><b>Diplomatic</b>: <i>“Hi Mr Berger, <b>I'm afraid</b> [softening intro] the new schedule <b>isn't quite right</b> [not + positive] for me – I have an exam on Saturday morning. <b>I was wondering if</b> [distance] it <b>might be possible</b> [modal] to swap my shift with Tom's Friday shift? <b>I'd be grateful if you could</b> let me know by Wednesday. Thanks a lot!”</i><br>Same content, but the manager is much more likely to say yes." },
  { t: "example", title: "Confusables in one travel story", html: "<i>Our flight to Barcelona was <b>delayed</b> by two hours because of fog (not planned). Then the airline <b>cancelled</b> the connecting flight, so our hotel check-in had to be <b>postponed</b> to the next day (a decision). I had to <b>borrow</b> a charger from a stranger, who kindly <b>lent</b> me hers. The trip was not very <b>economical</b> (we spent too much), and the strike had a big <b>effect</b> on our plans – it <b>affected</b> the whole day. <b>Eventually</b>, we arrived at midnight.</i>" },
  { t: "hint", title: "“Would you mind …?” – answer with No!", html: "<i>Would you mind closing the window?</i> literally asks “Do you object?”. So the friendly answer is <b>“No, not at all”</b> or <b>“Of course not”</b> (= I'll do it). Saying “Yes” means you DO mind." },
  { t: "hint", title: "Top German false friends in business", html: "<i>aktuell</i> → <b>current</b> (not actual = tatsächlich) · <i>eventuell</i> → <b>possibly</b> (not eventually = schließlich) · <i>Chef</i> → <b>boss/manager</b> · <i>bekommen</i> → <b>get/receive</b> (not become) · <i>sensibel</i> → <b>sensitive</b> (not sensible = vernünftig) · <i>Handy</i> → <b>mobile (phone)</b>." },
  { t: "hint", title: "Exam trick for gap sentences", html: "When given words like <i>sure / don't need / remind</i>, build the frame first: <b>I'm sure I don't need to remind you of …</b>. Remember the patterns: <i>remind someone <b>of</b> something</i>, <i>remind someone <b>to</b> do something</i>." }
];
D["exx-3"] = [
  { t: "text", h: "Vertiefung: understanding Treasure's argument, not just the facts", levels: {
    simple: "Julian Treasure says we listen badly: we spend about 60 % of communication time listening but remember only about 25 %. Listening means making meaning from sound. Our brain uses tricks (recognising patterns like our name, ignoring constant noise, filters). The modern world makes it worse (noise, headphones, impatience). He gives five exercises to listen better, the last one is RASA: Receive, Appreciate, Summarise, Ask.",
    normal: "<b>The argument in four steps</b>:<ol><li><b>Problem</b>: we spend about 60 % of communication time listening but retain only about 25 %.</li><li><b>How listening works</b>: listening = <b>making meaning from sound</b>. The brain uses <b>pattern recognition</b> (you hear your name in a noisy room – the “cocktail party effect”), <b>differencing</b> (constant sounds like a fridge fade out; we notice changes) and <b>filters</b> (culture, language, values, beliefs, attitudes, expectations, intentions) to select what we pay attention to.</li><li><b>Why we are losing listening</b>: we invented <b>recording</b> (writing, audio, video), so accurate listening is less needed; the world is so <b>noisy</b> that people retreat into <b>headphones</b> (“millions of tiny private sound bubbles”); we have become <b>impatient</b> (soundbites); media have to scream at us (headlines, capital letters); we become <b>desensitised</b>.</li><li><b>Solution – five exercises</b>: <b>Silence</b> (3 min a day), <b>The mixer</b> (how many channels of sound can you hear?), <b>Savouring</b> (enjoy mundane sounds – the “hidden choir”), <b>Listening positions</b>, and <b>RASA</b>.</li></ol><b>Listening positions</b> explained: <i>active vs. passive</i> (do you engage or let it wash over you?), <i>reductive vs. expansive</i> (listening <b>for</b> a point/solution vs. enjoying the journey, like listening to jazz), <i>critical vs. empathetic</i> (judging vs. understanding the speaker's feelings).",
    technical: "<b>Connection to active listening (e5-1)</b>: RASA mirrors the course tools – <b>Receive</b> = attention and eye contact, <b>Appreciate</b> = non-verbal encouragement (<i>hmm, oh, okay</i>), <b>Summarise</b> = restatement (<i>“So …”</i>), <b>Ask</b> = open-ended questions afterwards. The filters correspond to the course's <b>emotional</b> and <b>semantic</b> barriers; the noisy world to <b>physical</b> barriers. <b>Vocabulary</b> from the talk: <i>to retain</i> (behalten), <i>to savour</i> (genießen), <i>mundane</i> (alltäglich, banal), <i>desensitised</i> (abgestumpft), <i>a soundbite</i> (a short quotable phrase), <i>to reset</i>, <i>conscious</i> (bewusst). His closing statement: <i>“Conscious listening always creates understanding.”</i> <b>RASA</b> is a Sanskrit word meaning “juice” or “essence”." } },
  { t: "example", title: "Treasure's five exercises in your week", html: "<ul><li><b>Silence</b>: before a lecture, Kevin sits in the empty library for three minutes without headphones – his ears “reset”.</li><li><b>The mixer</b>: on the tram he counts the channels: engine, announcement, two people talking, a phone ringing, rain on the window – five channels.</li><li><b>Savouring</b>: in the WG kitchen he listens to the coffee machine gurgling and the kettle – the “hidden choir” of mundane sounds.</li><li><b>Listening positions</b>: in a team meeting he notices he is listening <b>reductively</b> and <b>critically</b> (waiting to find mistakes) and switches to <b>empathetic</b>.</li><li><b>RASA</b>: when his flatmate Lukas tells him about his day, he <b>receives</b> (phone down), <b>appreciates</b> (“oh, really?”), <b>summarises</b> (“So the client loved your idea?”) and <b>asks</b> (“What did your boss say?”).</li></ul>" },
  { t: "hint", title: "Numbers that were missed in the old exam", html: "<b>60 %</b> of communication time = listening (not 30 %). We retain <b>25 %</b> (not 15 %). People deal with noise with <b>headphones</b>. RASA = Sanskrit for <b>juice</b> / essence. Memory trick: <b>6</b>0 → <b>2</b>5 sounds like “six to two-five”: we listen a lot, keep a quarter." },
  { t: "hint", title: "Listening ≠ hearing", html: "In the quiz, “hearing what is being said”, “filtering out noises” and “recognising patterns” are distractors. Treasure's definition is <b>making meaning from sound</b>. Filters, pattern recognition and differencing are only the <b>techniques</b> listening uses." },
  { t: "hint", title: "RASA in order", html: "<b>R</b>eceive → <b>A</b>ppreciate → <b>S</b>ummarise → <b>A</b>sk. The “Ask” comes last – first you listen, then you summarise (“so …”, which Treasure calls very important), then you ask questions. German spelling trap: <i>summarise/summarize</i>, not “summerise”." }
];
})();
