/* Prüfungsvorbereitung KOMMU – KEINE Altprüfungen vorhanden und keine schriftliche Prüfung. Aufgebaut aus den Beurteilungsregeln, Terminen und Aufgaben
   der Kursdatei (Anwesenheit/Mitarbeit, Portfolio AA1–3, Selbstreflexion & Feedback, Deep Talk) und den Skriptinhalten des Kurses.
   KI ist in KOMMU ausdrücklich verboten: Alle Aufgaben hier sind reine Selbstübungen an erfundenen Situationen – nie als Portfolio-/Deep-Talk-Abgabe verwenden. */
(function () {
const c = (window.COURSE_DEFS || []).find(x => x.id === "kommu"); if (!c) return;

const SRC = "Prüfungsnah (eigene Frage)";

/* ---------- MC / Richtig-Falsch ---------- */
c.questions.push(
 { id: "kx-q1", topic: "k-grund", q: "Ihr habt eine Anwesenheits- und Mitarbeitskomponente von 60 Punkten, abgezogen werden 4 Punkte je versäumter 45-Minuten-Einheit. Alle anderen Teile sind perfekt (40/40). Wie viele 45′-Einheiten darfst du höchstens versäumen, um noch ein Sehr gut (ab 91) zu haben?", opts: ["1", "2", "3", "4"], a: 1, why: "100 − 2 × 4 = 92 → Sehr gut; 100 − 3 × 4 = 88 → nur Gut. Und das nur, wenn Portfolio und Deep Talk volle Punkte bringen. Zusätzlich gilt: mindestens 80 % Anwesenheit.", alt: true, src: SRC },
 { id: "kx-q2", topic: "k-grund", q: "Darfst du dein Portfolio von einem KI-Tool formulieren oder „glätten“ lassen?", opts: ["Ja, wenn du es kennzeichnest", "Ja, aber nur für die Rechtschreibung", "Nein – KI ist in KOMMU ausdrücklich verboten (§ 17 Abs. 8 StuPO); Portfolio und Deep-Talk-Blatt selbst erstellen", "Nur für Arbeitsauftrag 3"], a: 2, why: "Laut LV-Regel ist KI ausdrücklich verboten. Diese App dient nur zum Lernen und Planen; Texte für Abgaben schreibst du selbst.", alt: true, src: SRC },
 { id: "kx-q3", topic: "k-grund", q: "Konrad Lorenz: „Gesagt bedeutet noch lange nicht gehört. Gehört bedeutet noch lange nicht verstanden. Verstanden bedeutet noch lange nicht …“", opts: ["behalten", "einverstanden", "angewandt", "beantwortet"], a: 1, why: "Kette: gesagt → gehört → verstanden → einverstanden → behalten → angewandt. An jeder Station kann Kommunikation abbrechen.", alt: true, src: SRC },
 { id: "kx-q4", topic: "k-svt", q: "Kollege um 22 Uhr im Gruppenchat: „Puh, schon wieder so spät.“ Welche Seite steckt in der Deutung „Ich bin erschöpft“?", opts: ["Sachinhalt", "Selbstkundgabe", "Beziehungshinweis", "Appell"], a: 1, why: "Die Selbstkundgabe zeigt, was im Sender vorgeht (hier implizit). Sachinhalt wäre „Es ist 22 Uhr“, ein Appell z. B. „Lasst uns Schluss machen“.", alt: true, src: SRC },
 { id: "kx-q5", topic: "k-svt", q: "Mitbewohnerin: „Im Kühlschrank ist keine Milch mehr.“ Du hörst: „Geh einkaufen!“ Mit welchem Ohr hast du gehört?", opts: ["Sach-Ohr", "Selbstkundgabe-Ohr", "Beziehungs-Ohr", "Appell-Ohr"], a: 3, why: "Der Appell ist das, was die Senderin erreichen will (offen oder verdeckt). Hörst du „Du denkst nie ans Einkaufen“, wäre es das Beziehungs-Ohr.", alt: true, src: SRC },
 { id: "kx-q6", topic: "k-team", q: "Du willst zu einer Teamanfrage ja und nein zugleich sagen und fühlst dich innerlich zerrissen. Wie ordnet das Modell des Inneren Teams das ein?", opts: ["Als Kommunikationsstörung, die behandelt werden muss", "Als normale innere Pluralität – Ziel ist, aus dem „Haufen“ ein Team zu machen, um klarer und authentischer zu reagieren", "Als Pseudogefühl", "Als symmetrische Eskalation"], a: 1, why: "Schulz von Thun: Mehrere „Seelen in der Brust“ sind normal. Gelingt es, die Stimmen zu hören und zu ordnen, reagiert man klarer, authentischer und situationsgerechter.", alt: true, src: SRC },
 { id: "kx-q7", topic: "k-team", q: "Was transportiert laut Eisbergtheorie vor allem die nonverbale Kommunikation?", opts: ["Fakten und Zahlen", "Eher Emotionen – die Sprache eher den Verstand", "Nur die Sachebene", "Ausschließlich Appelle"], a: 1, why: "Nonverbales trägt eher Emotionen, Sprache eher den Verstand; mindestens 80 % der Entscheidungen fallen „im Bauch“. Droht Gefahr, wird das Nonverbale wichtiger als die Worte.", alt: true, src: SRC },
 { id: "kx-q8", topic: "k-watz", q: "„Er kommt zu spät, weil sie immer meckert; sie meckert, weil er immer zu spät kommt.“ Welches Axiom beschreibt das?", opts: ["Axiom 1 – man kann nicht nicht kommunizieren", "Axiom 3 – Interpunktion von Ereignisfolgen (Ursache und Wirkung)", "Axiom 4 – analog und digital", "Axiom 5 – symmetrisch und komplementär"], a: 1, why: "Jede Seite setzt den „Anfang“ der Kette anders (Interpunktion) und sieht das eigene Verhalten nur als Reaktion.", alt: true, src: SRC },
 { id: "kx-q9", topic: "k-watz", q: "Was gehört zur analogen Kommunikation nach Watzlawick?", opts: ["Der Wortlaut einer E-Mail", "Mimik, Gestik, Tonfall, Körperhaltung", "Fachbegriffe", "Zahlen und Daten"], a: 1, why: "Analog = nonverbal, bildhaft, eher Beziehungsaspekt. Digital = Worte/Zeichen mit vereinbarter Bedeutung, eher Inhaltsaspekt.", alt: true, src: SRC },
 { id: "kx-q10", topic: "k-gfkhalt", q: "Welche Aussage gehört zu den Grundannahmen der GFK nach Rosenberg?", opts: ["Wer Fehler macht, muss Konsequenzen spüren", "Alles, was ein Mensch tut, ist ein Versuch, eigene Bedürfnisse zu erfüllen", "Bedürfnisse erfüllt man am besten in Konkurrenz", "Nur perfekt erledigte Dinge sind es wert, getan zu werden"], a: 1, why: "Weitere Grundannahmen: Gewalt ist ein tragischer Ausdruck unerfüllter Bedürfnisse; Kooperation statt Konkurrenz; alles, was es wert ist getan zu werden, ist es wert, unvollkommen getan zu werden.", alt: true, src: SRC },
 { id: "kx-q11", topic: "k-gfkhalt", q: "„Ich fühle, dass du unfair bist.“ Wolf- oder Giraffensprache?", opts: ["Giraffe – es beginnt mit „Ich fühle“", "Wolf – ein Urteil ist als Gefühl getarnt", "Giraffe – es ist eine Ich-Botschaft", "Weder noch – das ist eine Bitte"], a: 1, why: "„fühlen, dass …“ ist ein Warnsignal: Es folgt ein Gedanke/Urteil („unfair“), kein Gefühl. Giraffe wäre z. B. „Ich bin enttäuscht, weil mir Fairness wichtig ist.“", alt: true, src: SRC },
 { id: "kx-q12", topic: "k-block", q: "„Du bist einfach ein Egoist.“ Welche Kommunikationsblockade liegt vor?", opts: ["Moralisches Urteil", "Vergleich", "Verantwortung leugnen", "Strafe"], a: 0, why: "Moralische Urteile sagen, wie jemand IST (Schubladen, Diagnosen, Beleidigungen) – statt zu beschreiben, was er tut und was mir fehlt.", alt: true, src: SRC },
 { id: "kx-q13", topic: "k-block", q: "„Ich hatte keine Wahl, die Projektleitung wollte es so.“ Welche Blockade?", opts: ["Forderung", "Vergleich", "Verantwortung leugnen", "Lob"], a: 2, why: "Formulierungen wie „müssen“, „keine Wahl“, „so sind die Vorschriften“ verschleiern, dass man selbst entschieden hat.", alt: true, src: SRC },
 { id: "kx-q14", topic: "k-block", q: "Warum kann laut GFK auch Lob blockieren?", opts: ["Weil Lob immer gelogen ist", "Wenn es eingesetzt wird, um Verhalten zu steuern – es ist dann ein Urteil (positiv) mit Belohnungsabsicht", "Weil man in der GFK nie über andere sprechen darf", "Weil Lob die Beziehungsebene ausschaltet"], a: 1, why: "Lob als Steuerungsinstrument ist die Kehrseite von Strafe. GFK-Alternative: Dank ausdrücken – was die Person getan hat, wie es mir geht und welches Bedürfnis dadurch erfüllt wurde.", alt: true, src: SRC },
 { id: "kx-q15", topic: "k-beob", q: "Welche Aussage ist eine Beobachtung im Sinne der GFK?", opts: ["„Du bist nie bei der Sache.“", "„In den letzten drei Teamtreffen hast du während der Präsentationen auf deinem Handy getippt.“", "„Du tippst ständig auf dem Handy.“", "„Du interessierst dich nicht für unsere Arbeit.“"], a: 1, why: "Kamera-Test: konkret, zeitlich begrenzt, überprüfbar. „nie“, „ständig“ und Unterstellungen („interessierst dich nicht“) sind Bewertungen.", alt: true, src: SRC },
 { id: "kx-q16", topic: "k-gef", q: "Welche Formulierung drückt ein echtes Gefühl aus?", opts: ["„Ich fühle mich ausgenutzt.“", "„Ich habe das Gefühl, dass das sinnlos ist.“", "„Ich bin traurig und ein bisschen ratlos.“", "„Ich fühle mich, als ob mir niemand zuhört.“"], a: 2, why: "Traurig und ratlos sind Gefühle. „ausgenutzt“ beschreibt, was andere (angeblich) tun; „dass …“ und „als ob …“ leiten Gedanken ein – Pseudogefühle.", alt: true, src: SRC },
 { id: "kx-q17", topic: "k-bed", q: "Welche Aussage nennt ein Bedürfnis und keine Strategie?", opts: ["„Ich brauche, dass du mich jeden Abend anrufst.“", "„Mir ist Verbindung wichtig.“", "„Ich will, dass du pünktlich bist.“", "„Ich brauche ein neues Handy.“"], a: 1, why: "Bedürfnisse sind abstrakt, universell und unabhängig von Zeit, Ort und Person (Verbindung, Verlässlichkeit, Sicherheit). Anrufen, Pünktlichkeit einer bestimmten Person oder ein Handy sind Strategien.", alt: true, src: SRC },
 { id: "kx-q18", topic: "k-bitte", q: "Welche Bitte ist am erfolgversprechendsten?", opts: ["„Sei bitte nicht so laut.“", "„Nimm bitte mehr Rücksicht.“", "„Würdest du bitte ab 22 Uhr Kopfhörer verwenden, wenn du Musik hörst?“", "„Du musst ab jetzt leiser sein.“"], a: 2, why: "Positiv (was ich will, nicht was ich nicht will), konkret und in Handlungssprache, als Frage mit echter Wahl. „mehr Rücksicht“ ist ein frommer Wunsch, „musst“ eine Forderung.", alt: true, src: SRC },
 { id: "kx-q19", topic: "k-4s", q: "„Als du gestern meine Notizen ohne zu fragen mitgenommen hast, war ich verärgert. Gib sie mir bitte heute bis 12 Uhr zurück.“ Welcher GFK-Schritt fehlt?", opts: ["Beobachtung", "Gefühl", "Bedürfnis", "Bitte"], a: 2, why: "Beobachtung (gestern, ohne zu fragen mitgenommen), Gefühl (verärgert) und Bitte (heute bis 12 Uhr) sind da. Es fehlt das Bedürfnis, z. B. „weil mir Verlässlichkeit/Absprache wichtig ist und ich die Notizen zum Lernen brauche“.", alt: true, src: SRC },
 { id: "kx-q20", topic: "k-zuh", q: "Eine Freundin: „Ich hab die Klausur verhaut, obwohl ich so viel gelernt habe.“ Welche Reaktion ist aktives Zuhören?", opts: ["„Das passiert jedem mal, mach dir nichts draus.“", "„Du hättest früher anfangen sollen.“", "„Du bist enttäuscht, weil du dir für den Aufwand ein besseres Ergebnis gewünscht hättest?“", "„Mir ist das letztes Jahr auch passiert, da habe ich …“"], a: 2, why: "Gefühl und Bedürfnis spiegeln und als Frage zur Bestätigung anbieten. Trösten/Bagatellisieren, Ratschläge und das Thema auf sich lenken sind typische Gesprächsblocker.", alt: true, src: SRC },
 { id: "kx-q21", topic: "k-ich", q: "Welche Aussage ist eine Ich-Botschaft im Sinne der Ich-Formel?", opts: ["„Ich finde, du bist rücksichtslos.“", "„Ich bin verunsichert, wenn Termine am Vortag verschoben werden, weil ich Planbarkeit brauche.“", "„Ich sage dir jetzt mal, was du falsch machst.“", "„Ich frage mich, warum du nie zuhörst.“"], a: 1, why: "Gefühl (verunsichert) + Verhalten ohne Schuld (Termine am Vortag verschoben) + Bedürfnis (Planbarkeit). Die anderen beginnen mit „Ich“, sind aber verkappte Du-Botschaften mit Urteil.", alt: true, src: SRC },
 { id: "kx-q22", topic: "k-ich", q: "Richtig oder falsch: Jeder Satz, der mit „Ich“ beginnt, ist eine Ich-Botschaft.", opts: ["Richtig", "Falsch"], a: 1, why: "Falsch. „Ich finde, du bist faul“ ist eine Du-Botschaft (Urteil über den anderen). Eine Ich-Botschaft beschreibt eigenes Gefühl, das Verhalten ohne Schuldzuweisung und das eigene Bedürfnis.", alt: true, src: SRC },
 { id: "kx-q23", topic: "k-harv", q: "Zwei Teams streiten um den einzigen Besprechungsraum am Freitag. Welche Frage folgt dem Prinzip „Interessen statt Positionen“?", opts: ["„Wer hat zuerst reserviert?“", "„Wofür braucht ihr den Raum genau – was muss er können?“", "„Wer ist in der Hierarchie höher?“", "„Wollt ihr ihn ganz oder gar nicht?“"], a: 1, why: "W-Fragen nach dem Warum legen Interessen offen (z. B. Bildschirm vs. Ruhe). Daraus entstehen Optionen „sowohl als auch“ – wie bei der Orange (Saft vs. Schale).", alt: true, src: SRC },
 { id: "kx-q24", topic: "k-harv", q: "Was ist ein objektives Kriterium im Sinne des Harvard-Konzepts?", opts: ["„Ich will es so, weil ich älter bin.“", "Der übliche Marktpreis laut Vergleichsportal", "„Wer lauter argumentiert, gewinnt.“", "Die eigene Position wiederholen, bis die andere nachgibt"], a: 1, why: "Objektive Kriterien sind faire, von beiden anerkennbare Maßstäbe (Marktwert, Gutachten, Regeln, Losverfahren) – unabhängig vom Willen einer Seite.", alt: true, src: SRC }
);

/* ---------- Offene Fragen mit Musterantwort (Wissen für Mitarbeit, Portfolio-Theorie und Deep Talk) ---------- */
c.flashcards.push(
 { id: "kx-f1", cat: "KOMMU", topic: "k-svt", alt: true, src: SRC, front: "Analysiere mit dem Kommunikationsquadrat: Projektleiterin zur Gruppe: „Die Abgabe ist übermorgen.“", back: "<ul><li><b>Sachinhalt</b> (blau): Abgabetermin ist in zwei Tagen.</li><li><b>Selbstkundgabe</b> (grün): Ich bin nervös / mir ist der Termin wichtig.</li><li><b>Beziehungshinweis</b> (gelb): Ich traue euch nicht zu, dass ihr daran denkt / ich bin für euch verantwortlich.</li><li><b>Appell</b> (rot): Macht eure Teile fertig!</li></ul>Je nachdem, mit welchem Ohr die Gruppe hört, reagiert sie sachlich, besorgt, gekränkt oder geschäftig. Das Beziehungsohr ist bei vielen besonders empfindlich." },
 { id: "kx-f2", cat: "KOMMU", topic: "k-watz", alt: true, src: SRC, front: "Nenne die fünf Axiome Watzlawicks mit je einem eigenen Beispiel.", back: "<ol><li><b>Man kann nicht nicht kommunizieren.</b> – Wer im Meeting schweigt und aufs Handy schaut, sagt auch etwas.</li><li><b>Inhalts- und Beziehungsaspekt</b>, wobei der Beziehungsaspekt den Inhalt bestimmt. – „Super gemacht“ ironisch gesagt.</li><li><b>Interpunktion</b>: Die Natur einer Beziehung hängt davon ab, wie die Partner die Ereignisfolge gliedern. – „Ich kontrolliere, weil du schlampst“ / „Ich schlampe, weil du kontrollierst“.</li><li><b>Digitale und analoge Modalitäten</b>. – „Passt schon“ (digital) mit verschränkten Armen (analog).</li><li><b>Symmetrisch oder komplementär</b> (Gleichheit vs. Unterschiedlichkeit). – Zwei Kolleginnen überbieten sich (symmetrisch); Chefin–Praktikant (komplementär). Gestört ist es, wenn eine Form starr wird (z. B. symmetrische Eskalation).</li></ol>" },
 { id: "kx-f3", cat: "KOMMU", topic: "k-gfkhalt", alt: true, src: SRC, front: "Die zwei Säulen der GFK und die sieben Grundannahmen.", back: "<b>Säulen:</b> Aufrichtigkeit (ich teile mit, wie es mir geht und was ich brauche) und Empathie (ich bin ganz bei der anderen Person).<br><b>Grundannahmen:</b><ol><li>Alles, was ein Mensch tut, ist ein Versuch, eigene Bedürfnisse zu erfüllen.</li><li>Jede Form von Gewalt ist ein tragischer Ausdruck unerfüllter Bedürfnisse.</li><li>Bedürfnisse lassen sich durch Kooperation statt Konkurrenz erfüllen.</li><li>Es bereitet Freude, zum Wohl anderer beizutragen, wenn es freiwillig geschieht.</li><li>Alles, was es wert ist getan zu werden, ist es auch wert, unvollkommen getan zu werden.</li><li>Jeder Mensch macht in jedem Augenblick das Beste, was er für sein Leben tun kann.</li><li>Ziel ist nicht Perfektion, sondern all unser Lachen zu lachen und all unsere Tränen zu weinen.</li></ol>" },
 { id: "kx-f4", cat: "KOMMU", topic: "k-4s", alt: true, src: SRC, front: "Die 4 Schritte der GFK – je Schritt die typische Falle.", back: "<table class=\"dt\"><tr><th>Schritt</th><th>Gelingt, wenn …</th><th>Typische Falle</th></tr><tr><td>1 Beobachtung</td><td>eine Kamera es aufzeichnen könnte</td><td>„immer, nie, schon wieder, total“, Interpretationen</td></tr><tr><td>2 Gefühl</td><td>es ein echtes Gefühl ist (traurig, verärgert, erleichtert)</td><td>Pseudogefühle: „dass/als ob“, „ich habe das Gefühl, …“, „ignoriert, ausgenutzt“</td></tr><tr><td>3 Bedürfnis</td><td>es abstrakt und universell ist (Verlässlichkeit, Ruhe)</td><td>Strategie statt Bedürfnis („dass du anrufst“)</td></tr><tr><td>4 Bitte</td><td>positiv, konkret, in Handlungssprache, mit echter Wahl</td><td>frommer Wunsch („mehr Rücksicht“) oder Forderung (Nein wird bestraft)</td></tr></table>" },
 { id: "kx-f5", cat: "KOMMU", topic: "k-gef", alt: true, src: SRC, front: "Woran erkennst du ein Pseudogefühl? (vier Warnsignale)", back: "Vorsicht, wenn nach „fühlen“ folgt:<ol><li><b>dass, wie, als ob</b> – „Ich fühle, dass du mich nicht ernst nimmst.“</li><li>ein <b>Pronomen</b> – „Ich habe das Gefühl, es ist sinnlos.“</li><li><b>Namen oder Personen</b> – „Ich fühle, mein Chef manipuliert mich.“</li><li>ein <b>Verb, das beschreibt, was andere tun</b> – ausgenutzt, ignoriert, übergangen, im Stich gelassen.</li></ol>Umformen: Was fühle ich dabei wirklich? (z. B. „übergangen“ → enttäuscht, verletzt; Bedürfnis: Gesehenwerden, Beteiligung)." },
 { id: "kx-f6", cat: "KOMMU", topic: "k-ich", alt: true, src: SRC, front: "Ich-Formel: drei Teile – und wie wird aus „Du lässt mich immer warten!“ eine Ich-Botschaft?", back: "<ol><li><b>Gefühl</b>: „Ich bin …“ (echtes Gefühl)</li><li><b>Verhalten ohne Schuld</b>: „wenn …“ (beschreibend)</li><li><b>Bedürfnis/Wunsch</b>: „weil ich … brauche“ / „ich würde mich freuen, wenn …“</li></ol>Beispiel: „Ich bin ungeduldig und gestresst, wenn ich nach dem vereinbarten Zeitpunkt 20 Minuten warte, weil mir meine Zeit und Verlässlichkeit wichtig sind. Ich würde mich freuen, wenn du mir schreibst, sobald du merkst, dass es später wird.“" },
 { id: "kx-f7", cat: "KOMMU", topic: "k-zuh", alt: true, src: SRC, front: "Aktives Zuhören: vier fördernde Reaktionen und drei Arten von Zuhörbarrieren.", back: "<b>Fördernd:</b><ul><li>nonverbal verstärken (Blickkontakt, Nicken, „mh, ja“, zugewandte Haltung)</li><li>auf Inhalte und Gefühle eingehen (zusammenfassen, spiegeln, nachfragen, eigene Meinung zurückstellen, keine Lösungen anbieten)</li><li>zum Sprechen ermutigen („Möchtest du mehr darüber erzählen?“)</li><li>Zeit geben (Pausen aushalten, nicht dazwischenreden)</li></ul><b>Barrieren:</b> physisch (Lärm, Müdigkeit), emotional (Vorurteile, Reizwörter), semantisch (unterschiedliches Vokabular, Fachbegriffe)." },
 { id: "kx-f8", cat: "KOMMU", topic: "k-harv", alt: true, src: SRC, front: "Harvard-Konzept: vier Prinzipien, BATNA und WATNA.", back: "<ol><li><b>Menschen und Probleme trennen</b> – weich zu den Menschen, Emotionen ohne Schuld ansprechen</li><li><b>Interessen statt Positionen</b> – W-Fragen: Warum will jemand etwas?</li><li><b>Optionen entwickeln</b> – „sowohl als auch“ statt „entweder oder“, Brainstorming</li><li><b>Objektive Kriterien</b> – faire, gemeinsame Entscheidungsgrundlage</li></ol><b>BATNA</b> = Best Alternative To a Negotiated Agreement: beste Alternative ohne Einigung – je attraktiver, desto größer die Verhandlungsmacht. <b>WATNA</b> = Worst Alternative To a Negotiated Agreement: schlechtestes realistisches Szenario ohne Einigung. Beispiel Orange: Eine Person will den Saft, die andere die Schale – beide bekommen 100 %." },
 { id: "kx-f9", cat: "KOMMU", topic: "k-zuh", alt: true, src: SRC, front: "Deep Talk: Wie führst du ein Gespräch so, dass du Gefühl und Bedürfnis des Gegenübers wahrnimmst und bestätigen lässt?", back: "<ol><li>Eine offene, persönliche Frage stellen und echtes Interesse zeigen.</li><li>Aktiv zuhören: nicht unterbrechen, keine Ratschläge, eigene Geschichte zurückstellen.</li><li>Gefühl und Bedürfnis <b>vermuten und als Frage spiegeln</b>: „Bist du stolz, weil dir Selbstständigkeit wichtig ist?“</li><li>Auf Bestätigung oder Korrektur warten – eine Korrektur ist ein Erfolg, weil sie zum eigentlichen Bedürfnis führt.</li><li>Danach kurz notieren: Frage, wahrgenommenes Gefühl, Bedürfnis, Bestätigung ja/nein.</li></ol>Das Übungsblatt füllst du selbst und ohne KI aus." },
 { id: "kx-f10", cat: "KOMMU", topic: "k-ich", alt: true, src: SRC, front: "Feedback geben und nehmen – woran orientierst du dich (für Mitarbeit und den Teil „Selbstreflexion & Feedback“)?", back: "<b>Geben</b> (allgemeine Feedbackregeln, passen zu GFK und Ich-Botschaft):<ul><li>beschreibend statt bewertend (Beobachtung), konkret statt allgemein</li><li>als Ich-Botschaft: Wirkung auf mich, mein Gefühl, mein Bedürfnis</li><li>zeitnah, auf veränderbares Verhalten bezogen, mit konkretem Vorschlag als Bitte</li><li>erwünscht – vorher fragen, ob die Person Feedback möchte; auch Gelungenes benennen</li></ul><b>Nehmen:</b> zuhören, nachfragen, nicht rechtfertigen, das eigene Gefühl wahrnehmen, bedanken und selbst entscheiden, was man annimmt.<br><b>Selbstreflexion:</b> Was habe ich ausprobiert, was ist passiert (Beobachtung), wie ging es mir, was habe ich gelernt, was mache ich nächstes Mal anders?" }
);

/* ---------- Prüfungsfokus ---------- */
c.examPrep = {
  format: "<b>Es wurden keine Altprüfungen bereitgestellt – KOMMU hat keine schriftliche Prüfung.</b> Beurteilt wird laut Kursunterlagen mit 100 Punkten: <b>Anwesenheit & Mitarbeit 60 P.</b> (−4 P. je versäumter 45-Minuten-Einheit), <b>Portfolio</b> mit Arbeitsauftrag 1, 2 und 3 (je 5 P.) sowie <b>Selbstreflexion & Feedback</b> (10 P.), und <b>Deep Talk Interviews</b> (15 P., ausgefülltes Übungsblatt). Mind. <b>80 % Anwesenheit</b> erforderlich. Portfolio als PDF/Word mit Inhaltsverzeichnis, Kopf-/Fußzeile mit Name und Seitenzahlen, Rechtschreibung prüfen – Abgabe bis 28.01.2027, 23:59 (öffnet 07.11.2026); Deep-Talk-Blatt bis 30.01.2027, 23:59. <b>KI ist ausdrücklich verboten</b> (§ 17 Abs. 8 StuPO). Ob einzelne Teile separat positiv sein müssen, ist in den Unterlagen nicht angegeben – in der LV nachfragen. Die Fragen und Übungen hier sind selbst erstellte Selbstübungen an erfundenen Situationen.",
  sources: ["Kursdatei KOMMU (Beurteilung, Termine, Arbeitsaufträge, Forumsaufgaben)", "Skript Kommunikationstraining WS 2026/27 (Inhalte laut Kurs)"],
  strategy: [
    "Anwesenheit ist der größte Hebel: 60 von 100 Punkten, jede versäumte 45′-Einheit kostet 4 Punkte. Für ein Sehr gut (≥ 91) darfst du selbst bei perfektem Portfolio und Deep Talk höchstens zwei Einheiten versäumen – also praktisch jede Einheit besuchen und aktiv mitmachen.",
    "Arbeitsaufträge 1–3 rechtzeitig vorbereiten und zur jeweiligen Einheit mitbringen (AA1 zur 2., AA2 zur 3., AA3 zur 5. UE) – nicht erst kurz vor der Portfolio-Abgabe.",
    "Im Portfolio die Theorie korrekt anwenden: Kamera-taugliche Beobachtungen, echte Gefühle statt Pseudogefühle, Bedürfnisse statt Strategien, positive konkrete Bitten – genau diese Unterscheidungen trainieren die Übungen hier.",
    "Selbstreflexion & Feedback (10 P.) ernst nehmen: ehrlich, konkret, mit Lernerkenntnis und nächstem Schritt – und Formalia (Inhaltsverzeichnis, Kopf-/Fußzeile, Seitenzahlen, Rechtschreibung) sauber erfüllen.",
    "Deep Talk (15 P.) über die Wochen verteilt führen und sofort notieren: Frage, vermutetes Gefühl/Bedürfnis, Bestätigung – nicht am letzten Abend rekonstruieren.",
    "Alles selbst schreiben: KI ist verboten. Diese App nur zum Üben an erfundenen Beispielen verwenden, nie Texte übernehmen."
  ],
  focus: [
    { topic: "k-4s", weight: 3, note: "GFK in der Anwendung – Kern von Arbeitsauftrag 2 und 3 und der Mitarbeit" },
    { topic: "k-beob", weight: 3, note: "Beobachtung vs. Bewertung – eigene Übung in AA2, Grundlage jeder GFK-Formulierung" },
    { topic: "k-gef", weight: 3, note: "Gefühle vs. Pseudogefühle – AA2 und Deep Talk (Gefühl wahrnehmen)" },
    { topic: "k-bed", weight: 3, note: "Bedürfnisse erkennen – AA2/AA3 (Bedürfnischeck) und Deep Talk" },
    { topic: "k-zuh", weight: 3, note: "Aktives Zuhören ist die Technik der Deep Talk Interviews (15 P.)" },
    { topic: "k-gfkhalt", weight: 2, note: "Arbeitsauftrag 1 (GFK-Grundhaltung), Forumsaufgaben" },
    { topic: "k-bitte", weight: 2, note: "4. GFK-Schritt, häufigster Fehler: frommer Wunsch/Forderung" },
    { topic: "k-ich", weight: 2, note: "Ich-Botschaften für Feedback und Selbstreflexion" },
    { topic: "k-block", weight: 2, note: "Blockaden erkennen und umformulieren (Forum „negative Aussagen“)" },
    { topic: "k-svt", weight: 2, note: "Vier-Ohren-Modell – Mitarbeit, Mindmap-Forum" },
    { topic: "k-watz", weight: 2, note: "Axiome – Mitarbeit, Mindmap- und Beispiel-Forum" },
    { topic: "k-harv", weight: 2, note: "Harvard-Konzept, BATNA/WATNA – Forum „Übung Urlaub“" },
    { topic: "k-team", weight: 1, note: "Eisberg und Inneres Team – Hintergrund für Selbstreflexion" },
    { topic: "k-grund", weight: 1, note: "Grundmodell, Beurteilungs- und KI-Regeln" }
  ],
  checklist: [
    { id: "kxc1", topic: "k-grund", text: "Jede Einheit besuchen (mind. 80 %; jede versäumte 45′ = −4 P.) und aktiv mitarbeiten." },
    { id: "kxc2", topic: "k-grund", text: "Abgabetermine eingetragen: Portfolio bis 28.01.2027 23:59 (öffnet 07.11.2026), Deep-Talk-Blatt bis 30.01.2027 23:59." },
    { id: "kxc3", topic: "k-gfkhalt", text: "Arbeitsauftrag 1 (eine von drei Übungen zur GFK-Grundhaltung) selbst erstellt und zur 2. UE mitgebracht." },
    { id: "kxc4", topic: "k-4s", text: "Arbeitsauftrag 2 (zwei von vier Übungen zu den GFK-Schritten) selbst erstellt und zur 3. UE mitgebracht." },
    { id: "kxc5", topic: "k-4s", text: "Arbeitsauftrag 3 (eine von drei Übungen zur GFK-Anwendung) selbst erstellt und zur 5. UE mitgebracht." },
    { id: "kxc6", topic: "k-ich", text: "Selbstreflexion & Feedback geschrieben: konkret, ehrlich, mit Lernerkenntnis und nächstem Schritt." },
    { id: "kxc7", topic: "k-grund", text: "Portfolio-Formalia: PDF/Word, Inhaltsverzeichnis, Kopf-/Fußzeile mit Name und Seitenzahlen, Rechtschreibung geprüft." },
    { id: "kxc8", topic: "k-zuh", text: "Deep Talk Interviews geführt (pro Einheit 2 Fragen), Gefühl/Bedürfnis wahrgenommen und bestätigen lassen, Übungsblatt selbst ausgefüllt." },
    { id: "kxc9", topic: "k-grund", text: "Forumsaufgaben erledigt: Gesichtsausdrückeraten, Mindmap (Homegroup), Übung Urlaub, negative Aussagen umformulieren, Beispiele GFK-Grundhaltungen und Watzlawick-Axiome." },
    { id: "kxc10", topic: "k-grund", text: "Kein KI-Einsatz bei Portfolio, Deep Talk und Forumsbeiträgen (§ 17 Abs. 8 StuPO)." },
    { id: "kxc11", topic: "k-svt", text: "Jede Aussage in Sachinhalt, Selbstkundgabe, Beziehungshinweis und Appell zerlegen können (inkl. Farben)." },
    { id: "kxc12", topic: "k-watz", text: "Alle fünf Axiome mit eigenem Beispiel erklären können." },
    { id: "kxc13", topic: "k-team", text: "Eisbergtheorie und Inneres Team erklären und für die eigene Reflexion nutzen." },
    { id: "kxc14", topic: "k-gfkhalt", text: "Zwei Säulen und sieben Grundannahmen der GFK, Wolf- vs. Giraffensprache unterscheiden." },
    { id: "kxc15", topic: "k-block", text: "Blockaden (moralisches Urteil, Vergleich, Verantwortung leugnen, Forderung, Strafe, Lob) erkennen und umformulieren." },
    { id: "kxc16", topic: "k-beob", text: "Bewertungen in Kamera-taugliche Beobachtungen umformulieren (Warnwörter immer, nie, schon wieder …)." },
    { id: "kxc17", topic: "k-gef", text: "Pseudogefühle an den vier Warnsignalen erkennen und in echte Gefühle übersetzen." },
    { id: "kxc18", topic: "k-bed", text: "Hinter Vorwürfen und Strategien das Bedürfnis finden (beide Wege: Verhalten → Bedürfnis, Bewertung → Gegenteil)." },
    { id: "kxc19", topic: "k-bitte", text: "Lösungs- und Beziehungsbitten positiv, konkret und mit echter Wahl formulieren." },
    { id: "kxc20", topic: "k-harv", text: "Vier Harvard-Prinzipien anwenden, Positionen von Interessen trennen, BATNA/WATNA bestimmen." }
  ],
  tasks: [
   { id: "kxr1", topic: "k-beob", title: "Selbstübung: Bewertung → Beobachtung",
     html: "Formuliere die Aussagen so um, dass eine Kamera sie aufzeichnen könnte (erfundene Situationen – nur zum Üben):<ol><li>„Jonas ist total unzuverlässig.“</li><li>„Die WG-Küche ist schon wieder ein Saustall.“</li><li>„Meine Trainerin bevorzugt die anderen.“</li><li>„Du redest immer dazwischen.“</li><li>„Lena hat sich gestern ziemlich daneben benommen.“</li><li>„Der Vortrag war viel zu lang.“</li></ol>",
     solution: "<ol><li>„Jonas hat diese Woche zwei von drei vereinbarten Treffen abgesagt, jeweils eine Stunde vorher.“</li><li>„Auf der Arbeitsfläche stehen seit Samstag drei ungespülte Töpfe.“</li><li>„Beim letzten Training hat die Trainerin vier anderen Spielerinnen Feedback gegeben und mir nicht.“</li><li>„In der Besprechung heute hast du zweimal zu sprechen begonnen, bevor ich meinen Satz beendet hatte.“</li><li>„Lena hat gestern beim Abendessen zweimal laut „Halt die Klappe“ zu Tim gesagt.“</li><li>„Der Vortrag dauerte 50 Minuten, geplant waren 20.“</li></ol><b>Prüfkriterien:</b> konkret (wer, was, wann, wie oft), überprüfbar, keine Warnwörter (immer, schon wieder, total, zu …), keine Unterstellung von Absichten (bevorzugt, daneben benommen). Eine gute Beobachtung kann das Gegenüber nicht bestreiten – sie schafft eine gemeinsame Wirklichkeit." },
   { id: "kxr2", topic: "k-gef", title: "Selbstübung: Pseudogefühl → Gefühl + Bedürfnis",
     html: "Übersetze die Pseudogefühle in echte Gefühle und finde ein mögliches Bedürfnis:<table class=\"dt\"><tr><th>Pseudogefühl</th></tr><tr><td>„Ich fühle mich übergangen.“</td></tr><tr><td>„Ich fühle mich ausgenutzt.“</td></tr><tr><td>„Ich habe das Gefühl, dass mir niemand zuhört.“</td></tr><tr><td>„Ich fühle mich unter Druck gesetzt.“</td></tr><tr><td>„Ich fühle mich im Stich gelassen.“</td></tr></table>",
     solution: "<table class=\"dt\"><tr><th>Pseudogefühl</th><th>Mögliche echte Gefühle</th><th>Mögliches Bedürfnis</th></tr><tr><td>übergangen</td><td>enttäuscht, verletzt, ärgerlich</td><td>Beteiligung, Gesehenwerden, Wertschätzung</td></tr><tr><td>ausgenutzt</td><td>wütend, frustriert, erschöpft</td><td>Fairness, Gegenseitigkeit, Ausgleich</td></tr><tr><td>„dass mir niemand zuhört“</td><td>einsam, traurig, frustriert</td><td>Verbindung, Verständnis, gehört werden</td></tr><tr><td>unter Druck gesetzt</td><td>angespannt, gestresst, beunruhigt</td><td>Selbstbestimmung, Ruhe, Freiraum</td></tr><tr><td>im Stich gelassen</td><td>enttäuscht, ängstlich, hilflos</td><td>Unterstützung, Verlässlichkeit</td></tr></table>Merke: Pseudogefühle beschreiben, was andere (angeblich) tun – die Verantwortung liegt beim Gegenüber. Echte Gefühle zeigen wie Armaturenbrett-Lämpchen an, ob ein eigenes Bedürfnis erfüllt ist. Es gibt mehrere richtige Lösungen – entscheidend ist, dass Gefühl und Bedürfnis zueinander passen." },
   { id: "kxr3", topic: "k-4s", title: "Selbstübung: Die 4 Schritte in einer WG-Situation",
     html: "Erfundene Situation: Dein Mitbewohner hat in den letzten zwei Wochen dreimal nach Mitternacht laut Musik gehört; du hattest am Morgen danach jeweils um 8 Uhr Vorlesung. Dein erster Impuls: „Du bist so rücksichtslos!“<ol><li>Formuliere die Botschaft in den 4 GFK-Schritten.</li><li>Ergänze eine Beziehungsbitte.</li><li>Was tust du, wenn er „Nein“ sagt?</li></ol>",
     solution: "<ol><li><b>Beobachtung:</b> „In den letzten zwei Wochen lief dreimal nach Mitternacht Musik aus deinem Zimmer, die ich in meinem Zimmer gehört habe.“<br><b>Gefühl:</b> „Ich war dann gereizt und am nächsten Morgen erschöpft,“<br><b>Bedürfnis:</b> „weil mir Schlaf und Erholung wichtig sind, gerade vor den Vorlesungen um 8.“<br><b>Bitte (Lösungsbitte):</b> „Wärst du bereit, unter der Woche ab 23 Uhr Kopfhörer zu verwenden?“</li><li><b>Beziehungsbitte:</b> „Wie geht es dir, wenn du das hörst?“ oder „Magst du mir sagen, was bei dir angekommen ist?“</li><li>Ein Nein ist ein Gesprächsangebot, kein Angriff: empathisch nach seinem Bedürfnis fragen („Ist dir wichtig, abends abschalten zu können?“) und gemeinsam eine Strategie suchen, die beide Bedürfnisse erfüllt (z. B. Lautsprecher am Wochenende, Kopfhörer unter der Woche). Folgen Vorwurf oder Druck, war es eine Forderung.</li></ol>" },
   { id: "kxr4", topic: "k-ich", title: "Selbstübung: Du-Botschaften → Ich-Botschaften",
     html: "Wandle mit der Ich-Formel (Gefühl – Verhalten ohne Schuld – Bedürfnis/Wunsch) um:<ol><li>„Du hörst mir nie zu!“</li><li>„Du hast schon wieder deinen Teil zu spät geschickt.“</li><li>„Du nervst mit deinen ständigen Nachrichten.“</li><li>„Ich finde, du bist arrogant.“</li></ol>",
     solution: "<ol><li>„Ich bin enttäuscht, wenn ich dir etwas erzähle und du dabei auf dein Handy schaust, weil mir Aufmerksamkeit wichtig ist. Ich würde mich freuen, wenn wir uns zehn Minuten ohne Handy unterhalten.“</li><li>„Ich bin gestresst, wenn dein Teil erst am Abgabetag um 22 Uhr kommt statt wie vereinbart am Vortag, weil ich Zeit brauche, alles zusammenzufügen. Ich würde mich freuen, wenn du mir Bescheid gibst, sobald sich etwas verzögert.“</li><li>„Ich bin abgelenkt und angespannt, wenn ich während der Lernzeit am Nachmittag viele Nachrichten bekomme, weil ich Konzentration brauche. Mir wäre lieber, wenn wir uns abends schreiben.“</li><li>„Ich ärgere mich und fühle mich unsicher, wenn meine Vorschläge im Meeting mit ‚Das bringt nichts‘ beantwortet werden, weil mir Respekt und Mitsprache wichtig sind. Ich würde mir wünschen, dass wir Vorschläge erst sammeln und dann besprechen.“</li></ol>Achtung bei 4: „Ich finde, du bist …“ beginnt mit Ich, bleibt aber ein Urteil (verkappte Du-Botschaft)." },
   { id: "kxr5", topic: "k-zuh", title: "Selbstübung: Aktives Zuhören statt Gesprächsblocker",
     html: "Ein Freund erzählt: „Seit dem Teamwechsel sagt mir keiner mehr, was los ist. Ich erfahre alles als Letzter.“<ol><li>Benenne bei den Reaktionen (a)–(d) das Problem.</li><li>Formuliere drei Antworten im Sinne des aktiven Zuhörens (Zusammenfassen, Gefühl/Bedürfnis spiegeln, Ermutigen).</li></ol>(a) „Dann frag halt selber nach.“ (b) „Ach, das bildest du dir ein.“ (c) „Bei mir in der Firma war das genauso, da hab ich …“ (d) „Dein neuer Chef ist halt unfähig.“",
     solution: "<ol><li>(a) Ratschlag/Lösung anbieten – nimmt das Gefühl nicht wahr. (b) Bagatellisieren/Widersprechen – das Erleben wird abgesprochen. (c) Thema auf sich lenken – eigene Geschichte statt Zuhören. (d) Urteil/Diagnose über Dritte – heizt an, statt zu verstehen.</li><li><b>Zusammenfassen:</b> „Du bekommst Informationen im neuen Team erst spät mit?“<br><b>Spiegeln:</b> „Das klingt, als wärst du frustriert und ein bisschen außen vor – ist dir wichtig, dazuzugehören und informiert zu sein?“<br><b>Ermutigen:</b> „Magst du mir ein Beispiel erzählen, wann das zuletzt so war?“</li></ol>Dazu nonverbal: Blickkontakt, Nicken, zugewandte Haltung, Pausen aushalten; die eigene Meinung zurückstellen und auf Bestätigung warten." },
   { id: "kxr6", topic: "k-zuh", title: "Selbstübung: Deep-Talk-Gespräch vorbereiten",
     html: "Bereite ein Übungsgespräch vor (nicht das Abgabeblatt – das füllst du selbst nach echten Gesprächen aus):<ol><li>Formuliere zwei offene, persönliche Einstiegsfragen.</li><li>Dein Gegenüber antwortet: „Am meisten stolz bin ich darauf, dass ich nach der Lehre noch studiere, obwohl mir das keiner zugetraut hat.“ Formuliere eine Vermutung zu Gefühl und Bedürfnis als Frage.</li><li>Die Person korrigiert: „Stolz schon, aber eigentlich geht's mir darum, mir selbst was zu beweisen.“ Wie reagierst du?</li><li>Was notierst du direkt danach?</li></ol>",
     solution: "<ol><li>z. B. „Worauf bist du in deinem Leben besonders stolz?“ · „Was hat dich in letzter Zeit richtig berührt?“ – offen (keine Ja/Nein-Fragen), persönlich, ohne Bewertung.</li><li>„Bist du stolz und vielleicht auch erleichtert, weil dir Anerkennung wichtig ist – dass andere sehen, was du kannst?“</li><li>Die Korrektur dankbar aufnehmen und erneut spiegeln: „Also ist dir vor allem wichtig, dir selbst zu zeigen, dass du es schaffst – Selbstwirksamkeit, unabhängig davon, was andere denken?“ – und auf Bestätigung warten. Eine Korrektur ist kein Fehler, sondern führt zum eigentlichen Bedürfnis.</li><li>Frage, Antwort in Stichworten, vermutetes Gefühl und Bedürfnis, bestätigt/korrigiert, eigene Beobachtung (was fiel mir schwer?). Direkt notieren, nicht aus dem Gedächtnis nachbauen.</li></ol>" },
   { id: "kxr7", topic: "k-svt", title: "Selbstübung: Analyse eines Missverständnisses (Vier Ohren + Axiome)",
     html: "Erfundener Dialog in einer Lerngruppe:<br>Anna (schaut auf die Uhr): „Es ist schon halb acht.“<br>Ben (verschränkt die Arme): „Ja, ich weiß, ich war zu spät. Du musst nicht jedes Mal darauf herumreiten.“<br>Anna: „Ich hab doch gar nichts gesagt!“<ol><li>Analysiere Annas Satz mit den vier Seiten. Mit welchem Ohr hört Ben?</li><li>Welche Axiome Watzlawicks erkennst du?</li><li>Wie könnten beide das Gespräch klären?</li></ol>",
     solution: "<ol><li>Sachinhalt: Es ist 19:30. Selbstkundgabe: Ich bin müde/unter Zeitdruck. Beziehung: (möglich) Du hast uns aufgehalten. Appell: Lasst uns anfangen/schneller machen. Ben hört mit dem <b>Beziehungsohr</b> (Vorwurf) – daher die Rechtfertigung.</li><li><b>Axiom 1</b>: Der Blick auf die Uhr kommuniziert mit, auch wenn Anna „nichts gesagt“ hat. <b>Axiom 2</b>: Die Beziehung (früheres Zuspätkommen) bestimmt, wie der Inhalt verstanden wird. <b>Axiom 4</b>: digital „halb acht“, analog Uhrblick/verschränkte Arme. <b>Axiom 3</b>, falls es sich wiederholt: „Ich rechtfertige mich, weil du kritisierst“ / „Ich werde ungeduldig, weil du zu spät kommst“.</li><li>Metakommunikation: Anna erklärt ihre Selbstkundgabe („Ich bin heute müde und will um neun fertig sein“); Ben fragt nach statt sich zu verteidigen („Hast du das als Kritik an mir gemeint?“). Beide formulieren Ich-Botschaften und eine konkrete Bitte zum Zeitplan.</li></ol>" },
   { id: "kxr8", topic: "k-harv", title: "Selbstübung: Verhandeln nach Harvard",
     html: "Erfundene Situation: Zwei Studierende teilen sich ein Auto. Mia will es am Samstag den ganzen Tag (Position), Tom auch.<ol><li>Welche Interessen könnten hinter den Positionen stehen? Wie findest du sie heraus?</li><li>Entwickle mindestens drei Optionen.</li><li>Bestimme BATNA und WATNA für Mia.</li><li>Welches objektive Kriterium könnte helfen, falls keine Option für beide passt?</li></ol>",
     solution: "<ol><li>Mit W-Fragen: „Wofür brauchst du das Auto? Wann genau? Was ist dir daran wichtig?“ – z. B. Mia: Großeinkauf für eine Feier am Vormittag (Transport von viel Gepäck); Tom: Fahrt zu einem Konzert am Abend (Flexibilität, kein Nachtbus).</li><li>Mia bekommt das Auto bis 14 Uhr, Tom danach · Tom fährt Mia beim Einkauf mit und nimmt danach das Auto · Mia lässt liefern, Tom übernimmt dafür die Tankkosten · einer leiht ein Carsharing-Auto, die Kosten werden geteilt.</li><li><b>BATNA</b> (Mia, beste Alternative ohne Einigung): z. B. Carsharing für drei Stunden mieten. <b>WATNA</b> (schlechtestes realistisches Szenario): Einkauf mit Öffis in mehreren Fahrten, Feier verspätet vorbereitet. Je besser die BATNA, desto gelassener kann Mia verhandeln.</li><li>z. B. Abwechselprinzip nach Kalender, wer zuletzt das Auto hatte, Losentscheid oder Kostenteilung nach gefahrenen Kilometern – fair und von beiden anerkennbar.</li></ol>Grundsatz: hart in der Sache, weich zu den Menschen – Person und Problem trennen." }
  ]
};
})();
