/* Prüfungsvorbereitung GL-UFO – aus studentischem Fragenkatalog „GL_UFO_Prüfungsvorbereitung“ (Frage + Antwort je Kapitel, 10 Folienabbildungen: Five Forces, Nachhaltigkeitsdreieck, Vision, Kulturwandel, Board-/AG-/GmbH-Verfassung, Analyse-Schema, Formen der Planung) */
(function () {
const c = (window.COURSE_DEFS || []).find(x => x.id === "ufo"); if (!c) return;

Object.assign(c.topics, {
  "ufx-ethik": { name: "Werte, Ethik, Nachhaltigkeit & Kultur", lesson: "ufx-1" },
  "ufx-verfassung": { name: "Unternehmensverfassung & Corporate Governance", lesson: "ufx-2" },
  "ufx-pm": { name: "Projektmanagement", lesson: "ufx-3" },
  "ufx-skalierung": { name: "Unternehmensskalierung", lesson: "ufx-4" }
});

c.worlds.push({ id: "ufxw", n: 7, title: "Prüfungstraining: Lücken aus dem Fragenkatalog", sub: "Ethik & Nachhaltigkeit, Verfassung, Projekte, Skalierung", boss: null, lessons: [
 { id: "ufx-1", title: "Unternehmenswerte, Ethik, Nachhaltigkeit & Kulturwandel", topic: "ufx-ethik", min: 12, xp: 0, blocks: [
  { t: "lead", html: "Die normative Führung besteht aus fünf Elementen: <b>Werte</b> (Ethik, Philosophie) → <b>Ziele</b> (Vision, Politik) → <b>Kultur</b>, <b>Verfassung</b> → zusammengefasst in der <b>Mission</b>." },
  { t: "text", h: "Unternehmensphilosophie und Unternehmensethik", levels: {
    simple: "Die Philosophie sind die Grundüberzeugungen eines Unternehmens. Die Ethik ist der moralische Teil davon: Was ist erlaubt und richtig, nicht nur was bringt Geld?",
    normal: "<b>Unternehmensphilosophie</b> = grundlegende Einstellungen und Überzeugungen eines Unternehmens; sie bilden die Werte, die Denken und Handeln aller Mitarbeitenden beeinflussen (oft unausgesprochen und unreflektiert). <b>Unternehmensethik</b> = Teil der Philosophie mit den <b>moralischen Maßstäben</b>; sie <b>legitimiert</b> das Handeln und beschreibt die moralische und gesellschaftliche Verantwortung. Sie reflektiert Werte danach, was <b>ökonomisch relevant und moralisch legitim</b> ist, und erweitert die betriebswirtschaftliche Rationalität um ethische Belange. In der Marktwirtschaft steht Wirtschaften immer im <b>Spannungsfeld Moral vs. Ökonomie</b>.<br><br><b>Typen nach ethischem Verhalten</b> (aufsteigend): <ol><li><b>Unmoralisch</b> – bewusste Regelverstöße (Bilanzfälschung, Abgasskandal)</li><li><b>Legalistisch</b> – nur was das Gesetz verlangt, Gesetzeslücken werden genutzt (Cum-Ex)</li><li><b>Ethisch reaktiv</b> – Ethik nur, wenn es nützt/Druck entsteht (opportunistisch)</li><li><b>Ethisch engagiert</b> – aktives Bemühen um ethisches Handeln</li><li><b>Ethisch</b> – Ethik fest in Kultur und Entscheidungen verankert</li></ol>",
    technical: "Werteorientierte Unternehmensführung stützt sich auf <b>Humanismus</b> (Nachhaltigkeit, Respekt, Kooperation, Goldene Regel), <b>Wirtschaftlichkeit</b> (Überleben, Gewinn), <b>Professionalität</b> (sachrichtige, optimale Leistung für Kunden) und <b>Glaubwürdigkeit</b> (Übereinstimmung von Reden und Handeln). Umsetzung: Konfliktlösung, <b>Kodifizierung</b> der Werte (Ethikkodex / Code of Ethics), Systeme zur Durchsetzung (<b>Compliance</b>) und <b>Corporate Social Responsibility</b>." } },
  { t: "text", h: "Nachhaltige Unternehmensführung", levels: {
    simple: "Nachhaltig heißt: Geld verdienen, aber ohne Umwelt und Menschen zu schaden – damit es auch künftigen Generationen gut geht.",
    normal: "Nachhaltige Unternehmensführung verfolgt <b>gleichermaßen ökonomische, ökologische und soziale Ziele</b> (Wert-, Sozial- und Naturorientierung) und strebt <b>inter- und intragenerationelle Gerechtigkeit</b> an: Ressourcen werden so genutzt, dass die heutige Lebensqualität auch künftig zumindest erhalten bleibt.<br><b>Nachhaltigkeitsdreieck</b>: Ecken = ökonomische, ökologische, soziale <b>Effektivität</b>; Verbindungen: <b>Öko-Effizienz</b> (Ökonomie ↔ Ökologie) und <b>Sozio-Effizienz</b> (Ökonomie ↔ Soziales).",
    technical: "Effektivität = die richtigen Dinge tun (Zielerreichung in einer Dimension), Effizienz = Verhältnis zwischen den Dimensionen, z. B. Öko-Effizienz = Wertschöpfung je Umweltbelastung. Triple Bottom Line (Elkington): People, Planet, Profit." } },
  { t: "text", h: "Unternehmenskultur und Kulturwandel", levels: {
    simple: "Kultur ist, „wie man es bei uns eben macht“. Sie ändert sich meist erst, wenn es eine Krise gibt.",
    normal: "<b>Unternehmenskultur</b> = Gesamtheit der vorherrschenden Wertvorstellungen, Traditionen, Überlieferungen, Mythen und Denkhaltungen, die das Verhalten der Mitarbeitenden prägen. Sie wirkt auf Sprache, Rituale, Kleidung, Umgangsformen, Verhaltensrichtlinien, Verbote, Einstellungen und Werte.<br><b>Typischer Verlauf eines Kulturwandels</b> (Kreislauf):<ol><li>Bisherige Handlungsmuster führen in die <b>Krise</b></li><li><b>Verunsicherung</b> kommt auf; Symbole und Riten werden unglaubwürdig</li><li><b>Schattenkulturen</b> treten hervor; neue Orientierungsmuster entstehen</li><li>Alte und neue Kultur im <b>Konflikt</b></li><li><b>Akzeptanz</b> erfolgreicher Verhaltensmuster, Ablehnung anderer</li><li><b>Entfaltung</b> der neuen Kultur; Symbole, Normen, Standards entwickeln sich</li></ol>Kultur + Werte + Ziele + Verfassung → <b>Mission</b> (angestrebtes Selbstbild). Die gelebte Kultur ist das umgesetzte Selbstbild = <b>Corporate Identity</b> (Corporate Behaviour, Corporate Design, Corporate Communication).",
    technical: "Kultur lässt sich nur begrenzt direkt steuern (Schein: Artefakte – Werte – Grundannahmen). Hebel: Vorbild der Führung, Personalauswahl, Anreize, Symbole/Geschichten, Strukturen." } },
  { t: "widget", w: "sorter", topic: "ufx-ethik", title: "Welcher Ethik-Typ?", cats: [{ k: "u", label: "unmoralisch" }, { k: "l", label: "legalistisch" }, { k: "r", label: "ethisch reaktiv" }, { k: "e", label: "ethisch engagiert / ethisch" }], items: [
    { t: "Manipulierte Abgaswerte bei Diesel-Fahrzeugen", a: "u", why: "Bewusster Rechtsbruch." },
    { t: "Steuerkonstruktion, die eine Gesetzeslücke ausnutzt (Cum-Ex)", a: "l", why: "Formal (vermeintlich) legal, moralisch nicht legitim." },
    { t: "Lieferkettenkontrolle erst nach einem Medienskandal", a: "r", why: "Reagiert opportunistisch auf Druck." },
    { t: "Freiwilliger Ethikkodex, gelebte Werte in allen Entscheidungen", a: "e", why: "Ethik ist aktiv verankert." },
    { t: "Gefälschte Bilanz zur Täuschung von Investoren", a: "u", why: "Bewusste Täuschung." }
  ] },
  { t: "check", q: "Was verbindet im Nachhaltigkeitsdreieck die ökonomische mit der ökologischen Dimension?", opts: ["Sozio-Effizienz", "Öko-Effizienz", "Öko-Effektivität", "Corporate Governance"], a: 1, why: "Öko-Effizienz = Ökonomie ↔ Ökologie; Sozio-Effizienz = Ökonomie ↔ Soziales." },
  { t: "keys", items: ["Philosophie = Grundüberzeugungen; Ethik = moralische Maßstäbe, legitimiert Handeln", "Fünf Ethik-Typen: unmoralisch, legalistisch, ethisch reaktiv, ethisch engagiert, ethisch", "Nachhaltigkeit = ökonomisch + ökologisch + sozial, inter- und intragenerationelle Gerechtigkeit", "Kulturwandel beginnt mit einer Krise und endet mit der Entfaltung der neuen Kultur", "Corporate Identity = Behaviour + Design + Communication"] }
 ] },
 { id: "ufx-2", title: "Unternehmensverfassung, Corporate Governance & Compliance", topic: "ufx-verfassung", min: 10, xp: 0, blocks: [
  { t: "lead", html: "Die <b>Unternehmensverfassung</b> bestimmt die <b>Organe</b> eines Unternehmens sowie deren <b>Rechte und Pflichten</b>." },
  { t: "html", html: "<table class=\"dt\"><tr><th>Form</th><th>Organe</th><th>Kernmerkmal</th></tr><tr><td><b>Board-Verfassung (USA)</b></td><td>Shareholders' Meeting → Board of Directors (Managing + Outside Directors)</td><td><b>Monistisch</b>: Leitung und Überwachung in einem Organ (Verwaltungsrat)</td></tr><tr><td><b>AG (deutsch)</b></td><td>Hauptversammlung → Aufsichtsrat → Vorstand</td><td><b>Dualistisch</b>: Aufsichtsrat überwacht, Vorstand leitet; HV wählt AR (außer Arbeitnehmervertreter)</td></tr><tr><td><b>GmbH (deutsch)</b></td><td>Gesellschafterversammlung → (optional Beirat) → Geschäftsführung</td><td>Gesellschafter bestellen/berufen Geschäftsführer ab, stellen Jahresabschluss fest; Beirat berät/überwacht freiwillig</td></tr><tr><td><b>Familienunternehmen</b></td><td>Eigentümer:innen in der Führung</td><td>langfristige Orientierung, kurze Entscheidungswege, Flexibilität, Kontinuität; Rechtfertigung gegenüber der Öffentlichkeit hat geringen Stellenwert</td></tr></table>" },
  { t: "text", h: "Rechte der Aktionäre und Kompetenzen der Organe", levels: {
    simple: "Aktionäre besitzen das Unternehmen, führen es aber nicht selbst. Sie wählen Leute, die kontrollieren, und diese bestimmen die Manager.",
    normal: "<b>Aktionärsrechte</b>: Teilnahme, Auskunft, Stimmrecht, Anfechtungsrecht, Dividendenanspruch, Teilnahme an Liquidationserlösen.<br><b>Deutsche AG</b>: Die <b>Hauptversammlung</b> wählt und beruft die Aufsichtsratsmitglieder ab (Ausnahme: Arbeitnehmervertreter, Mitbestimmung). Der <b>Aufsichtsrat</b> bestellt und beruft den <b>Vorstand</b> ab, beschließt über besondere Angelegenheiten (zustimmungspflichtige Geschäfte) und überwacht die Geschäftsführung. Vorstand berichtet an AR, AR an HV.<br><b>US-Board</b>: Shareholders' Meeting bestellt das Board, beschließt über besondere Angelegenheiten und den Gründungsvertrag; das Board vereint geschäftsführende (<b>Managing</b>) und nicht geschäftsführende (<b>Outside</b>) Directors.<br><b>GmbH</b>: Gesellschafterversammlung stellt Jahresabschluss und Ergebnisverwendung fest, bestellt/beruft Geschäftsführer ab, ändert Geschäftsanteile, regelt Prüfung/Überwachung; Geschäftsführung übernimmt Außenvertretung, Unternehmensführung, Buchführung und Geschäftsbericht.",
    technical: "In Österreich gilt dasselbe dualistische Prinzip (AktG: Vorstand, Aufsichtsrat, Hauptversammlung; GmbHG: Generalversammlung, Geschäftsführer, Aufsichtsrat ab bestimmten Schwellen). Die SE kann monistisch oder dualistisch verfasst sein." } },
  { t: "text", h: "Corporate Governance und Compliance", levels: {
    simple: "Corporate Governance = Regeln für gute, verantwortungsvolle Leitung und Kontrolle. Compliance = dafür sorgen, dass alle Gesetze und Regeln eingehalten werden.",
    normal: "<b>Corporate Governance</b> beschreibt Grundsätze ordnungsgemäßer und verantwortungsvoller Unternehmensführung – den Rahmen für <b>Leitung und Überwachung</b> eines Unternehmens (z. B. Corporate-Governance-Kodex). Instrument ist das <b>interne Kontrollsystem</b> mit <b>Risikomanagement, Revision und Compliance</b>.<br><b>Compliance</b> = Gesamtheit der Grundsätze und Maßnahmen zur <b>Einhaltung von Gesetzen, Richtlinien und freiwilligen Kodizes</b>, um Regelverstöße im Unternehmen zu vermeiden.",
    technical: "Hintergrund: Principal-Agent-Problem zwischen Eigentümern und Management (Trennung von Eigentum und Verfügungsgewalt) – Governance-Mechanismen sollen Informationsasymmetrie und Interessenkonflikte begrenzen." } },
  { t: "widget", w: "pairs", topic: "ufx-verfassung", title: "Organ zuordnen", pairs: [["Hauptversammlung", "wählt Aufsichtsrat (außer AN-Vertreter)"], ["Aufsichtsrat", "bestellt und überwacht den Vorstand"], ["Vorstand", "leitet die AG eigenverantwortlich"], ["Board of Directors", "Leitung und Überwachung in einem Organ"], ["Gesellschafterversammlung", "bestellt Geschäftsführer der GmbH"], ["Beirat", "freiwillige Beratung/Überwachung der GmbH-Geschäftsführung"]] },
  { t: "check", q: "Wer bestellt in der deutschen AG den Vorstand?", opts: ["Die Hauptversammlung", "Der Aufsichtsrat", "Der Betriebsrat", "Der Vorstandsvorsitzende"], a: 1, why: "HV → wählt AR; AR → bestellt/beruft Vorstand ab und überwacht ihn." }
 ] },
 { id: "ufx-3", title: "Projektmanagement & Multiprojektmanagement", topic: "ufx-pm", min: 8, xp: 0, blocks: [
  { t: "lead", html: "Ein <b>Projekt</b> ist ein <b>einmaliges, zeitlich begrenztes und komplexes</b> Vorhaben, für das mehrere Mitarbeitende aus unterschiedlichen Organisationseinheiten nötig sind." },
  { t: "text", h: "Bausteine und Erfolgsfaktoren", levels: {
    simple: "Projekte werden definiert, geplant, kontrolliert und abgeschlossen. Erfolg heißt: Leistung, Zeit und Kosten passen.",
    normal: "<b>Bausteine</b> des Projektmanagements: Projektdefinition, Projektplanung, Projektkontrolle/-steuerung, Projektabschluss, Projektunterstützung – funktional: Führung, Zielsetzung, Organisation, Planung, Kontrolle &amp; Steuerung.<br><b>Erfolgskritisch</b> ist das <b>magische Dreieck</b>: <b>Leistung</b> (Qualität/Funktionalität), <b>Zeit</b> (Termine), <b>Einsatzmittel</b> (Kosten/Ressourcen) – die drei Größen beeinflussen sich gegenseitig.<br><b>Viele parallele Projekte</b> → <b>Multiprojekt- bzw. Projektportfoliomanagement</b>: Projekte nach strategischem Beitrag bewerten und <b>priorisieren</b>, knappe Ressourcen projektübergreifend planen und zuteilen, Abhängigkeiten koordinieren, laufend über ein Projektportfolio-Controlling (oft durch ein <b>Project Management Office</b>) steuern, Projekte notfalls stoppen.",
    technical: "Projektorganisationsformen: reine (autonome) Projektorganisation, Stabs-/Einfluss-Projektorganisation, Matrix-Projektorganisation – Wahl je nach Größe, Bedeutung und Dauer des Projekts." } },
  { t: "check", q: "Welche drei Größen bilden das Projektmanagement-Dreieck?", opts: ["Leistung, Zeit, Einsatzmittel", "Vision, Mission, Leitbild", "Planung, Organisation, Personal", "Kunden, Finanzen, Prozesse"], a: 0, why: "Leistung/Qualität, Zeit/Termine, Einsatzmittel/Kosten." }
 ] },
 { id: "ufx-4", title: "Unternehmensskalierung", topic: "ufx-skalierung", min: 8, xp: 0, blocks: [
  { t: "lead", html: "<b>Skalierung</b> = Wachstum des Geschäfts (v. a. Umsatz), idealerweise ohne dass Kosten und Komplexität im gleichen Maß steigen." },
  { t: "html", html: "<table class=\"dt\"><tr><th>Weg</th><th>Vorteil</th><th>Nachteil</th></tr><tr><td>Organisches Wachstum</td><td>nachhaltig, geringes Risiko</td><td>langsam</td></tr><tr><td>Akquisitionen</td><td>schnelles Wachstum</td><td>hoher Kapitalbedarf, hohes Risiko</td></tr><tr><td>Partnerschaften</td><td>schnelle Skalierung</td><td>Qualitätsrisiko</td></tr><tr><td>Franchising</td><td>sehr hohe Skalierbarkeit</td><td>geringeres Einkommenspotenzial</td></tr></table>" },
  { t: "keys", items: ["<b>Gründe</b>: höhere Marktanteile, Effizienzsteigerung (Skaleneffekte), Erweiterung von Produkten/DL, Marktnachfrage bedienen → Umsatzwachstum", "<b>Herausforderungen</b>: Verlust der Agilität, erhöhte Komplexität, finanzielle Herausforderungen, kulturelle Veränderungen", "<b>Nachhaltige Skalierung</b>: Geschäftsprozesse verbessern, Technologie integrieren, Talente entwickeln, Kunden binden"] },
  { t: "widget", w: "pairs", topic: "ufx-skalierung", title: "Skalierungsweg und Nachteil", pairs: [["Organisches Wachstum", "langsam"], ["Akquisition", "Kapitalbedarf und hohes Risiko"], ["Partnerschaft", "Qualitätsrisiko"], ["Franchising", "geringeres Einkommenspotenzial"]] },
  { t: "check", q: "Ein Start-up will in 12 Monaten in 5 neuen Ländern präsent sein, hat aber wenig Kapital. Welcher Weg passt am besten?", opts: ["Akquisition lokaler Wettbewerber", "Organisches Wachstum mit eigenen Filialen", "Franchising bzw. Partnerschaften", "Rückwärtsintegration"], a: 2, why: "Franchising/Partnerschaften skalieren schnell mit fremdem Kapital; Akquisitionen brauchen viel Kapital, organisch ist langsam." }
 ] }
] });

// Antwortpositionen deterministisch rotieren, damit die richtige Option nicht immer an derselben Stelle steht (Richtig/Falsch bleibt fix)
const Q = (id, topic, q, opts, a, why) => { const n = opts.length, k = n > 2 ? (id * 7) % n : 0; const o = opts.map((_, i) => opts[(i + k) % n]);
  return { id: "ufx-q" + id, topic, q, opts: o, a: (a - k + n) % n, why, alt: true, src: "Fragenkatalog" }; };
c.questions.push(
 // Grundbegriffe
 Q(1, "ufo-begriffe", "Welche Definition beschreibt ein Unternehmen korrekt?", ["Eine spontane Gruppe von Personen, die Güter für den Eigenbedarf erzeugt", "Eine planvoll organisierte Wirtschaftseinheit, die durch Kombination von Produktionsfaktoren Güter und Dienstleistungen über den eigenen Bedarf hinaus herstellt und absetzt", "Jede öffentliche Einrichtung, die Steuern einnimmt", "Ein Zusammenschluss von Kapitalgebern ohne eigene Leistungserstellung"], 1, "Kernelemente: planvoll organisiert, Faktorkombination, Fremdbedarfsdeckung (über den eigenen Bedarf hinaus)."),
 Q(2, "ufo-begriffe", "Führung im funktionalen Sinn umfasst …", ["nur die Personen der obersten Hierarchieebene", "alle Aufgaben und Handlungen zur zielorientierten Gestaltung, Lenkung und Entwicklung einer Organisation", "ausschließlich die Mitarbeiterführung", "die rechtliche Vertretung nach außen"], 1, "Funktional = Aufgaben/Handlungen; institutionell = Personen, die führen."),
 Q(3, "ufo-ebenen", "Welche Aussage zur Unternehmensführung je Führungsebene ist richtig?", ["Normativ: Planung, Steuerung und Kontrolle der laufenden Aktivitäten", "Strategisch: Entwicklung bestehender und Erschließung neuer Erfolgspotenziale", "Operativ: Festlegung von Werten und Unternehmensverfassung", "Strategisch: Identität des Unternehmens in Werten und Normen"], 1, "Normativ = Identität (Werte, Ziele, Normen); strategisch = Erfolgspotenziale; operativ = effektive Nutzung der bestehenden Potenziale im laufenden Geschäft."),
 // Theorien
 Q(4, "ufo-io", "Welche drei Theorien der Unternehmensführung werden im Fragenkatalog/der VL vertieft?", ["Taylorismus, Fordismus, Toyotismus", "Industrieökonomie, ressourcenorientierter Ansatz, Systemtheorie", "Maslow, Herzberg, McGregor", "Kontingenztheorie, Spieltheorie, Chaostheorie"], 1, "Market-based View (Industrieökonomie), Resource-based View, Systemtheorie (St. Galler Modell)."),
 Q(5, "ufo-io", "Welche Theorie erklärt am besten, warum Unternehmen überhaupt entstehen?", ["Die Transaktionskostentheorie: Leistungen werden im Unternehmen (Hierarchie) koordiniert, wenn das günstiger ist als über den Markt", "Die Maslow'sche Bedürfnispyramide", "Das BCG-Portfolio", "Das Gegenstromverfahren"], 0, "Coase/Williamson (Neue Institutionenökonomie): Unternehmen existieren, weil Markttransaktionen Kosten verursachen (Anbahnung, Vereinbarung, Kontrolle …); ist interne Koordination billiger, wird integriert."),
 Q(6, "ufo-io", "Das Structure-Conduct-Performance-Paradigma der Industrieökonomie besagt, …", ["dass Ressourcen das Verhalten bestimmen", "dass die Branchenstruktur das Verhalten der Unternehmen und dieses ihren Erfolg bestimmt", "dass Kultur der Strategie folgt", "dass Erfolg vom Führungsstil abhängt"], 1, "Structure (Branche) → Conduct (Verhalten/Strategie) → Performance (Erfolg); Analysewerkzeug: Porters Five Forces."),
 Q(7, "ufo-rbv", "Der ressourcenorientierte Ansatz folgt welchem Paradigma?", ["Structure-Conduct-Performance", "Resources-Conduct-Performance", "Strategy-Structure-Process", "Plan-Do-Check-Act"], 1, "Unternehmensinterne Ressourcen (statt Branchenstruktur) bestimmen Verhalten und Erfolg – Inside-out-Perspektive."),
 Q(8, "ufo-system", "Welchen praktischen Beitrag liefert die Systemtheorie für die Unternehmensführung?", ["Branchenstrukturanalyse mit Five Forces", "Steuerungs-, Regelungs- bzw. Lenkungsprinzip und das St. Galler Management-Modell", "Die Ansoff-Matrix", "Das Business Model Canvas"], 1, "Systemtheorie → Kybernetik (Steuerung, Regelung, Lenkung) und ganzheitliches St. Galler Modell; Five Forces gehören zur Industrieökonomie."),
 // Five Forces
 Q(9, "ufo-stratana", "Welcher Faktor <b>erhöht</b> die Verhandlungsmacht der Lieferanten?", ["Viele kleine Lieferanten", "Hoch standardisierte, leicht austauschbare Produkte", "Wenige Lieferanten (hoher Konzentrationsgrad) und Möglichkeit der Vorwärtsintegration", "Die Branche ist für die Lieferanten sehr wichtig"], 2, "Je weniger Lieferanten und je eher sie selbst vorwärts integrieren können, desto größer ihre Macht. Ist die Branche für die Lieferanten wichtig, sinkt ihre Macht."),
 Q(10, "ufo-stratana", "Die Möglichkeit der <b>Rückwärtsintegration</b> stärkt in Porters Five Forces die Macht …", ["der Lieferanten", "der Abnehmer", "der Substitute", "der neuen Anbieter"], 1, "Abnehmer, die selbst die Vorstufe übernehmen könnten, verhandeln stärker; Vorwärtsintegration stärkt dagegen die Lieferanten."),
 Q(11, "ufo-stratana", "Welche ist <b>keine</b> Markteintrittsbarriere laut Five-Forces-Schema?", ["Economies of Scale", "Kapitalbedarf", "Zugang zu Vertriebskanälen", "Hohes Branchenwachstum"], 3, "Barrieren: Skaleneffekte, Produktdifferenzierung, Kapitalbedarf, Kostennachteile, Vertriebskanäle, staatliche Politik (+ erwartete Reaktion der Etablierten). Wachstum beeinflusst den Rivalitätsgrad (hohes Wachstum senkt ihn)."),
 Q(12, "ufo-stratana", "Welcher Umstand <b>verstärkt</b> die Rivalität unter den etablierten Wettbewerbern?", ["Starkes Branchenwachstum", "Hohe Produktdifferenzierung", "Hohe Überschusskapazitäten und hohe Austrittsbarrieren", "Wenige, ungleich große Wettbewerber"], 2, "Rivalität steigt bei geringem Wachstum, geringer Differenzierung, Überkapazitäten, hohen Austrittsbarrieren und konkurrierenden Geschäftslogiken."),
 // Ebenen & Funktionen
 Q(13, "ufo-ebenen", "Welche Zuordnung von Führungsebene und Hierarchie entspricht dem Fragenkatalog?", ["Normativ – untere Ebene, operativ – obere Ebene", "Normativ – obere, strategisch – mittlere, operativ – untere Führungsebenen", "Alle drei Ebenen werden ausschließlich vom Vorstand wahrgenommen", "Strategisch – untere, operativ – mittlere Ebene"], 1, "Schwerpunktmäßig: oben normativ, Mitte strategisch, unten operativ (Dreiecksdarstellung)."),
 Q(14, "ufo-prozess", "Welche drei Führungsfunktionen nennt der Fragenkatalog?", ["Beschaffung, Produktion, Absatz", "Personal, Planung & Kontrolle, Organisation", "Vision, Mission, Leitbild", "Finanzen, Kunden, Prozesse"], 1, "Führungsfunktionen: Planung & Kontrolle, Organisation, Personal(führung) – verbunden durch Information."),
 Q(15, "ufo-prozess", "Wie hängen Ebenen und Funktionen im Führungssystem zusammen? Welche Aussage ist <b>falsch</b>?", ["Sie bauen hierarchisch aufeinander auf (Dreiecksform)", "Übergeordnete Ebenen bilden den Rahmen für die nachfolgenden", "Informationen verbinden Ebenen und Funktionen", "Die operative Ebene gibt den Rahmen für die normative Ebene vor"], 3, "Der Rahmen wird von oben gesetzt: normativ → strategisch → operativ, nicht umgekehrt."),
 Q(16, "ufo-planung", "Planung und Kontrolle bilden eine Einheit, weil …", ["Kontrolle ohne Planung unmöglich ist (kein Soll) und Planung ohne Kontrolle zwecklos ist", "beide immer von derselben Person durchgeführt werden müssen", "beide nur in der Buchhaltung stattfinden", "Kontrolle die Planung ersetzt"], 0, "Ohne Plan fehlt der Sollwert, ohne Kontrolle bleibt offen, ob der Plan wirkt."),
 // Normativ
 Q(17, "ufo-normativ", "Welche Aufgabe hat die normative Unternehmensführung?", ["Festlegung der Tagesproduktion", "Bestimmung der Identität des Unternehmens in Werten, Zielen, Verhaltensweisen und organisatorischen Normen, zusammengefasst in einer Mission", "Durchführung der Kostenstellenrechnung", "Auswahl einzelner Lieferanten"], 1, "Sie sichert Lebens- und Entwicklungsfähigkeit und definiert die Identität."),
 Q(18, "ufo-normativ", "Ordne die Elemente der normativen Führung richtig zu: Unternehmenskultur entspricht …", ["Ethik und Philosophie", "Vision und Politik", "Verhaltensnormen", "organisatorischen Normen"], 2, "Werte → Ethik/Philosophie; Ziele → Vision/Politik; Kultur → Verhaltensnormen; Verfassung → organisatorische Normen; Mission → Anspruch und Selbstbild."),
 Q(19, "ufo-normativ", "Die Unternehmensverfassung entspricht in der normativen Führung …", ["den Verhaltensnormen", "den organisatorischen Normen", "dem Selbstbild", "der Vision"], 1, "Verfassung = organisatorische Normen (Organe, Rechte, Pflichten)."),
 Q(20, "ufo-normativ", "Wie wirken die normativen Elemente zusammen?", ["Aus der Mission werden die Werte abgeleitet", "Aus den Werten werden die Ziele abgeleitet; Ziele sind Basis für Kultur, Verfassung und Mission; Kultur und Verfassung fließen in die Mission ein", "Alle Elemente sind voneinander unabhängig", "Die Verfassung legt die Werte fest"], 1, "Werte → Ziele → Kultur/Verfassung → Mission (angestrebtes Selbstbild)."),
 Q(21, "ufo-normativ", "Unternehmenspolitik …", ["entwickelt die Unternehmensziele durch politische Prozesse des Interessenausgleichs", "ist die staatliche Regulierung von Unternehmen", "bezeichnet die Lobbyarbeit gegenüber Parteien", "ist identisch mit der operativen Planung"], 0, "Ziele werden bei Interessenkonflikten (Stakeholder vs. Shareholder) durch Machtausübung und Ausgleich festgelegt."),
 Q(22, "ufo-normativ", "Was ist kennzeichnend für die Shareholder-Orientierung?", ["Alle Anspruchsgruppen sind gleichberechtigt", "Die Ziele der Eigentümer sind primäre Grundlage der Unternehmensführung", "Die Mitarbeitenden bestimmen die Ziele", "Kunden sind die einzige Bezugsgruppe"], 1, "Stakeholder-Orientierung berücksichtigt dagegen alle Gruppen mit Erwartungen an das Unternehmen (Kunden, Lieferanten, Staat, Fremdkapitalgeber …)."),
 Q(23, "ufo-normativ", "Welche Gruppe ist <b>kein</b> typischer Stakeholder eines Unternehmens?", ["Fremdkapitalgeber", "Lieferanten", "Staat", "Ein Unternehmen einer völlig anderen Branche ohne Beziehung zum Unternehmen"], 3, "Stakeholder stehen mit dem Unternehmen in Beziehung und haben Erwartungen an es."),
 Q(24, "ufo-normativ", "Welche Faktoren gehören zur Analyse der globalen Umwelt?", ["Kunden, Lieferanten, Substitute", "Politik/Recht, Gesellschaft, Ökonomie, Ökologie, Technik", "Stärken und Schwächen", "Finanzen, Kunden, Prozesse, Lernen"], 1, "Globale (Makro-)Umwelt; entspricht PESTEL. Kunden/Lieferanten gehören zur Branchenumwelt."),
 Q(25, "ufo-normativ", "Welche Eigenschaft gehört <b>nicht</b> zu den Anforderungen an eine Vision?", ["Richtungsweisend", "Anspornend", "Plausibel", "Detailliert operationalisiert mit Kennzahl und Termin"], 3, "Eine Vision ist richtungsweisend, anspornend, plausibel und prägnant; Kennzahl und Termin gehören zu (SMARTen) Zielen."),
 Q(26, "ufo-normativ", "Welche Funktionen erfüllt die Vision als Bindeglied der Führungsfunktionen (Personal, Organisation, Planung & Kontrolle)?", ["Kostensenkung, Rationalisierung, Automatisierung", "Fokussierung, Legitimation, Identifikation und Motivation", "Kontrolle, Sanktion, Überwachung", "Beschaffung, Produktion, Absatz"], 1, "Fokussierung (gemeinsame Zielsetzung), Legitimation (Sinn für alle Anspruchsgruppen), Identifikation/Motivation (Beitrag zum Ganzen)."),
 Q(27, "ufo-normativ", "„Wir steigern den Marktanteil in China bis Dezember um 5 % (verantwortlich: Leitung Vertrieb).“ Welche Zieldimensionen sind in dieser Formulierung <b>enthalten</b>?", ["Nur Inhalt", "Inhalt, Ausmaß, Termin, Verantwortung und Ort", "Nur Ausmaß und Termin", "Keine – es ist eine Vision"], 1, "Inhalt (Marktanteil), Ausmaß (5 %), Termin (Dezember), Verantwortung (Leitung Vertrieb), Ort (China) – vollständig formuliert."),
 Q(28, "ufo-normativ", "Wofür steht das „A“ in SMART laut Fragenkatalog?", ["Allgemein", "Anspruchsvoll bzw. akzeptiert", "Analytisch", "Aktuell"], 1, "Spezifisch, Messbar, Anspruchsvoll/Akzeptiert, Realistisch, Terminiert."),
 Q(29, "ufo-normativ", "Ein Ziel lautet: „Wir wollen besser werden.“ Welches SMART-Kriterium ist am offensichtlichsten verletzt?", ["Nur Realistisch", "Spezifisch, messbar und terminiert", "Nur Anspruchsvoll", "Keines"], 1, "Weder Inhalt noch Ausmaß noch Termin sind festgelegt."),
 Q(30, "ufo-normativ", "Was ist ein Leitbild?", ["Die Satzung der GmbH", "Die schriftliche Dokumentation wesentlicher Bestandteile der Unternehmensmission, intern und extern bekannt gemacht", "Das Organigramm", "Ein Budgetplan"], 1, "Ziel: Identifikation mit Unternehmen und Zielen fördern."),
 Q(31, "ufo-normativ", "Welche Funktion hat ein Leitbild <b>nicht</b>?", ["Orientierung", "Legitimation", "Motivation", "Rechtsverbindliche Festlegung der Organe"], 3, "Funktionen: Orientierung, Konkretisierung, Legitimation, Motivation. Organe regelt die Verfassung."),
 Q(32, "ufo-normativ", "Worin unterscheiden sich Mission und Leitbild?", ["Kein Unterschied", "Mission: Auftrag und Beitrag zur Gesellschaft, stärkere Kundenperspektive; Leitbild: Orientierung für Mitarbeitende, wirkt stärker nach innen", "Mission wirkt nur intern, Leitbild nur extern", "Leitbild ist ein Finanzplan"], 1, "Die Mission ist der Auftrag nach außen; das Leitbild dokumentiert Werte, Grundsätze und Ziele vor allem für die Mitarbeitenden."),
 Q(33, "ufo-normativ", "Welches Element gehört <b>nicht</b> zur Unternehmensmission im weiteren Sinn?", ["Zweck (warum es das Unternehmen gibt, Tätigkeitsfeld)", "Werte", "Kultur und Verfassung", "Die monatliche Kostenstellenauswertung"], 3, "Mission = Zweck + Werte + Ziele + Kultur + Verfassung als angestrebtes Selbstbild."),
 Q(34, "ufo-normativ", "Was beinhaltet die Unternehmenskultur?", ["Nur das Corporate Design (Logo, Farben)", "Die Gesamtheit vorherrschender Wertvorstellungen, Traditionen, Überlieferungen, Mythen und Denkhaltungen, die das Verhalten prägen", "Die rechtliche Verfassung", "Die Balanced Scorecard"], 1, "Corporate Design ist nur ein sichtbarer Teil der Corporate Identity."),
 // Ethik/Nachhaltigkeit/Kultur
 Q(35, "ufx-ethik", "Ein Unternehmen nutzt eine Gesetzeslücke für Steuererstattungen, die moralisch klar illegitim sind (Cum-Ex). Welcher Typ nach ethischem Verhalten liegt vor?", ["Unmoralisch", "Legalistisch", "Ethisch engagiert", "Ethisch"], 1, "Legalistisch: Es wird nur das gesetzlich Geforderte eingehalten, Lücken werden ausgenutzt."),
 Q(36, "ufx-ethik", "Welche Aussage zur Unternehmensethik ist richtig?", ["Sie ist mit Gewinnmaximierung identisch", "Sie legitimiert das Handeln und reflektiert, was ökonomisch relevant und moralisch legitim ist", "Sie betrifft nur gemeinnützige Organisationen", "Sie ist Teil der operativen Planung"], 1, "Ethik erweitert die betriebswirtschaftliche Rationalität um ethische Belange (Spannungsfeld Moral – Ökonomie)."),
 Q(37, "ufx-ethik", "Nachhaltige Unternehmensführung verfolgt …", ["nur ökologische Ziele", "gleichermaßen ökonomische, ökologische und soziale Ziele mit inter- und intragenerationeller Gerechtigkeit", "nur ökonomische Ziele mit grünem Marketing", "nur soziale Ziele"], 1, "Drei Dimensionen des Nachhaltigkeitsdreiecks."),
 Q(38, "ufx-ethik", "Im Nachhaltigkeitsdreieck verbindet die <b>Sozio-Effizienz</b> …", ["Ökologie und Soziales", "Ökonomie und Soziales", "Ökonomie und Ökologie", "Kultur und Verfassung"], 1, "Öko-Effizienz: Ökonomie ↔ Ökologie; Sozio-Effizienz: Ökonomie ↔ Soziales."),
 Q(39, "ufx-ethik", "Womit beginnt der typische Verlauf eines Kulturwandels?", ["Mit der Entfaltung der neuen Kultur", "Bisherige Handlungsmuster führen in die Krise", "Mit dem Konflikt zwischen alter und neuer Kultur", "Mit neuen Symbolen und Standards"], 1, "Krise → Verunsicherung → Schattenkulturen → Konflikt alt/neu → Akzeptanz → Entfaltung."),
 Q(40, "ufx-ethik", "In welcher Phase des Kulturwandels „treten Schattenkulturen hervor und neue Orientierungsmuster entstehen“?", ["Direkt nach der Verunsicherung, vor dem Konflikt alter und neuer Kultur", "Ganz am Ende", "Vor der Krise", "Nach der Entfaltung der neuen Kultur"], 0, "Reihenfolge: Krise → Verunsicherung → Schattenkulturen → Konflikt → Akzeptanz → Entfaltung."),
 Q(41, "ufx-ethik", "Corporate Identity (gelebtes Selbstbild) besteht aus …", ["Corporate Behaviour, Corporate Design, Corporate Communication", "Vision, Mission, Leitbild", "Compliance, Revision, Risikomanagement", "Kunden, Finanzen, Prozesse"], 0, "Die gelebte Kultur zeigt sich in Verhalten, Erscheinungsbild und Kommunikation."),
 Q(42, "ufx-ethik", "Ein Ethikkodex (Code of Ethics) dient vor allem …", ["der Bilanzierung", "der Kodifizierung der Unternehmenswerte zur besseren Umsetzung", "der Preisfestsetzung", "dem Ersatz der Unternehmensverfassung"], 1, "Werte werden schriftlich festgehalten und über Compliance-Systeme durchgesetzt."),
 // Verfassung
 Q(43, "ufx-verfassung", "Was regelt die Unternehmensverfassung?", ["Die Werbestrategie", "Die Organe eines Unternehmens sowie deren Rechte und Pflichten", "Die Produktionsplanung", "Die Unternehmenskultur"], 1, "Verfassung = organisatorische Normen."),
 Q(44, "ufx-verfassung", "Wodurch unterscheidet sich die US-Board-Verfassung von der deutschen AG?", ["Es gibt keine Aktionäre", "Leitung und Überwachung liegen in einem Organ (Board mit Managing und Outside Directors) – monistisch statt dualistisch (Vorstand + Aufsichtsrat)", "Der Board wird vom Staat ernannt", "Es gibt keine Berichtspflicht"], 1, "Monistisches Board vs. dualistisches System mit getrenntem Aufsichtsrat und Vorstand."),
 Q(45, "ufx-verfassung", "Wer wählt in der deutschen AG die Aufsichtsratsmitglieder (Ausnahme Arbeitnehmervertreter)?", ["Der Vorstand", "Die Hauptversammlung", "Der Betriebsrat", "Das Handelsgericht"], 1, "HV wählt/beruft AR ab; AR bestellt Vorstand."),
 Q(46, "ufx-verfassung", "Welche Aufgabe hat der Aufsichtsrat einer AG <b>nicht</b>?", ["Bestellung und Abberufung des Vorstands", "Überwachung der Geschäftsführung", "Beschlussfassung über besondere Angelegenheiten", "Laufende Führung des Tagesgeschäfts"], 3, "Das Tagesgeschäft führt der Vorstand eigenverantwortlich."),
 Q(47, "ufx-verfassung", "Welches Recht gehört <b>nicht</b> zu den Aktionärsrechten?", ["Stimmrecht", "Dividendenanspruch", "Anfechtungsrecht", "Weisungsrecht gegenüber einzelnen Mitarbeitenden"], 3, "Aktionärsrechte: Teilnahme, Auskunft, Stimmrecht, Anfechtung, Dividende, Liquidationserlös."),
 Q(48, "ufx-verfassung", "Welches Organ einer GmbH ist freiwillig und dient der Beratung und Überwachung der Geschäftsführung?", ["Gesellschafterversammlung", "Beirat", "Hauptversammlung", "Vorstand"], 1, "Der Beirat erhält von der Gesellschafterversammlung Regeln zur Prüfung/Überwachung."),
 Q(49, "ufx-verfassung", "Welches Merkmal ist typisch für Familienunternehmen?", ["Kurzfristige Quartalsorientierung", "Langfristige strategische Orientierung, kurze Entscheidungswege, hohe Flexibilität und Kontinuität", "Hohe Bedeutung der Rechtfertigung gegenüber der Öffentlichkeit", "Strikte Trennung von Eigentum und Führung"], 1, "Eigentümer:innen sind in die Führung eingebunden; öffentliche Rechtfertigung hat geringen Stellenwert."),
 Q(50, "ufx-verfassung", "Compliance bezeichnet …", ["die Gesamtheit der Grundsätze und Maßnahmen zur Einhaltung von Gesetzen, Richtlinien und freiwilligen Kodizes", "die Kundenzufriedenheit", "die Gewinnverwendung", "eine Wachstumsstrategie"], 0, "Teil des internen Kontrollsystems im Rahmen der Corporate Governance."),
 Q(51, "ufx-verfassung", "Welche Elemente umfasst das interne Kontrollsystem der Corporate Governance laut Katalog?", ["Risikomanagement, Revision, Compliance", "Marketing, Vertrieb, Service", "Vision, Mission, Leitbild", "Beschaffung, Produktion, Absatz"], 0, "Corporate Governance = Rahmen für Leitung und Überwachung; IKS = Risikomanagement, (interne) Revision, Compliance."),
 // Strategische Analyse
 Q(52, "ufo-stratana", "Welche Analysen gehören laut Analyseschema zu den <b>Umweltanalysen</b>?", ["Ressourcen-, Kompetenz- und Geschäftsmodellanalyse", "Branchen-, Markt-, Kunden- und Produktanalyse", "Nur die SWOT-Analyse", "Wertkettenanalyse und Kernkompetenzen"], 1, "Umwelt → Chancen und Risiken; Unternehmensanalysen (Ressourcen, Kompetenzen, Geschäftsmodell) → Stärken und Schwächen. Die Konkurrenzanalyse verbindet beide; alles mündet in die SWOT-Analyse."),
 Q(53, "ufo-stratana", "Welche Aussage ist eine <b>Chance</b> im Sinne der Umweltanalyse?", ["Veraltete Produktionsanlagen", "Ein neues Gesetz fördert die Nachfrage nach dem eigenen Produkt", "Hohe Mitarbeiterfluktuation", "Starke Marke"], 1, "Chancen/Risiken kommen von außen (Umwelt); Anlagen, Fluktuation und Marke sind interne Stärken/Schwächen."),
 Q(54, "ufo-stratana", "Warum werden Stärken und Schwächen immer <b>relativ</b> beurteilt?", ["Weil sie nur intern berechnet werden können", "Weil sie erst im Vergleich zu den wichtigsten Wettbewerbern bzw. zu den Kundenanforderungen Aussagekraft haben", "Weil sie aus der Branchenanalyse stammen", "Weil sie nur in Geldeinheiten messbar sind"], 1, "Stärken-Schwächen-Profil / Benchmarking gegenüber Konkurrenz."),
 Q(55, "ufo-stratana", "Welches Kriterium beschreibt eine Kernkompetenz <b>nicht</b>?", ["Wertvoll (Kundennutzen)", "Selten", "Schwer imitierbar", "Leicht am Markt zukaufbar"], 3, "Kernkompetenzen sind wertvoll, selten, schwer imitierbar und innerbetrieblich transferierbar – leicht zukaufbar wäre keine Basis für nachhaltige Wettbewerbsvorteile."),
 Q(56, "ufo-stratana", "Wozu dient die Wertkettenanalyse nach Porter?", ["Zur Bestimmung der Marktwachstumsrate", "Zur Analyse des Geschäftsmodells: welche primären und unterstützenden Aktivitäten Wert schaffen und wo Kosten- oder Differenzierungsvorteile entstehen", "Zur Berechnung der Dividende", "Zur Planung der Organisationsstruktur"], 1, "Primäraktivitäten (Eingangslogistik, Operationen, Ausgangslogistik, Marketing & Vertrieb, Service) + Unterstützungsaktivitäten (Infrastruktur, Personal, Technologie, Beschaffung)."),
 // Planung & Kontrolle
 Q(57, "ufo-planung", "Welche Ausprägung gehört zum Merkmal „Gegenstände“ der Planung und Kontrolle?", ["Kurz-, mittel-, langfristig", "Potenziale, Programme, Prozesse", "Sachziel- vs. wertzielorientiert", "Strategisch vs. operativ"], 1, "Zeithorizonte: kurz/mittel/lang; Zieldimensionen: Sach-/Wertziel; Ebenen: strategisch/operativ; Gestaltungsdimensionen: inhaltliche, Unterstützungs-, formale Aufgaben."),
 Q(58, "ufo-planung", "Welche drei Sichtweisen beschreiben das Planungs- und Kontrollsystem (PuK-System)?", ["Funktionale, instrumentale, institutionale Sichtweise", "Normativ, strategisch, operativ", "Kunden, Finanzen, Prozesse", "Top-down, Bottom-up, Gegenstrom"], 0, "Funktional (Prozess/Aufgaben), instrumental (Methoden/Instrumente), institutional (Träger, wer plant)."),
 Q(59, "ufo-planung", "„Die Planung schränkt durch ihr formalisiertes Vorgehen die Kreativität ein.“ Das ist eine …", ["personenbezogene Grenze", "prinzipielle Grenze", "sachbezogene Grenze", "finanzielle Grenze"], 1, "Prinzipielle Grenzen: Vergangenheitsdaten für Zukunft, deterministische Planung unsicherer Zukunft, Kreativitäts- und Flexibilitätsverlust."),
 Q(60, "ufo-planung", "„Prognosemethoden liefern unzuverlässige Ergebnisse, Informationen sind schwer zugänglich.“ Das ist eine …", ["prinzipielle Grenze", "personenbezogene Grenze", "sachbezogene Grenze", "normative Grenze"], 2, "Sachbezogen: Zugänglichkeit/Zuverlässigkeit von Informationen, Leistungsfähigkeit der Instrumente, Kosten-Nutzen."),
 Q(61, "ufo-planung", "Begrenzte Rationalität und mangelnde Motivation der Planer sind …", ["prinzipielle Grenzen", "personenbezogene Grenzen", "sachbezogene Grenzen", "keine Grenzen der Planung"], 1, "Menschen handeln nicht vollkommen rational und haben begrenzte Prognosefähigkeit."),
 Q(62, "ufo-planung", "Welches ist ein typisches <b>Problem</b> der Planung in der Praxis?", ["Zu realistische Planung", "Bildung stiller Reserven (Budgetpolster) und Ressortegoismus", "Zu große Nähe zur Strategie", "Fehlende Bürokratie"], 1, "Weitere Probleme: Tagesroutine verdrängt Planung, Abneigung der Linie, mangelndes Know-how, optimistische Mentalität, Termine, Bürokratie, Vernachlässigung strategischer Aspekte, Strategieumsetzung."),
 Q(63, "ufo-strategie", "Wie entstehen Strategien laut Mintzberg in der Praxis?", ["Ausschließlich durch formale Planung", "Realisierte Strategien entstehen aus beabsichtigten (geplanten) und emergenten Strategien; ein Teil der Planung wird nie realisiert", "Nur zufällig", "Nur durch Vorgaben des Aufsichtsrats"], 1, "Beabsichtigt → bewusst verfolgt + emergent (ungeplant, aus Handlungsmustern) = realisierte Strategie; unrealisierte Strategien fallen weg."),
 Q(64, "ufo-kontrolle", "Die Balanced Scorecard fragt in der <b>Finanzperspektive</b>: …", ["Wie sollen wir gegenüber Kunden auftreten?", "Wie können wir die Anforderungen unserer Shareholder erfüllen?", "In welchen Prozessen müssen wir die Besten sein?", "Wie fördern wir Veränderungs- und Wachstumspotenziale?"], 1, "Kunden → Auftreten gegenüber Kunden; Prozesse → in welchen Prozessen Bester sein; Lernen & Entwicklung → Wachstumspotenziale."),
 Q(65, "ufo-kontrolle", "Wofür wird die Balanced Scorecard primär eingesetzt?", ["Zur Gewinnermittlung nach UGB", "Zur Übersetzung von Vision und Strategie in Ziele, Kennzahlen und Maßnahmen in vier Perspektiven (Strategieumsetzung)", "Zur Personalauswahl", "Zur Organigrammerstellung"], 1, "Kaplan/Norton: Operationalisierung der Strategie; verbindet strategische und operative Ebene."),
 Q(66, "ufo-kontrolle", "Welche Form der strategischen Kontrolle überprüft laufend, ob die der Strategie zugrunde liegenden Annahmen noch gelten?", ["Durchführungskontrolle", "Prämissenkontrolle", "Strategische Überwachung", "Ergebniskontrolle"], 1, "Strategische Kontrolle (Schreyögg/Steinmann): Prämissenkontrolle (Annahmen), Durchführungskontrolle (Meilensteine/Umsetzung), strategische Überwachung (ungerichtet, Frühwarnung)."),
 Q(67, "ufo-kontrolle", "Die <b>strategische Überwachung</b> ist …", ["eine gezielte Soll-Ist-Kontrolle von Meilensteinen", "eine ungerichtete, breite Beobachtung von Umwelt und Unternehmen zum frühzeitigen Erkennen von Bedrohungen", "die monatliche Budgetkontrolle", "die Kontrolle durch den Abschlussprüfer"], 1, "Sie ergänzt Prämissen- und Durchführungskontrolle als „Radar“ für unerwartete Entwicklungen."),
 Q(68, "ufo-planung", "Wie werden Strategien wirkungsvoll umgesetzt?", ["Nur durch Kommunikation der Vision", "Durch Operationalisierung (z. B. Balanced Scorecard, Maßnahmen, Verantwortliche) und Budgetierung (Ressourcen den Maßnahmen zuordnen)", "Durch Verzicht auf Kontrolle", "Durch Wechsel der Rechtsform"], 1, "Strategie → strategische Ziele → operative Maßnahmen → Budgets."),
 // Organisation
 Q(69, "ufo-aufbau", "Welches Gestaltungsprinzip nennt der Katalog für die Organisation?", ["Strategy follows structure", "Structure follows process follows strategy", "Process follows structure", "Culture eats strategy"], 1, "Erst Strategie, daraus die Prozesse, daraus die Struktur (Chandler, erweitert)."),
 Q(70, "ufo-aufbau", "Was legt die Aufbauorganisation fest?", ["Den zeitlichen und räumlichen Ablauf der Aufgabenerfüllung", "Die institutionellen Beziehungen der Aufgabenträger (Arbeitsteilung und Koordination)", "Die Unternehmensethik", "Die Budgets"], 1, "Ablauforganisation = zeitliche/räumliche Aufgabenerfüllung (Prozess)."),
 Q(71, "ufo-ablauf", "Die Ablauforganisation ist das Resultat der Gestaltung …", ["der Weisungsbeziehungen", "der zeitlichen und räumlichen Aufgabenerfüllung", "der Rechtsform", "der Unternehmenswerte"], 1, "Ablauf = Prozess der Aufgabenerfüllung."),
 Q(72, "ufo-aufbau", "Ein Unternehmen ist nach Einkauf, Produktion, Vertrieb und Finanzen gegliedert. Welche Organisationsform liegt vor?", ["Divisionale Organisation", "Funktionale Organisation", "Matrixorganisation", "Holding"], 1, "Gliederung nach Verrichtungen/Funktionen."),
 Q(73, "ufo-aufbau", "Welcher Nachteil ist typisch für die funktionale Organisation?", ["Fehlende Spezialisierung", "Hoher Koordinationsaufwand, Bereichsegoismen und fehlende Ergebnisverantwortung", "Zu viele Profit-Center", "Doppelte Unterstellung"], 1, "Vorteile: Spezialisierung, Erfahrungskurveneffekte, klare Verantwortlichkeiten."),
 Q(74, "ufo-aufbau", "Welche Ursache fördert die Verbreitung der divisionalen (Sparten-)Organisation?", ["Ein einziges Produkt auf einem Markt", "Diversifikation und Internationalisierung, Größenwachstum, steigende Umweltdynamik", "Sinkende Mitarbeiterzahl", "Ausschließlich staatliche Vorgaben"], 1, "Viele Produkte/Regionen erfordern objektorientierte, marktnahe Einheiten."),
 Q(75, "ufo-aufbau", "Welcher Nachteil ist typisch für die divisionale Organisation?", ["Fehlende Marktorientierung", "Geringe Ressourceneffizienz (Doppelarbeit), Bereichsegoismen und Konflikte", "Überlastung durch Zweifachunterstellung", "Fehlende Autonomie"], 1, "Vorteile: Marktorientierung, Flexibilität, Autonomie, Entlastung der Unternehmensführung."),
 Q(76, "ufo-aufbau", "Eine Mitarbeiterin berichtet fachlich an die Leitung „Marketing“ und zugleich an die Leitung „Produktbereich Haushaltsgeräte“. Welche Organisationsform?", ["Einlinienorganisation", "Stablinienorganisation", "Matrixorganisation (Zweiliniensystem)", "Funktionale Organisation"], 2, "Gleichzeitige Gliederung nach Funktion und Objekt, Mitarbeitende sind zwei Instanzen unterstellt."),
 Q(77, "ufo-aufbau", "Welcher Nachteil gehört zur Matrixorganisation?", ["Eindimensionale Entscheidungen", "Hohes Konfliktpotenzial zwischen den Stellen und Gefahr der Überlastung der Unternehmensführung", "Keine Koordination nötig", "Zu geringe Leitungsspanne"], 1, "Vorteile: mehrdimensionale Entscheidungen, gegenseitige Kontrolle, Kooperation und Konsens."),
 Q(78, "ufo-aufbau", "In einer <b>balancierten</b> Matrix …", ["hat die Funktionsdimension immer Vorrang", "sind die Weisungsbefugnisse gleichberechtigt auf beide Dimensionen verteilt", "gibt es nur eine Instanz", "entscheiden nur Stäbe"], 1, "Fördert Koordination, schafft aber Konfliktfelder, die produktive Lösungen verlangen."),
 Q(79, "ufo-aufbau", "Welcher Vorteil kennzeichnet die Einlinienorganisation?", ["Kurze Kommunikationswege bei bereichsübergreifenden Problemen", "Eindeutige Kompetenzregelung und gute Kontrollmöglichkeiten", "Förderung der Risikobereitschaft", "Mehrdimensionale Entscheidungen"], 1, "Nachteile: lange Dienstwege, Rivalität, Sicherheits- und Risikovermeidungshaltung."),
 Q(80, "ufo-aufbau", "Was kennzeichnet die Stablinienorganisation?", ["Stäbe haben volle Weisungsbefugnis", "Die Entscheidungsvorbereitung wird an Stabsstellen delegiert, die Entscheidungskompetenz bleibt in der Linie", "Jede Stelle hat mehrere Vorgesetzte", "Es gibt keine Linieninstanzen"], 1, "Stäbe beraten, entscheiden aber nicht."),
 Q(81, "ufo-aufbau", "Welche Tätigkeit gehört <b>nicht</b> zum Organisieren laut Katalog?", ["Bildung von Stellen, Gruppen und Bereichen", "Gestaltung von Kommunikationswegen", "Ausstattung der Aufgabenträger mit Kompetenzen und Verantwortung", "Festlegung der Dividendenhöhe"], 3, "Dividende ist Sache der Gewinnverwendung (HV)."),
 Q(82, "ufo-aufbau", "Organisation im instrumentellen Sinn bedeutet laut Katalog …", ["einmalige Improvisation", "Festlegung dauerhafter Regeln zur Aufgabenerfüllung", "spontane Selbstorganisation ohne Regeln", "Disposition im Einzelfall"], 1, "Organisation = dauerhafte, generelle Regelungen (im Gegensatz zu Disposition/Improvisation)."),
 // PM
 Q(83, "ufx-pm", "Welches Merkmal gehört <b>nicht</b> zur Definition eines Projekts?", ["Einmalig", "Zeitlich begrenzt", "Komplex, mehrere Organisationseinheiten beteiligt", "Dauerhafte Routineaufgabe"], 3, "Routineaufgaben sind Linienaufgaben, keine Projekte."),
 Q(84, "ufx-pm", "Wie geht man am besten mit einer Vielzahl paralleler Projekte um?", ["Alle gleichzeitig mit voller Priorität starten", "Multiprojekt- bzw. Projektportfoliomanagement: priorisieren nach strategischem Beitrag, Ressourcen projektübergreifend planen, Abhängigkeiten steuern", "Projekte ohne Planung laufen lassen", "Nur das kleinste Projekt durchführen"], 1, "Ein PMO/Portfolio-Board bewertet, priorisiert und steuert alle Projekte gemeinsam."),
 Q(85, "ufx-pm", "Das Projektmanagement-Dreieck besteht aus …", ["Leistung (Qualität), Zeit (Termine), Einsatzmitteln (Kosten/Ressourcen)", "Planung, Organisation, Personal", "Werte, Ziele, Kultur", "Branche, Markt, Kunde"], 0, "Veränderung einer Größe wirkt auf die anderen (magisches Dreieck)."),
 // Geschäftsmodelle & Skalierung
 Q(86, "ufo-bm", "Ein Geschäftsmodell beschreibt …", ["nur die Kostenstruktur", "das Grundprinzip, wie ein Unternehmen Werte schafft, vermittelt (liefert) und erfasst", "das Organigramm", "die Rechtsform"], 1, "Osterwalder/Pigneur."),
 Q(87, "ufo-bm", "Welcher Baustein gehört <b>nicht</b> zum Business Model Canvas?", ["Schlüsselpartner", "Einnahmequellen", "Kostenstruktur", "Unternehmensverfassung"], 3, "9 Bausteine: Wertangebote, Kundensegmente, Kundenbeziehungen, Kanäle, Einnahmequellen, Kostenstruktur, Schlüsselpartner, -ressourcen, -aktivitäten."),
 Q(88, "ufx-skalierung", "Welcher Skalierungsweg bietet schnelles Wachstum bei hohem Kapitalbedarf und hohem Risiko?", ["Organisches Wachstum", "Akquisitionen", "Franchising", "Partnerschaften"], 1, "Organisch: nachhaltig, langsam; Partnerschaften: schnell, Qualitätsrisiko; Franchising: hohe Skalierbarkeit, geringeres Einkommenspotenzial."),
 Q(89, "ufx-skalierung", "Welcher Nachteil ist für <b>Franchising</b> typisch?", ["Sehr langsames Wachstum", "Geringeres Einkommenspotenzial (Gewinn bleibt großteils beim Franchisenehmer)", "Sehr hoher eigener Kapitalbedarf", "Keine Skalierbarkeit"], 1, "Der Franchisegeber erhält nur Gebühren/Lizenzen."),
 Q(90, "ufx-skalierung", "Welche ist <b>keine</b> typische Herausforderung bei der Unternehmensskalierung?", ["Verlust der Agilität", "Erhöhte Komplexität", "Kulturelle Veränderungen", "Sinkende Zahl an Schnittstellen"], 3, "Mit Wachstum steigen Schnittstellen und Komplexität; dazu finanzielle Herausforderungen."),
 Q(91, "ufx-skalierung", "Welche Strategie dient einer <b>nachhaltigen</b> Skalierung?", ["Prozesse unverändert lassen", "Geschäftsprozesse verbessern, Technologie integrieren, Talente entwickeln, Kunden binden", "Personalentwicklung streichen", "Kundenbindung vernachlässigen zugunsten Neukunden"], 1, "Diese vier Hebel nennt der Katalog."),
 Q(92, "ufx-skalierung", "Welcher Grund für Skalierung wird im Katalog genannt?", ["Verringerung des Marktanteils", "Effizienzsteigerungen (Skaleneffekte) und höhere Marktanteile", "Verkleinerung des Produktportfolios", "Abbau der Marktnachfrage"], 1, "Gründe: Marktanteile, Effizienz, Erweiterung von Produkten/DL, Marktnachfrage bedienen → Umsatzwachstum."),
 // Richtig/Falsch
 Q(93, "ufo-planung", "Richtig oder falsch: „Kontrolle ist der beurteilende Vergleich zwischen zwei Größen (z. B. Soll/Ist) mit anschließender Analyse der Abweichungen.“", ["Richtig", "Falsch"], 0, "Genau so definiert der Katalog Kontrolle."),
 Q(94, "ufo-aufbau", "Richtig oder falsch: „In der Mehrlinienorganisation sind die Weisungskompetenzen der übergeordneten Stellen immer gleich stark.“", ["Richtig", "Falsch"], 1, "Sie können gleich oder unterschiedlich stark sein."),
 Q(95, "ufx-verfassung", "Richtig oder falsch: „In der deutschen AG wählt die Hauptversammlung den Vorstand direkt.“", ["Richtig", "Falsch"], 1, "Der Vorstand wird vom Aufsichtsrat bestellt."),
 Q(96, "ufo-normativ", "Richtig oder falsch: „Eine Vision soll so nahe sein, dass sie realisierbar wirkt, und so fern, dass sie Begeisterung für eine bessere Wirklichkeit weckt.“", ["Richtig", "Falsch"], 0, "Definition der unternehmerischen Vision.")
);

const F = (id, topic, front, back) => ({ id: "ufx-f" + id, cat: "GL-UFO", topic, front, back, alt: true });
c.flashcards.push(
 F(1, "ufo-begriffe", "Was ist Unternehmensführung? (je Ebene)", "<ul><li><b>Normativ</b>: Identität des Unternehmens in Werten, Zielen, Verhaltensweisen und organisatorischen Normen</li><li><b>Strategisch</b>: Entwicklung bestehender und Erschließung neuer <b>Erfolgspotenziale</b> samt Zielen, Leistungspotenzialen, Vorgehensweisen</li><li><b>Operativ</b>: Planung, Steuerung und Kontrolle der laufenden Aktivitäten, um bestehende Erfolgspotenziale möglichst effektiv zu nutzen</li></ul>"),
 F(2, "ufo-io", "Wie lässt sich die Entstehung von Unternehmen erklären?", "<b>Neue Institutionenökonomie</b>, v. a. <b>Transaktionskostentheorie</b> (Coase, Williamson): Leistungen werden im Unternehmen (Hierarchie) statt über den Markt koordiniert, wenn die Transaktionskosten (Anbahnung, Vereinbarung, Abwicklung, Kontrolle, Anpassung) intern geringer sind – v. a. bei hoher Spezifität, Unsicherheit und Häufigkeit. Ergänzend: <b>Principal-Agent-Theorie</b> (Verträge zwischen Eigentümern und Managern) und <b>Verfügungsrechte</b> (Bündelung von Property Rights). Betriebswirtschaftlich: Kombination von Produktionsfaktoren zur Fremdbedarfsdeckung ist arbeitsteilig effizienter."),
 F(3, "ufo-io", "Welchen praktischen Beitrag leisten die drei Theorien der Unternehmensführung?", "<ul><li><b>Industrieökonomie</b>: Structure-Conduct-Performance; Branchenstrukturanalyse mit <b>Porters Five Forces</b>, Veränderung von Branchenstrukturen</li><li><b>Ressourcenorientierter Ansatz</b>: Resources-Conduct-Performance; Ressourcen/Kernkompetenzen als Quelle von Wettbewerbsvorteilen</li><li><b>Systemtheorie</b>: Steuerungs-, Regelungs- bzw. Lenkungsprinzip; <b>St. Galler Management-Modell</b></li></ul>"),
 F(4, "ufo-stratana", "Porters Five Forces – Kräfte und Einflussfaktoren", "Zentrum: <b>Rivalität</b> (Wachstum, Differenzierung, Überkapazität, Austrittsbarrieren, konkurrierende Geschäftslogiken).<br><b>Neue Anbieter</b>: erwartete Reaktion der Etablierten + Eintrittsbarrieren (Economies of Scale, Produktdifferenzierung, Kapitalbedarf, Kostennachteile, Vertriebskanäle, staatliche Politik).<br><b>Lieferanten</b>/<b>Abnehmer</b>: Konzentrationsgrad (je weniger, desto mächtiger), Standardisierungsgrad (Umstellkosten), Vorwärts- bzw. Rückwärtsintegration, Bedeutung der Branche für sie (je wichtiger, desto geringer ihre Macht).<br><b>Substitute</b>."),
 F(5, "ufo-prozess", "Funktionen der Unternehmensführung und ihr Zusammenhang mit den Ebenen", "<b>Funktionen</b>: Planung &amp; Kontrolle (zukunftsbezogenes Festlegen von Zielen, Maßnahmen, Mitteln; Einheit mit Kontrolle), Organisation (zweckgerichtete Gestaltung von Strukturen), Personal (alle mitarbeiterbezogenen Planungs-, Steuerungs- und Kontrollaufgaben).<br><b>Zusammenhang</b>: hierarchischer Aufbau (Dreieck normativ – strategisch – operativ), übergeordnete Ebenen setzen den Rahmen, <b>Information</b> verbindet Ebenen und Funktionen."),
 F(6, "ufo-normativ", "Aufgaben und Elemente der normativen Unternehmensführung", "Aufgabe: Identität des Unternehmens bestimmen, Lebens- und Entwicklungsfähigkeit sichern.<br>Elemente: <b>Werte</b> (Ethik, Philosophie) · <b>Ziele</b> (Vision, Politik) · <b>Kultur</b> (Verhaltensnormen) · <b>Verfassung</b> (organisatorische Normen) · <b>Mission</b> (Anspruch und Selbstbild).<br>Zusammenwirken: Werte → Ziele → Kultur, Verfassung, Mission; Kultur und Verfassung fließen in die Mission ein."),
 F(7, "ufx-ethik", "Unternehmensphilosophie vs. Unternehmensethik", "<b>Philosophie</b>: grundlegende Einstellungen/Überzeugungen; bilden Werte, die Denken und Handeln prägen (oft verdeckt, unausgesprochen).<br><b>Ethik</b>: Teil der Philosophie mit den moralischen Maßstäben; legitimiert das Handeln, beschreibt moralische und gesellschaftliche Verantwortung; reflektiert, was ökonomisch relevant und moralisch legitim ist; löst den Grundkonflikt Moral vs. Ökonomie."),
 F(8, "ufx-ethik", "Einteilung von Unternehmen nach ethischem Verhalten", "1. unmoralisch (Bilanzfälschung, Abgasskandal) · 2. legalistisch (Cum-Ex: Gesetzeslücken nutzen) · 3. ethisch reaktiv (opportunistisch, nur unter Druck) · 4. ethisch engagiert · 5. ethisch"),
 F(9, "ufx-ethik", "Einfluss der Werte auf die Unternehmensführung (werteorientierte Führung)", "Grundwerte: <b>Humanismus</b> (Nachhaltigkeit, Respekt, Kooperation, Goldene Regel), <b>Wirtschaftlichkeit</b> (Überleben, Gewinn), <b>Professionalität</b> (sachrichtige, optimale Leistung für Kunden), <b>Glaubwürdigkeit</b> (Reden = Handeln).<br>Umsetzung: Konfliktlösung, Kodifizierung (Ethikkodex/Code of Ethics), Durchsetzungssysteme (Compliance), Corporate Social Responsibility."),
 F(10, "ufx-ethik", "Nachhaltige Unternehmensführung und Nachhaltigkeitsdreieck", "Gleichrangig ökonomische, ökologische und soziale Ziele (Wert-, Sozial-, Naturorientierung); Ressourcen so nutzen, dass die Lebensqualität künftig zumindest erhalten bleibt; inter- und intragenerationelle Gerechtigkeit.<br>Dreieck: ökonomische, ökologische, soziale <b>Effektivität</b>; <b>Öko-Effizienz</b> (Ökonomie–Ökologie), <b>Sozio-Effizienz</b> (Ökonomie–Soziales)."),
 F(11, "ufo-normativ", "Unternehmenspolitik: Was umfasst sie?", "Entwickelt die <b>Unternehmensziele</b> durch politische Prozesse des Interessenausgleichs; legt Ziele bei Interessenkonflikten durch Machtausübung fest. Ausrichtung: <b>Stakeholder</b>- (alle Anspruchsgruppen: Kunden, Lieferanten, Staat, Fremdkapitalgeber …) oder <b>Shareholder-Orientierung</b> (Eigentümerziele primär). Aufgaben: Konfliktklärung, Zielsuche."),
 F(12, "ufo-normativ", "Analyse der globalen Umwelt", "Fragen: Was macht die globale Umwelt aus? Welche Faktoren beeinflussen das Unternehmen? Wie analysieren/beobachten? Welche Bedeutung?<br>Faktoren: <b>Politik/Recht, Gesellschaft, Ökonomie, Ökologie, Technik</b>.<br>Analyse ist immer selektiv; Erfolg hängt von Anpassung an Veränderungen ab (Bsp. Nokia); proaktiv z. B. durch Lobbyarbeit."),
 F(13, "ufo-normativ", "Unternehmerische Vision: Definition, Anforderungen, Rolle", "Konkretes Zukunftsbild – nah genug, um realisierbar zu wirken, fern genug, um Begeisterung zu wecken.<br>Anforderungen: <b>richtungsweisend</b> (zukunftsorientiert, verbindlich), <b>anspornend</b> (fordernd, begeisternd), <b>plausibel</b> (realistisch, kompetent), <b>prägnant</b> (verständlich, kommunizierbar).<br>Rolle: Bindeglied zwischen Personal, Organisation, Planung &amp; Kontrolle → Fokussierung, Legitimation, Identifikation und Motivation."),
 F(14, "ufo-normativ", "Wie formuliert man Unternehmensziele?", "Ziel = normative Vorstellung über einen künftigen Zustand, der durch Handeln erreicht werden soll.<br>Dimensionen: <b>Inhalt</b> (Marktanteil erhöhen), <b>Ausmaß</b> (5 %), <b>Termin</b> (Dezember), <b>Verantwortung</b> (GL Vertrieb), <b>Ort</b> (China).<br><b>SMART</b>: spezifisch, messbar, anspruchsvoll/akzeptiert, realistisch, terminiert."),
 F(15, "ufx-ethik", "Unternehmenskultur: Inhalt, Wirkungen, Kulturwandel", "Gesamtheit der Wertvorstellungen, Traditionen, Überlieferungen, Mythen, Denkhaltungen, die Verhalten prägen. Wirkt auf Sprache, Rituale, Kleidung, Umgangsformen, Verhaltensrichtlinien, Verbote, Einstellungen, Werte.<br><b>Kulturwandel</b>: Krise durch bisherige Muster → Verunsicherung (Symbole/Riten unglaubwürdig) → Schattenkulturen, neue Orientierungsmuster → Konflikt alt/neu → Akzeptanz erfolgreicher Muster → Entfaltung der neuen Kultur (neue Symbole, Normen, Standards)."),
 F(16, "ufx-ethik", "Zusammenhang Unternehmenskultur – Unternehmensmission", "Kultur wird mit Werten, Zielen und Verfassung zur <b>Mission</b> (angestrebtes Selbstbild) zusammengefasst. Die gelebte Kultur ist das umgesetzte Selbstbild = <b>Corporate Identity</b> (Corporate Behaviour, Corporate Design, Corporate Communication)."),
 F(17, "ufx-verfassung", "Grundformen der Unternehmensverfassung", "<ul><li><b>Board (USA)</b>: Shareholders' Meeting → Board of Directors (Managing + Outside Directors), monistisch</li><li><b>AG (D)</b>: Hauptversammlung → Aufsichtsrat → Vorstand, dualistisch</li><li><b>GmbH (D)</b>: Gesellschafterversammlung → (Beirat) → Geschäftsführung</li><li><b>Familienunternehmen</b>: Eigentümer in der Führung, langfristig, kurze Wege, flexibel, kontinuierlich, geringe öffentliche Rechtfertigung</li></ul>"),
 F(18, "ufx-verfassung", "Deutsche AG: Rechte der Aktionäre und Aufgaben der Organe", "Aktionäre: Teilnahme, Auskunft, Stimmrecht, Anfechtung, Dividende, Liquidationserlös.<br><b>HV</b>: wählt/beruft Aufsichtsrat ab (außer Arbeitnehmervertreter).<br><b>Aufsichtsrat</b>: bestellt/beruft Vorstand ab, beschließt über besondere Angelegenheiten, überwacht die Geschäftsführung; berichtet an HV.<br><b>Vorstand</b>: leitet, berichtet an AR."),
 F(19, "ufx-verfassung", "Corporate Governance und Compliance", "<b>Corporate Governance</b>: Grundsätze ordnungsgemäßer, verantwortungsvoller Unternehmensführung – Rahmen für Leitung und Überwachung; internes Kontrollsystem aus Risikomanagement, Revision, Compliance.<br><b>Compliance</b>: Gesamtheit der Grundsätze und Maßnahmen zur Einhaltung von Gesetzen, Richtlinien und freiwilligen Kodizes zur Vermeidung von Regelverstößen."),
 F(20, "ufo-normativ", "Unternehmensmission: Bestandteile", "Legt den <b>Zweck</b> fest und fasst Werte, Ziele, Kultur und Verfassung zu einem angestrebten Selbstbild zusammen:<br>Werte (ethischer Anspruch) · Ziele (was für Stakeholder erreicht werden soll) · Kultur (wie gedacht und gehandelt wird) · Verfassung (Organe, Rechte, Pflichten) · Zweck (warum es das Unternehmen gibt: Tätigkeitsfeld, Kundenbedürfnisse, Branchen, Märkte)."),
 F(21, "ufo-normativ", "Leitbild: Definition, Funktionen, Abgrenzung zur Mission", "Schriftliche Dokumentation wesentlicher Bestandteile der Mission, intern und extern bekannt gemacht (Identifikation fördern). Funktionen: <b>Orientierung, Konkretisierung, Legitimation, Motivation</b>.<br>Mission = Auftrag und Beitrag zur Gesellschaft, stärkere Kundenperspektive; Leitbild = Orientierung für Mitarbeitende (Werte, Grundsätze, Ziele), wirkt stärker nach innen."),
 F(22, "ufo-stratana", "Wie wird die Unternehmensumwelt strategisch analysiert? (Analyseschema)", "Ausgang: normative Situation + <b>globale Umweltanalyse</b>.<br><b>Umweltanalysen</b>: Branchenanalyse (Five Forces) → Marktanalyse → Kunden- und Produktanalyse ⇒ <b>Chancen &amp; Risiken</b>.<br><b>Unternehmensanalysen</b>: Geschäftsmodell-, Ressourcen-, Kompetenzanalyse ⇒ <b>Stärken &amp; Schwächen</b>.<br><b>Konkurrenzanalyse</b> verbindet beide. Ergebnis: <b>SWOT-Analyse</b> = strategische Situation."),
 F(23, "ufo-stratana", "Chancen und Risiken aus der Umwelt (Beispiele)", "Chancen und Risiken entstehen <b>außerhalb</b> des Unternehmens (nicht beeinflussbar), abgeleitet aus globaler Umwelt (PESTEL), Branche, Markt, Kunden, Produkten, Konkurrenz.<br><b>Chancen</b>: neue Märkte/Kundengruppen, wachsende Nachfrage, technologische Innovationen, günstige Gesetzesänderungen, Schwächen der Konkurrenz.<br><b>Risiken</b>: neue Wettbewerber, Substitute, steigende Macht von Lieferanten/Abnehmern, Konjunktureinbruch, strengere Regulierung, technologischer Wandel (Bsp. Nokia)."),
 F(24, "ufo-stratana", "Relative Stärken und Schwächen ermitteln", "Interne Analyse von Geschäftsmodell (Wertkette), Ressourcen und Kompetenzen – stets <b>relativ zum stärksten Wettbewerber</b> und zu den Kundenanforderungen (sonst keine Aussagekraft). Instrumente: <b>Stärken-Schwächen-Profil</b>, Benchmarking, Wertkettenanalyse, Ressourcen-/Kernkompetenzanalyse. Ergebnis fließt mit Chancen/Risiken in die SWOT."),
 F(25, "ufo-stratana", "Strategische Ressourcen und Kernkompetenzen", "<b>Strategische Ressourcen</b> – Kriterien: Nutzbarkeit, Einzigartigkeit, Überlegenheit, Dauerhaftigkeit, (geringe) Ersetzbarkeit, Kundenwert.<br><b>Kernkompetenzen</b>: einzelne/kombinierte Kompetenzen, aus denen Wettbewerbsvorteile entstehen – <b>wertvoll, selten, schwer imitierbar, innerbetrieblich transferierbar</b>.<br>Geschäftsmodellanalyse: Wertkette (Porter), Wertschöpfungsnetz."),
 F(26, "ufo-planung", "Formen der Planung und Kontrolle (Merkmale)", "<table class=\"dt\"><tr><th>Merkmal</th><th>Ausprägungen</th></tr><tr><td>Funktionen</td><td>Beschaffung, Produktion, Absatz, Personal …</td></tr><tr><td>Geltungsbereiche</td><td>Gesamtunternehmen, Bereiche, Stellen</td></tr><tr><td>Zeithorizonte</td><td>kurz-, mittel-, langfristig</td></tr><tr><td>Ebenen</td><td>strategisch, operativ</td></tr><tr><td>Zieldimensionen</td><td>sachziel-, wertzielorientiert</td></tr><tr><td>Gestaltungsdimensionen</td><td>inhaltliche, Unterstützungs-, formale Aufgaben</td></tr><tr><td>Gegenstände</td><td>Potenziale, Programme, Prozesse</td></tr></table>"),
 F(27, "ufo-planung", "Planungs- und Kontrollsystem (PuK-System)", "Beschreibt Aufbau und Zusammenhang der Pläne und Kontrollen, Aufgaben der Beteiligten, den PuK-Prozess und die Instrumente; liefert den Rahmen für die inhaltliche Planung.<br>Sichtweisen: <b>funktional</b> (Prozess), <b>instrumental</b> (Methoden), <b>institutional</b> (Träger/Organisation)."),
 F(28, "ufo-planung", "Grenzen und Probleme der Planung und Kontrolle", "<b>Prinzipiell</b>: Zukunft aus Vergangenheit ableiten, deterministische Planung unsicherer Zukunft, Kreativitätsverlust durch Formalisierung, Flexibilitätsverlust durch Festlegung.<br><b>Personenbezogen</b>: begrenzte Rationalität und Prognosefähigkeit, mangelnde Motivation.<br><b>Sachbezogen</b>: Zugänglichkeit/Zuverlässigkeit von Informationen, Leistungsfähigkeit der Instrumente, Kosten-Nutzen.<br><b>Probleme</b>: Tagesroutine, Abneigung der Linie, fehlendes Know-how, optimistische Mentalität, stille Reserven, Termine, Ressortegoismus, Bürokratie, Vernachlässigung strategischer Aspekte, Strategieumsetzung."),
 F(29, "ufo-strategie", "Wie entstehen Strategien?", "<b>Geplant</b> (rational: Analyse → Formulierung → Bewertung/Auswahl → Umsetzung → Kontrolle) und <b>emergent</b> (aus Handlungsmustern, ungeplant). Nach Mintzberg: beabsichtigte Strategie → teils unrealisiert, teils bewusst verfolgt; zusammen mit emergenten Strategien ergibt sich die <b>realisierte</b> Strategie.<br>Umsetzung: strategische Ziele werden über operative Maßnahmen konkretisiert und realisiert."),
 F(30, "ufo-kontrolle", "Balanced Scorecard – vier Perspektiven mit Leitfragen", "<b>Finanzen</b>: Wie erfüllen wir die Anforderungen unserer Shareholder?<br><b>Kunden</b>: Wie sollen wir gegenüber unseren Kunden auftreten, um die Vision zu verwirklichen?<br><b>Interne Geschäftsprozesse</b>: In welchen Prozessen müssen wir die Besten sein?<br><b>Lernen &amp; Entwicklung</b>: Wie fördern wir Veränderungs- und Wachstumspotenziale?<br>Je Perspektive: Ziele, Kennzahlen, Vorgaben, Maßnahmen."),
 F(31, "ufo-kontrolle", "Wie werden Strategien umgesetzt und kontrolliert?", "<b>Umsetzung</b>: Operationalisierung (BSC, Strategy Map, Maßnahmen, Verantwortliche) und <b>Budgetierung</b> (Ressourcen zuordnen).<br><b>Strategische Kontrolle</b>: <b>Prämissenkontrolle</b> (gelten die Annahmen noch?), <b>Durchführungskontrolle</b> (Meilensteine, Zwischenziele), <b>strategische Überwachung</b> (ungerichtet, Frühwarnung); ergänzt durch Ergebniskontrolle (Soll-Ist)."),
 F(32, "ufo-aufbau", "Was ist Organisation, wie wird organisiert, wodurch gestaltet?", "Organisation legt <b>dauerhafte Regeln</b> zur Aufgabenerfüllung fest.<br>Organisieren: Stellen/Gruppen/Bereiche bilden, Kommunikationswege gestalten, Kompetenzen und Verantwortung zuordnen, Aufbau- und Ablauforganisation gestalten, neue Systeme einführen und dokumentieren.<br>Gestaltung: <b>Structure follows process follows strategy</b>; Aufbauorganisation (institutionelle Beziehungen, Arbeitsteilung &amp; Koordination), Ablauforganisation (zeitliche/räumliche Aufgabenerfüllung), Fremd- vs. Selbstorganisation."),
 F(33, "ufo-aufbau", "Funktionale, divisionale und Matrixorganisation – Vor- und Nachteile", "<table class=\"dt\"><tr><th>Form</th><th>Vorteile</th><th>Nachteile</th></tr><tr><td>Funktional (Verrichtung)</td><td>Spezialisierung, Erfahrungskurve, klare Verantwortung</td><td>hoher Koordinationsaufwand, Bereichsegoismen, keine Ergebnisverantwortung</td></tr><tr><td>Divisional (Produkt/Kunde/Region)</td><td>Marktorientierung, Flexibilität, Autonomie, Entlastung der Führung</td><td>Bereichsegoismen, Konflikte, geringe Ressourceneffizienz</td></tr><tr><td>Matrix (Zweilinien)</td><td>mehrdimensionale Entscheidungen, gegenseitige Kontrolle, Kooperation</td><td>Konfliktpotenzial, Überlastung der Führung, große Leitungsspanne</td></tr></table>"),
 F(34, "ufo-aufbau", "Einlinien-, Stablinien-, Mehrlinienorganisation", "<b>Einlinie</b>: genau eine übergeordnete Instanz (Entscheidung, Genehmigung, Anweisung, Veto); + eindeutige Kompetenzen, gute Kontrolle; − lange Wege, Rivalität, Sicherheitsdenken.<br><b>Stablinie</b>: Entscheidungsvorbereitung an Stäbe delegiert, Entscheidung bleibt in der Linie.<br><b>Mehrlinie</b>: zwei oder mehr übergeordnete Stellen, gleich oder unterschiedlich starke Weisungskompetenzen."),
 F(35, "ufx-pm", "Projekt, Bausteine, Erfolgsfaktoren, Multiprojektmanagement", "<b>Projekt</b>: einmalig, zeitlich begrenzt, komplex, mehrere Mitarbeitende aus verschiedenen Einheiten.<br><b>Bausteine</b>: Definition, Planung, Kontrolle/Steuerung, Abschluss, Unterstützung (Führung, Zielsetzung, Organisation).<br><b>Erfolgsfaktoren</b>: Dreieck Leistung/Qualität – Zeit/Termine – Einsatzmittel/Kosten.<br><b>Viele Projekte</b>: Multiprojekt-/Portfoliomanagement – bewerten, priorisieren, Ressourcen übergreifend zuteilen, Abhängigkeiten steuern, PMO."),
 F(36, "ufo-bm", "Geschäftsmodell: Definition und Aspekte bei der Entwicklung", "Grundprinzip, wie ein Unternehmen <b>Werte schafft, liefert und erfasst</b>.<br>Aspekte (Canvas): Wertangebote, Kundensegmente, Kundenbeziehungen, Vertriebskanäle, Einnahmequellen, Kostenstruktur, Schlüsselpartner, Schlüsselressourcen, Schlüsselaktivitäten."),
 F(37, "ufx-skalierung", "Unternehmensskalierung: Gründe, Wege, Herausforderungen, nachhaltige Strategien", "<b>Gründe</b>: Marktanteile, Effizienz, Erweiterung von Produkten/DL, Nachfrage bedienen → Umsatzwachstum.<br><b>Wege</b>: organisch (+ nachhaltig, wenig Risiko / − langsam), Akquisition (+ schnell / − Kapital, Risiko), Partnerschaft (+ schnell / − Qualitätsrisiko), Franchising (+ hoch skalierbar / − geringeres Einkommenspotenzial).<br><b>Herausforderungen</b>: Agilitätsverlust, Komplexität, Finanzen, Kultur.<br><b>Nachhaltig</b>: Prozesse verbessern, Technologie integrieren, Talente entwickeln, Kunden binden.")
);

c.examPrep = {
  format: "Laut Syllabus: schriftliches Exam am Ende der LV (Termine 1a/1b), Multiple-/Single-Choice, 75 von 100 Gesamtpunkten, ohne KI-Hilfsmittel; muss für sich positiv sein (> 60 %). Als Quelle liegt keine echte Altprüfung vor, sondern ein studentischer Fragenkatalog, der die Kapitel des Lehrbuchs (Dillerup/Stoi-Struktur) mit Leitfragen abarbeitet. Die genaue Fragenzahl und Punkteverteilung ist daher unsicher – erwarte Definitions-, Zuordnungs- und Fallfragen (z. B. Organisationsform erkennen) mit plausiblen Distraktoren.",
  sources: ["GL_UFO_Prüfungsvorbereitung (studentischer Fragenkatalog mit Antworten, 10 Folienabbildungen)"],
  strategy: [
    "Aufzählungen exakt lernen – MC-Distraktoren tauschen gern ein Element aus: 5 normative Elemente, SMART, 4 Vision-Anforderungen, 4 Leitbild-Funktionen, 4 BSC-Perspektiven, 9 Canvas-Bausteine, 5 Ethik-Typen.",
    "Zuordnungen üben: Element ↔ Inhalt (Kultur = Verhaltensnormen, Verfassung = organisatorische Normen), Five-Forces-Faktor ↔ Kraft (Vorwärtsintegration = Lieferanten, Rückwärtsintegration = Abnehmer), Planungsgrenze ↔ Kategorie.",
    "Organisationsformen mit Vor-/Nachteilen sicher können und an Fallbeschreibungen erkennen (Funktion vs. Sparte vs. Matrix, Einlinie vs. Stablinie vs. Mehrlinie).",
    "Bei „nicht“-Fragen langsam lesen: meist ist genau ein Element aus einem anderen Modell untergeschoben (z. B. „Wettbewerber“ als BSC-Perspektive).",
    "Organe der AG/GmbH/Board mit Pfeilrichtungen (wer wählt/bestellt wen, wer berichtet an wen) als Skizze aus dem Kopf zeichnen können.",
    "Die Fragen mit „?“ im Katalog (Entstehung von Unternehmen, Chancen/Risiken, relative Stärken, Strategiekontrolle, Multiprojekte) gezielt mit den Karten in diesem Bereich nachlernen."
  ],
  focus: [
    { topic: "ufo-normativ", weight: 3, note: "Größter Block im Katalog: Elemente, Politik/Stakeholder, Vision, SMART-Ziele, Kultur, Mission, Leitbild" },
    { topic: "ufo-aufbau", weight: 3, note: "Organisationsmodelle mit Vor-/Nachteilen ausführlich im Katalog – ideal für Fall-MC" },
    { topic: "ufo-stratana", weight: 3, note: "Five Forces (Abbildung), Analyseschema/SWOT, Ressourcen und Kernkompetenzen" },
    { topic: "ufo-planung", weight: 3, note: "Formen der Planung (2 Tabellen), PuK-System, Grenzen und Probleme" },
    { topic: "ufx-ethik", weight: 2, note: "Ethik-Typen, Werteorientierung, Nachhaltigkeitsdreieck, Kulturwandel (Abbildungen)" },
    { topic: "ufx-verfassung", weight: 2, note: "Board/AG/GmbH/Familienunternehmen mit Organen (3 Abbildungen), Corporate Governance, Compliance" },
    { topic: "ufo-kontrolle", weight: 2, note: "Balanced Scorecard mit Leitfragen, strategische Kontrolle" },
    { topic: "ufo-ebenen", weight: 2, note: "Normativ/strategisch/operativ – Definition der Unternehmensführung" },
    { topic: "ufo-prozess", weight: 2, note: "Führungsfunktionen und Zusammenhang im Führungssystem" },
    { topic: "ufo-io", weight: 2, note: "Drei Theorien und ihr praktischer Beitrag, Entstehung von Unternehmen" },
    { topic: "ufo-bm", weight: 2, note: "Geschäftsmodell-Definition und Canvas-Bausteine" },
    { topic: "ufx-skalierung", weight: 2, note: "Gründe, Wege mit Vor-/Nachteilen, Herausforderungen, Strategien" },
    { topic: "ufo-strategie", weight: 1, note: "Strategieentstehung, -auswahl, -umsetzung" },
    { topic: "ufx-pm", weight: 1, note: "Projektdefinition, Bausteine, magisches Dreieck, Multiprojekte" },
    { topic: "ufo-begriffe", weight: 1, note: "Definitionen Unternehmen, Führung, Unternehmensführung" },
    { topic: "ufo-rbv", weight: 1, note: "Resources-Conduct-Performance" },
    { topic: "ufo-system", weight: 1, note: "Steuerung/Regelung/Lenkung, St. Galler Modell" },
    { topic: "ufo-ablauf", weight: 1, note: "Abgrenzung Aufbau- vs. Ablauforganisation" }
  ],
  checklist: [
    { id: "ufx-c1", topic: "ufo-begriffe", text: "Unternehmen, Führung (funktional) und Unternehmensführung je Ebene wörtlich definieren" },
    { id: "ufx-c2", topic: "ufo-io", text: "Drei Theorien mit Paradigma (SCP, RCP, Lenkung/St. Gallen) nennen und Entstehung von Unternehmen per Transaktionskosten erklären" },
    { id: "ufx-c3", topic: "ufo-stratana", text: "Five Forces mit allen Einflussfaktoren zeichnen; Vorwärts- vs. Rückwärtsintegration richtig zuordnen" },
    { id: "ufx-c4", topic: "ufo-prozess", text: "Führungsfunktionen (Planung & Kontrolle, Organisation, Personal) und ihren Zusammenhang mit den Ebenen erklären" },
    { id: "ufx-c5", topic: "ufo-normativ", text: "Die 5 normativen Elemente mit Inhalt (Ethik/Philosophie, Vision/Politik, Verhaltensnormen, organisatorische Normen, Selbstbild) und ihr Zusammenwirken" },
    { id: "ufx-c6", topic: "ufx-ethik", text: "Philosophie vs. Ethik, 5 Ethik-Typen mit Beispiel, Grundwerte werteorientierter Führung" },
    { id: "ufx-c7", topic: "ufx-ethik", text: "Nachhaltigkeitsdreieck inkl. Öko- und Sozio-Effizienz zeichnen" },
    { id: "ufx-c8", topic: "ufo-normativ", text: "Stakeholder- vs. Shareholder-Orientierung; globale Umweltfaktoren aufzählen" },
    { id: "ufx-c9", topic: "ufo-normativ", text: "Vision: Definition, 4 Anforderungen, Funktionen als Bindeglied; Ziele mit 5 Dimensionen und SMART formulieren" },
    { id: "ufx-c10", topic: "ufx-ethik", text: "Kultur definieren und die 6 Phasen des Kulturwandels in Reihenfolge nennen; Corporate Identity (3 Teile)" },
    { id: "ufx-c11", topic: "ufx-verfassung", text: "Organe und Pfeile von Board-, AG- und GmbH-Verfassung; Merkmale Familienunternehmen; Corporate Governance vs. Compliance" },
    { id: "ufx-c12", topic: "ufo-normativ", text: "Mission (5 Bestandteile), Leitbild (4 Funktionen) und Unterschied Mission vs. Leitbild" },
    { id: "ufx-c13", topic: "ufo-stratana", text: "Analyseschema: Umwelt- vs. Unternehmensanalysen → Chancen/Risiken bzw. Stärken/Schwächen → SWOT; Beispiele richtig einordnen" },
    { id: "ufx-c14", topic: "ufo-stratana", text: "Kriterien strategischer Ressourcen und Kernkompetenzen; Wertkette als Geschäftsmodellanalyse" },
    { id: "ufx-c15", topic: "ufo-planung", text: "Planung und Kontrolle definieren; alle 7 Merkmale der Planungsformen mit Ausprägungen; PuK-System mit 3 Sichtweisen" },
    { id: "ufx-c16", topic: "ufo-planung", text: "Prinzipielle, personen- und sachbezogene Grenzen unterscheiden; typische Planungsprobleme nennen" },
    { id: "ufx-c17", topic: "ufo-kontrolle", text: "BSC-Perspektiven mit Leitfrage; Prämissen-, Durchführungskontrolle, strategische Überwachung" },
    { id: "ufx-c18", topic: "ufo-aufbau", text: "Organisieren (6 Tätigkeiten), Structure follows process follows strategy, Aufbau vs. Ablauf" },
    { id: "ufx-c19", topic: "ufo-aufbau", text: "Funktional/divisional/Matrix sowie Einlinie/Stablinie/Mehrlinie mit Vor- und Nachteilen; Form aus Fallbeschreibung erkennen" },
    { id: "ufx-c20", topic: "ufx-pm", text: "Projekt definieren, Bausteine, magisches Dreieck, Umgang mit vielen Projekten" },
    { id: "ufx-c21", topic: "ufo-bm", text: "Geschäftsmodell definieren, 9 Canvas-Bausteine" },
    { id: "ufx-c22", topic: "ufx-skalierung", text: "Skalierung: 4 Gründe, 4 Wege mit Vor-/Nachteil, 4 Herausforderungen, 4 Strategien" }
  ],
  tasks: [
    { id: "ufx-r1", topic: "ufo-aufbau", title: "Organisationsform bestimmen und bewerten",
      html: "<p>Die <b>Alpentec GmbH</b> (800 MA) stellt Skibindungen, E-Bike-Antriebe und Medizintechnik-Komponenten her. Unter der Geschäftsführung gibt es drei Bereiche „Wintersport“, „E-Mobility“ und „Medtech“, jeweils mit eigener Entwicklung, Produktion und eigenem Vertrieb sowie Ergebnisverantwortung. Zentral bleiben nur Finanzen und Recht. In letzter Zeit beschwert sich der CFO, dass drei Bereiche je eine eigene CAD-Software und eigene Einkaufsabteilungen haben.</p><ol><li>Welche Organisationsform liegt vor? Begründe.</li><li>Nenne zwei Vorteile und zwei Nachteile dieser Form und ordne die Beschwerde des CFO zu.</li><li>Welche Ursachen sprechen bei Alpentec für diese Form?</li></ol>",
      solution: "<ol><li><b>Divisionale Organisation (Spartenorganisation)</b> nach Produktgruppen (Objektprinzip): Bereiche mit eigenen Funktionen und Ergebnisverantwortung; zentrale Funktionen (Finanzen, Recht) als Zentralbereiche.</li><li>Vorteile: <b>Marktorientierung</b>, <b>Flexibilität</b>, <b>Autonomie</b> der Sparten, <b>Entlastung der Unternehmensführung</b>. Nachteile: <b>Bereichsegoismen</b>, Konflikte zwischen Sparten, <b>geringe Ressourceneffizienz</b>. Die Beschwerde (doppelte Software, doppelter Einkauf) ist genau die geringe Ressourceneffizienz/Doppelarbeit – Abhilfe: Einkauf/IT als Zentralbereich oder Shared Service.</li><li>Ursachen: <b>Diversifikation</b> (sehr unterschiedliche Märkte), Größenwachstum, steigende Umweltdynamik – unterschiedliche Kunden erfordern marktnahe Einheiten.</li></ol>" },
    { id: "ufx-r2", topic: "ufo-aufbau", title: "Matrix oder nicht? Drei Kurzfälle",
      html: "<p>Bestimme jeweils die Organisationsform:</p><ol><li>Ein Handwerksbetrieb: Jede:r Mitarbeitende hat genau eine:n Vorgesetzte:n, der Meister entscheidet alles; eine Assistentin bereitet Angebote vor, darf aber nichts entscheiden.</li><li>Ein Konzern: Länderchefs (Österreich, Deutschland, Schweiz) und Produktmanager (Kaffee, Tee) haben gleichberechtigtes Weisungsrecht gegenüber den Teams im jeweiligen Land/Produkt.</li><li>Ein Start-up mit 40 MA: Abteilungen Entwicklung, Marketing, Vertrieb, Finanzen unter der Geschäftsführung.</li></ol>",
      solution: "<ol><li><b>Stablinienorganisation</b> (Einlinie + Stab): Die Assistentin ist eine Stabsstelle (Entscheidungsvorbereitung ohne Entscheidungskompetenz).</li><li><b>Balancierte Matrixorganisation</b> (Zweiliniensystem: Region × Produkt, gleichberechtigte Weisungsbefugnis). Achtung: hohes Konfliktpotenzial, große Leitungsspanne.</li><li><b>Funktionale Organisation</b> (Gliederung nach Verrichtungen, Einliniensystem, Tendenz zur Zentralisation).</li></ol>" },
    { id: "ufx-r3", topic: "ufo-stratana", title: "Five Forces und SWOT für einen E-Scooter-Verleih",
      html: "<p>Ein regionaler E-Scooter-Verleih in Graz: Es gibt zwei große internationale Konkurrenten, die Stadt plant strengere Abstellregeln, Scooter werden von nur zwei Herstellern in China geliefert, Kund:innen wechseln per App in Sekunden den Anbieter, der Ausbau von Radwegen und Leih-E-Bikes schreitet voran. Das Unternehmen hat eine sehr gute Wartungsquote und Kooperationen mit der FH, aber wenig Kapital.</p><ol><li>Ordne die Fakten den fünf Kräften zu und beurteile die Branchenattraktivität.</li><li>Erstelle eine SWOT (je mindestens ein Punkt).</li></ol>",
      solution: "<ol><li><b>Rivalität</b>: hoch (große Konkurrenten, kaum Differenzierung). <b>Lieferantenmacht</b>: hoch (nur zwei Hersteller → hoher Konzentrationsgrad). <b>Abnehmermacht</b>: hoch (keine Umstellkosten, hoher Standardisierungsgrad). <b>Substitute</b>: Leih-E-Bikes, Rad, Öffis → hohe Bedrohung. <b>Neue Anbieter</b>: mäßig – geringer Kapitalbedarf je Fahrzeug, aber staatliche Politik (Lizenzen/Abstellregeln) als Barriere. ⇒ Branche wenig attraktiv.</li><li><b>Stärken</b>: Wartungsqualität, FH-Kooperation. <b>Schwächen</b>: wenig Kapital, regional klein. <b>Chancen</b>: Radwegausbau/Mobilitätswende, Kooperation mit Stadt bei Abstellzonen. <b>Risiken</b>: strengere Regulierung, Preiskampf der Großen, Substitute, Lieferantenabhängigkeit. Chancen/Risiken kommen aus der Umweltanalyse, Stärken/Schwächen aus der Unternehmensanalyse – stets relativ zu den Konkurrenten.</li></ol>" },
    { id: "ufx-r4", topic: "ufo-normativ", title: "Vision, Ziel und Leitbild formulieren",
      html: "<p>Ein Grazer Software-Unternehmen (Lernplattformen für Hochschulen) möchte seine normative Führung schärfen.</p><ol><li>Formuliere eine Vision und prüfe sie gegen die vier Anforderungen.</li><li>Formuliere daraus ein Unternehmensziel mit allen fünf Dimensionen und prüfe es nach SMART.</li><li>Nenne die vier Funktionen eines Leitbilds und erkläre, wie es sich von der Mission unterscheidet.</li></ol>",
      solution: "<ol><li>Beispiel: „Bis 2032 lernt jede:r Studierende im DACH-Raum mit einer Plattform, die sich wie ein persönlicher Tutor anfühlt.“ – <b>richtungsweisend</b> (klare Zukunftsrichtung), <b>anspornend</b> (begeisternd, fordernd), <b>plausibel</b> (realistisch für einen Spezialisten), <b>prägnant</b> (ein kommunizierbarer Satz).</li><li>Beispiel: „Wir erhöhen den Marktanteil (Inhalt) um 5 Prozentpunkte (Ausmaß) bis Dezember 2027 (Termin) in Deutschland (Ort); verantwortlich: Leitung Vertrieb (Verantwortung).“ SMART: spezifisch (Marktanteil, Deutschland), messbar (5 PP), anspruchsvoll/akzeptiert, realistisch, terminiert.</li><li>Funktionen: <b>Orientierung, Konkretisierung, Legitimation, Motivation</b>. Mission = Auftrag und Beitrag zur Gesellschaft, stärker kundenorientiert/nach außen; Leitbild = schriftliche Dokumentation von Werten, Grundsätzen, Zielen als Orientierung für Mitarbeitende, wirkt stärker nach innen.</li></ol>" },
    { id: "ufx-r5", topic: "ufx-skalierung", title: "Skalierungsweg wählen",
      html: "<p>Eine erfolgreiche Grazer Bubble-Tea-Kette (3 Filialen) will innerhalb von zwei Jahren in ganz Österreich präsent sein. Kapital ist knapp, das Rezept und die Marke sind das wichtigste Asset. Vergleiche die vier Skalierungswege und gib eine begründete Empfehlung inkl. Risiken und Gegenmaßnahmen.</p>",
      solution: "<p><b>Organisch</b>: nachhaltig, wenig Risiko, aber zu langsam für 2 Jahre. <b>Akquisition</b>: schnell, aber Kapitalbedarf und hohes Risiko – passt nicht zu knappem Kapital. <b>Partnerschaften</b> (z. B. Shop-in-Shop): schnell, aber Qualitätsrisiko. <b>Franchising</b>: sehr hohe Skalierbarkeit mit dem Kapital der Franchisenehmer, Nachteil: geringeres Einkommenspotenzial (nur Gebühren).</p><p><b>Empfehlung: Franchising</b> (ggf. ergänzt um einige eigene Flagship-Filialen). Risiken/Herausforderungen: Qualitätsverlust, Komplexität, Kulturwandel, Verlust der Agilität. Gegenmaßnahmen (nachhaltige Skalierung): standardisierte Prozesse/Handbuch, Technologie (Kassensystem, Bestellplattform), Schulung/Talententwicklung der Franchisenehmer, Kundenbindung (App, Treueprogramm).</p>" },
    { id: "ufx-r6", topic: "ufo-kontrolle", title: "Balanced Scorecard und strategische Kontrolle",
      html: "<p>Strategie eines Fahrradhändlers: „Wir werden durch erstklassigen Service die Nr. 1 für E-Bikes in der Steiermark.“</p><ol><li>Leite für jede BSC-Perspektive ein Ziel und eine Kennzahl ab.</li><li>Wie würdest du die Strategie mit den drei Formen der strategischen Kontrolle überwachen?</li></ol>",
      solution: "<ol><li><b>Finanzen</b>: profitables Wachstum – Umsatzwachstum E-Bikes, Deckungsbeitrag. <b>Kunden</b>: Marktführerschaft/Zufriedenheit – Marktanteil Steiermark, Weiterempfehlungsrate (NPS). <b>Interne Prozesse</b>: schnellster Werkstattservice – Reparaturdurchlaufzeit (Tage). <b>Lernen &amp; Entwicklung</b>: qualifizierte Mechaniker – Schulungsstunden/Zertifizierungen je MA.</li><li><b>Prämissenkontrolle</b>: Gelten Annahmen weiter (E-Bike-Nachfrage wächst, Förderungen, kein großer Online-Konkurrent mit Vor-Ort-Service)? <b>Durchführungskontrolle</b>: Meilensteine prüfen (zweite Werkstatt eröffnet, Servicezeit &lt; 3 Tage erreicht). <b>Strategische Überwachung</b>: ungerichtetes Beobachten von Umwelt und Markt (neue Technologien, Regulierung) als Frühwarnsystem.</li></ol>" },
    { id: "ufx-r7", topic: "ufx-verfassung", title: "Organe und Governance einer AG",
      html: "<p>In einer börsennotierten deutschen AG soll der Vorstandsvorsitzende wegen eines Bilanzskandals abberufen werden. Die Aktionär:innen sind empört.</p><ol><li>Wer kann den Vorstand abberufen, und wie können die Aktionär:innen Einfluss nehmen?</li><li>Wie wäre das in einer US-Board-Verfassung?</li><li>Welche Instrumente der Corporate Governance hätten den Skandal verhindern sollen, und welchem Ethik-Typ entspricht das Unternehmen?</li></ol>",
      solution: "<ol><li>Der <b>Aufsichtsrat</b> bestellt und beruft den Vorstand ab. Die Aktionär:innen wirken über die <b>Hauptversammlung</b>: Sie wählen/berufen die Aufsichtsratsmitglieder (der Anteilseignerseite) ab, haben Auskunfts-, Stimm- und Anfechtungsrecht.</li><li>Im <b>monistischen Board</b> entscheidet das Board of Directors (mit Managing und Outside Directors) selbst über die geschäftsführenden Directors; die Shareholders' Meeting bestellt bzw. beruft das Board ab.</li><li>Internes Kontrollsystem: <b>Risikomanagement, (interne) Revision, Compliance</b>; zusätzlich Kodizes/Ethikkodex. Bilanzfälschung = <b>unmoralisches</b> Unternehmen.</li></ol>" }
  ]
};
})();
